var date2 = Date.now() + 365 * 24 * 60 * 60 * 1000;
let criteria = '[' + encodeURIComponent('?') + '(' + '@.startingDate<' + date2 + ')]';

var dat = {
  'perfManagement.create': {
    numCols: 12 / 3,
    url: 'perfmanagement/v1/kpimaster/_create',
    useTimestamp: true,
    objectName: 'KPIs',
    idJsonPath: 'KPIs[0].code',
    groups: [
      {
        label: 'perfManagement.create.KPIs.groups.kpiMasterCreate',
        name: 'kpiMaster',
        fields: [
          {
            name: 'kpiDepartment',
            jsonPath: 'KPIs[0].departmentId',
            label: 'perfManagement.create.KPIs.groups.kpiDepartment',
            isRequired: true,
            pattern: '',
            type: 'singleValueList',
            url: 'egov-mdms-service/v1/_get?tenantId=default&moduleName=common-masters&masterName=Department|$..id|$..name',
            isDisabled: false,
            requiredErrMsg: '',
            isStateLevel: true,
          },
          {
            name: 'kpiCategory',
            jsonPath: 'KPIs[0].categoryId',
            label: 'perfManagement.create.KPIs.groups.kpiCategory',
            isRequired: true,
            pattern: '',
            type: 'singleValueList',
            url: '/egov-mdms-service/v1/_get?&moduleName=PM&masterName=KpiCategory|$..code|$..name',
            isDisabled: false,
            requiredErrMsg: '',
            isStateLevel: true,
          },
          {
            name: 'kpiDate',
            jsonPath: 'KPIs[0].financialYear',
            label: 'perfManagement.create.KPIs.groups.kpiDate',
            isRequired: true,
            pattern: '',
            type: 'singleValueList',
            url:
              'egov-mdms-service/v1/_get?tenantId=' +
              localStorage.tenantId.split('.')[0] +
              '&masterName=FinancialYear&moduleName=egf-master&filter=' +
              criteria +
              '|$..finYearRange|$..finYearRange',
            isDisabled: false,
            requiredErrMsg: '',
            isStateLevel: true,
          },
        ],
      },
      {
        label: '',
        name: 'kpiNameBlock',
        fields: [
          {
            name: 'kpiName',
            jsonPath: 'KPIs[0].name',
            label: 'perfManagement.create.KPIs.groups.kpiName',
            isRequired: true,
            pattern: '',
            type: 'text',
            isDisabled: false,
            requiredErrMsg: '',
            maxLength: 64,
          },
          {
            name: 'kpitype',
            jsonPath: 'KPIs[0].targetType',
            label: 'perfManagement.create.KPIs.groups.kpitype',
            pattern: '',
            type: 'radio',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            values: [
              {
                label: 'perfManagement.update.KPIs.groups.updatekpitype.text',
                value: 'TEXT',
              },
              {
                label: 'perfManagement.create.KPIs.groups.kpitype.value',
                value: 'VALUE',
              },
              {
                label: 'perfManagement.create.KPIs.groups.kpitype.objective',
                value: 'OBJECTIVE',
              },
            ],
            defaultValue: 'TEXT',
          },
        ],
      },

      {
        label: 'perfManagement.create.KPIs.groups.kpiInstruct',
        name: 'kpiInstruct',
        fields: [
          {
            name: 'kpiInstruction',
            jsonPath: 'KPIs[0].instructions',
            label: '',
            pattern: '',
            type: 'textarea',
            fullWidth: true,
            isDisabled: false,
            requiredErrMsg: '',
          },
        ],
      },
      {
        label: 'perfManagement.create.KPIs.groups.kpiDoc',
        name: 'kpiDoc',
        multiple: true,
        jsonPath: 'KPIs[0].documentsReq',
        fields: [
          {
            name: 'kpidocName',
            jsonPath: 'KPIs[0].documentsReq[0].name',
            label: 'perfManagement.create.KPIs.groups.kpidocName',
            pattern: '',
            type: 'text',
            isDisabled: false,
            url: '',
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'kpidocMandatory',
            jsonPath: 'KPIs[0].documentsReq[0].active',
            label: 'perfManagement.create.KPIs.groups.kpidocMandatory',
            pattern: '',
            type: 'checkbox',
            defaultValue: 0,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            url: '',
          },
        ],
      },
    ],
  },
  'perfManagement.search': {
    numCols: 12 / 3,
    url: '/perfmanagement/v1/kpimaster/_search',
    useTimestamp: true,
    objectName: 'KPIs.kpiList',
    groups: [
      {
        label: 'perfManagement.search.KPIs.groups.kpiSearch',
        name: 'kpiSearch',
        fields: [
          {
            name: 'searchkpiDepartment',
            jsonPath: 'departmentId',
            label: 'perfManagement.search.KPIs.groups.searchkpiDepartment',
            pattern: '',
            type: 'singleValueList',
            url:
              'egov-mdms-service/v1/_get?tenantId=' +
              localStorage.tenantId.split('.')[0] +
              '&moduleName=common-masters&masterName=Department|$..id|$..name',
            isDisabled: false,
            isRequired: true,
            requiredErrMsg: '',
            isStateLevel: true,
          },
          {
            name: 'kpiCategory',
            jsonPath: 'categoryId',
            label: 'perfManagement.create.KPIs.groups.kpiCategory',
            pattern: '',
            type: 'singleValueList',
            url: '/egov-mdms-service/v1/_get?&moduleName=PM&masterName=KpiCategory|$..code|$..name',
            isDisabled: false,
            requiredErrMsg: '',
            isStateLevel: true,
          },
          {
            name: 'searchkpiCode',
            jsonPath: 'kpiCode',
            label: 'perfManagement.search.KPIs.groups.searchkpiCode',
            pattern: '',
            type: 'text',
            isDisabled: false,
            requiredErrMsg: '',
          },
          {
            name: 'searchkpiName',
            jsonPath: 'kpiName',
            label: 'perfManagement.search.KPIs.groups.searchkpiName',
            pattern: '',
            type: 'text',
            isDisabled: false,
            requiredErrMsg: '',
          },
        ],
      },
    ],
    result: {
      header: [
        { label: 'perfManagement.search.KPIs.groups.searchkpiName' },
        { label: 'perfManagement.search.KPIs.groups.searchkpiCode' },
        { label: 'perfManagement.create.KPIs.groups.kpiDate' },
        { label: 'perfManagement.create.KPIs.groups.kpitype' },
      ],
      values: ['name', 'code', 'financialYear', 'targetType'],
      resultPath: 'KPIs',
      rowClickUrlUpdate: '/update/perfManagement/kpi/{code}',
      rowClickUrlView: '/view/perfManagement/kpi/{code}',
    },
  },
  'perfManagement.view': {
    numCols: 12 / 2,
    url: '/perfmanagement/v1/kpimaster/_search?kpiCode={code}',
    useTimestamp: true,
    objectName: 'KPIs',
    groups: [
      {
        label: 'perfManagement.view.KPIs.groups.viewKPI',
        name: 'viewKPI',
        fields: [
          {
            name: 'viewkpiDepartment',
            jsonPath: 'KPIs[0].department.name',
            label: 'perfManagement.view.KPIs.groups.viewkpiDepartment',
            pattern: '',
            type: 'text',
            isDisabled: false,
            requiredErrMsg: '',
            isStateLevel: true,
          },
          {
            name: 'viewkpiDate',
            jsonPath: 'KPIs[0].financialYear',
            label: 'perfManagement.view.KPIs.groups.viewkpiDate',
            isRequired: true,
            pattern: '',
            type: 'singleValueList',
            isDisabled: false,
            requiredErrMsg: '',
            isStateLevel: true,
          },
        ],
      },
      {
        label: '',
        name: 'viewKpiNameBlock',
        fields: [
          {
            name: 'viewkpiName',
            jsonPath: 'KPIs[0].name',
            label: 'perfManagement.view.KPIs.groups.viewkpiName',
            isRequired: true,
            pattern: '',
            type: 'text',
            isDisabled: false,
            requiredErrMsg: '',
          },
          {
            name: 'viewkpiCode',
            jsonPath: 'KPIs[0].code',
            label: 'perfManagement.view.KPIs.groups.viewkpiCode',
            isRequired: true,
            pattern: '',
            type: 'text',
            isDisabled: false,
            requiredErrMsg: '',
          },
        ],
      },
      {
        label: 'perfManagement.view.KPIs.groups.viewKpiInstruc',
        name: 'viewKpiInstruc',
        fields: [
          {
            name: 'viewkpiInstruction',
            jsonPath: 'KPIs[0].instructions',
            label: '',
            pattern: '',
            type: 'textarea',
            fullWidth: true,
            isDisabled: false,
            requiredErrMsg: '',
          },
        ],
      },
      {
        label: 'perfManagement.view.KPIs.groups.viewkpiDocuments',
        name: 'viewkpiDocuments',
        multiple: true,
        hide: "this.props.getVal('KPIs[0].documentsReq.length') == 0?true:false",
        jsonPath: 'KPIs[0].documentsReq',
        fields: [
          {
            name: 'viewkpidoc',
            jsonPath: 'KPIs[0].documentsReq[0].name',
            label: 'perfManagement.view.KPIs.groups.viewkpidoc',
            pattern: '',
            type: 'text',
            isDisabled: false,
            url: '',
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          
          {
            name: 'viewkpidocMandatory',
            jsonPath: 'KPIs[0].documentsReq[0].active',
            label: 'perfManagement.view.KPIs.groups.viewkpidocMandatory',
            pattern: '',
            type: 'checkbox',
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            url: '',
          },
        ],
      },
    ],
  },
  'perfManagement.update': {
    numCols: 12 / 3,
    searchUrl: '/perfmanagement/v1/kpimaster/_search?kpiCode={code}',
    url: 'perfmanagement/v1/kpimaster/_update',
    useTimestamp: true,
    objectName: 'KPIs',
    idJsonPath: 'KPIs[0]',
    groups: [
      {
        label: 'perfManagement.update.KPIs.groups.updateKpiDepartmentBlock',
        name: 'updateKpiDepartmentBlock',
        fields: [
          {
            name: 'updatekpiDepartment',
            jsonPath: 'KPIs[0].department.id',
            url: '/egov-mdms-service/v1/_get?&moduleName=common-masters&masterName=Department|$..id|$..name',
            label: 'perfManagement.update.KPIs.groups.updateKpiDepartmentBlock',
            pattern: '',
            type: 'singleValueList',
            isDisabled: false,
            requiredErrMsg: '',
            isStateLevel: true,
          },
          {
            name: 'updatekpiCategory',
            jsonPath: 'KPIs[0].categoryId',
            label: 'perfManagement.create.KPIs.groups.kpiCategory',
            isRequired: true,
            pattern: '',
            type: 'singleValueList',
            url: '/egov-mdms-service/v1/_get?&moduleName=PM&masterName=KpiCategory|$..code|$..name',
            isDisabled: false,
            requiredErrMsg: '',
            isStateLevel: true,
          },
          {
            name: 'updatekpiDate',
            jsonPath: 'KPIs[0].financialYear',
            label: 'perfManagement.update.KPIs.groups.updatekpiDate',
            isRequired: true,
            pattern: '',
            type: 'singleValueList',
            url:
              'egov-mdms-service/v1/_get?tenantId=' +
              localStorage.tenantId.split('.')[0] +
              '&masterName=FinancialYear&moduleName=egf-master&filter=' +
              criteria +
              '|$..finYearRange|$..finYearRange',
            isDisabled: false,
            requiredErrMsg: '',
            isStateLevel: true,
          },
        ],
      },
      {
        label: '',
        name: 'updateKpi',
        fields: [
          {
            name: 'updatekpiName',
            jsonPath: 'KPIs[0].name',
            label: 'perfManagement.update.KPIs.groups.updatekpiName',
            isRequired: true,
            pattern: '',
            type: 'text',
            isDisabled: false,
            requiredErrMsg: '',
            maxLength: 64,
          },
          {
            name: 'updatekpitype',
            jsonPath: 'KPIs[0].targetType',
            label: 'perfManagement.update.KPIs.groups.updatekpitype',
            pattern: '',
            type: 'radio',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            defaultValue: true,
            values: [
              {
                label: 'perfManagement.update.KPIs.groups.updatekpitype.text',
                value: 'TEXT',
              },
              {
                label: 'perfManagement.update.KPIs.groups.updatekpitype.value',
                value: 'VALUE',
              },
              {
                label: 'perfManagement.update.KPIs.groups.updatekpitype.objective',
                value: 'OBJECTIVE',
              },
            ],
          },
        ],
      },

      {
        name: 'updateKpiInstruc',
        label: 'perfManagement.update.KPIs.groups.updateKpiInstruc',
        fields: [
          {
            name: 'updatekpiInstruction',
            jsonPath: 'KPIs[0].instructions',
            label: '',
            pattern: '',
            type: 'textarea',
            fullWidth: true,
            isDisabled: false,
            requiredErrMsg: '',
          },
        ],
      },
      {
        label: 'perfManagement.update.KPIs.groups.updatekpiDocuments',
        name: 'updatekpiDocuments',
        multiple: true,
        jsonPath: 'KPIs[0].documentsReq',
        fields: [
          {
            name: 'updatekpidoc',
            jsonPath: 'KPIs[0].documentsReq[0].name',
            label: 'perfManagement.update.KPIs.groups.updatekpidoc',
            pattern: '',
            type: 'text',
            isDisabled: false,
            url: '',
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'updatekpidocMandatory',
            jsonPath: 'KPIs[0].documentsReq[0].active',
            label: 'perfManagement.update.KPIs.groups.updatekpidocMandatory',
            pattern: '',
            type: 'checkbox',
            isDisabled: false,
            defaultValue: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            url: '',
          },
        ],
      },
    ],
  },
};
export default dat;
