package org.jamabandi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-09-16T13:35:07.671+05:30
 * Generated source version: 3.5.3
 *
 */
@WebService(targetNamespace = "http://jamabandi.org/", name = "LRDataServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LRDataServiceHttpPost {

    @WebMethod(operationName = "GetMurabaFromParatPatwar")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getMurabaFromParatPatwar(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Period", name = "Period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period
    );

    @WebMethod(operationName = "GetRemarksByKhewat")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getRemarksByKhewat(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "period", name = "period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat
    );

    @WebMethod(operationName = "GetCompleteULBPropertyDueByID")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getCompleteULBPropertyDueByID(

        @WebParam(partName = "propertyid", name = "propertyid", targetNamespace = "http://jamabandi.org/")
        java.lang.String propertyid,
        @WebParam(partName = "mcid", name = "mcid", targetNamespace = "http://jamabandi.org/")
        java.lang.String mcid
    );

    @WebMethod(operationName = "GetKhasraListByNVCODE")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKhasraListByNVCODE(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Muraba", name = "Muraba", targetNamespace = "http://jamabandi.org/")
        java.lang.String muraba
    );

    @WebMethod(operationName = "GetKharabaKhewats")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKharabaKhewats(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "kgyear", name = "kgyear", targetNamespace = "http://jamabandi.org/")
        java.lang.String kgyear,
        @WebParam(partName = "fasalseasoncode", name = "fasalseasoncode", targetNamespace = "http://jamabandi.org/")
        java.lang.String fasalseasoncode,
        @WebParam(partName = "fasalcategorycode", name = "fasalcategorycode", targetNamespace = "http://jamabandi.org/")
        java.lang.String fasalcategorycode
    );

    @WebMethod(operationName = "GetKhatonis")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKhatonis(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "period", name = "period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat
    );

    @WebMethod(operationName = "CollectorateNew")
    @WebResult(name = "DataTable", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public DataTable collectorateNew(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "period", name = "period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period
    );

    @WebMethod(operationName = "GetDistrict2")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getDistrict2(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key
    );

    @WebMethod(operationName = "GetCultivableKhasraListByKhewatKhatoniOnline")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getCultivableKhasraListByKhewatKhatoniOnline(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Period", name = "Period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat,
        @WebParam(partName = "khatoni", name = "khatoni", targetNamespace = "http://jamabandi.org/")
        java.lang.String khatoni
    );

    @WebMethod(operationName = "GetGovtKhewats")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getGovtKhewats(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode
    );

    @WebMethod(operationName = "GetMurabaFromParatPatwarByLGCode")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getMurabaFromParatPatwarByLGCode(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "LGVillCode", name = "LGVillCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String lgVillCode
    );

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String isKhasraBlocked(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "nvcode", name = "nvcode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvcode,
        @WebParam(partName = "period", name = "period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "mustil", name = "mustil", targetNamespace = "http://jamabandi.org/")
        java.lang.String mustil,
        @WebParam(partName = "khasra", name = "khasra", targetNamespace = "http://jamabandi.org/")
        java.lang.String khasra
    );

    @WebMethod(operationName = "GetKhasraGirdawariYear")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKhasraGirdawariYear(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "jamyear", name = "jamyear", targetNamespace = "http://jamabandi.org/")
        java.lang.String jamyear
    );

    @WebMethod(operationName = "GetUrbanOutsideMCVillagesforRegistration")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getUrbanOutsideMCVillagesforRegistration(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode
    );

    @WebMethod(operationName = "GetAbadiKhewats")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getAbadiKhewats(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode
    );

    @WebMethod(operationName = "GetJurisdictionRural")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getJurisdictionRural(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode
    );

    @WebMethod(operationName = "GetTehsilWH")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getTehsilWH(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "SCode", name = "SCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String sCode,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode
    );

    @WebMethod(operationName = "GetUrbanOutsideMCSegmentsforRegistration")
    @WebResult(name = "DataTable", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public DataTable getUrbanOutsideMCSegmentsforRegistration(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode
    );

    @WebMethod(operationName = "GetOwnersOnline")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getOwnersOnline(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Mustno", name = "Mustno", targetNamespace = "http://jamabandi.org/")
        java.lang.String mustno,
        @WebParam(partName = "Khasra", name = "Khasra", targetNamespace = "http://jamabandi.org/")
        java.lang.String khasra
    );

    @WebMethod(operationName = "GetCultivatorListByKhewat2")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getCultivatorListByKhewat2(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "period", name = "period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat
    );

    @WebMethod(operationName = "GetDeedDetailsForCMDB")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getDeedDetailsForCMDB(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "RegDate", name = "RegDate", targetNamespace = "http://jamabandi.org/")
        java.lang.String regDate
    );

    @WebMethod(operationName = "GetAbadiKhasraListByKhewatKhatoniOnlineMorni")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getAbadiKhasraListByKhewatKhatoniOnlineMorni(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Period", name = "Period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat,
        @WebParam(partName = "khatoni", name = "khatoni", targetNamespace = "http://jamabandi.org/")
        java.lang.String khatoni
    );

    @WebMethod(operationName = "GetVillageDetails")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getVillageDetails(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode
    );

    @WebMethod(operationName = "GetKharabaKhasra")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKharabaKhasra(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "kgyear", name = "kgyear", targetNamespace = "http://jamabandi.org/")
        java.lang.String kgyear,
        @WebParam(partName = "fasalseasoncode", name = "fasalseasoncode", targetNamespace = "http://jamabandi.org/")
        java.lang.String fasalseasoncode,
        @WebParam(partName = "fasalcategorycode", name = "fasalcategorycode", targetNamespace = "http://jamabandi.org/")
        java.lang.String fasalcategorycode,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat,
        @WebParam(partName = "khatoni", name = "khatoni", targetNamespace = "http://jamabandi.org/")
        java.lang.String khatoni
    );

    @WebMethod(operationName = "GetKhasraListByMurabaParatPatwar")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKhasraListByMurabaParatPatwar(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Period", name = "Period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "Muraba", name = "Muraba", targetNamespace = "http://jamabandi.org/")
        java.lang.String muraba
    );

    @WebMethod(operationName = "GetUniqueKhasraByNVCODE")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getUniqueKhasraByNVCODE(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode
    );

    @WebMethod(operationName = "GetOwnersbykhewat")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getOwnersbykhewat(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "_Khewat", name = "_Khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat
    );

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String isKhasraRCCMSPending(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "nvcode", name = "nvcode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvcode,
        @WebParam(partName = "mustil", name = "mustil", targetNamespace = "http://jamabandi.org/")
        java.lang.String mustil,
        @WebParam(partName = "khasra", name = "khasra", targetNamespace = "http://jamabandi.org/")
        java.lang.String khasra
    );

    @WebMethod(operationName = "GetTehsil2")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getTehsil2(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode
    );

    @WebMethod(operationName = "Collectorate")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String collectorate(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode
    );

    @WebMethod(operationName = "GetOwnerListByNVCODE")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getOwnerListByNVCODE(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode
    );

    @WebMethod(operationName = "GetKhewatTotalArea")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKhewatTotalArea(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "dcode", name = "dcode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dcode,
        @WebParam(partName = "tcode", name = "tcode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tcode,
        @WebParam(partName = "nvcode", name = "nvcode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvcode,
        @WebParam(partName = "period", name = "period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat
    );

    @WebMethod(operationName = "GetKhasra")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKhasra(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "period", name = "period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat,
        @WebParam(partName = "khatoni", name = "khatoni", targetNamespace = "http://jamabandi.org/")
        java.lang.String khatoni,
        @WebParam(partName = "Muraba", name = "Muraba", targetNamespace = "http://jamabandi.org/")
        java.lang.String muraba
    );

    @WebMethod(operationName = "GetKhasraListByNVCODE3")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKhasraListByNVCODE3(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Muraba", name = "Muraba", targetNamespace = "http://jamabandi.org/")
        java.lang.String muraba
    );

    @WebMethod(operationName = "GetKhasraListByNVCODE2")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKhasraListByNVCODE2(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Muraba", name = "Muraba", targetNamespace = "http://jamabandi.org/")
        java.lang.String muraba
    );

    @WebMethod(operationName = "GetDistrict")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getDistrict(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "SCode", name = "SCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String sCode
    );

    @WebMethod(operationName = "GetMutPendingForCMDB")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getMutPendingForCMDB(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode
    );

    @WebMethod(operationName = "GetKGDetails")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKGDetails(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "KGYear", name = "KGYear", targetNamespace = "http://jamabandi.org/")
        java.lang.String kgYear,
        @WebParam(partName = "Season", name = "Season", targetNamespace = "http://jamabandi.org/")
        java.lang.String season,
        @WebParam(partName = "Muraba", name = "Muraba", targetNamespace = "http://jamabandi.org/")
        java.lang.String muraba
    );

    @WebMethod(operationName = "GetOwnersbykhewat2")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getOwnersbykhewat2(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Period", name = "Period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "_Khewat", name = "_Khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat
    );

    @WebMethod(operationName = "GetPanchayatKhewats")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getPanchayatKhewats(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode
    );

    @WebMethod(operationName = "GetKhasraList")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKhasraList(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Period", name = "Period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat
    );

    @WebMethod(operationName = "GetKGVillages")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKGVillages(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "KGYear", name = "KGYear", targetNamespace = "http://jamabandi.org/")
        java.lang.String kgYear,
        @WebParam(partName = "Season", name = "Season", targetNamespace = "http://jamabandi.org/")
        java.lang.String season
    );

    @WebMethod(operationName = "GetKharabaKhatoni")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKharabaKhatoni(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "kgyear", name = "kgyear", targetNamespace = "http://jamabandi.org/")
        java.lang.String kgyear,
        @WebParam(partName = "fasalseasoncode", name = "fasalseasoncode", targetNamespace = "http://jamabandi.org/")
        java.lang.String fasalseasoncode,
        @WebParam(partName = "fasalcategorycode", name = "fasalcategorycode", targetNamespace = "http://jamabandi.org/")
        java.lang.String fasalcategorycode,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat
    );

    @WebMethod(operationName = "GetCultivatorListByKhatoni")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getCultivatorListByKhatoni(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "period", name = "period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat,
        @WebParam(partName = "khatoni", name = "khatoni", targetNamespace = "http://jamabandi.org/")
        java.lang.String khatoni,
        @WebParam(partName = "kashatCode", name = "kashatCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String kashatCode
    );

    @WebMethod(operationName = "GetAbadiKhasraListByKhewatOnline")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getAbadiKhasraListByKhewatOnline(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Period", name = "Period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat
    );

    @WebMethod(operationName = "GetAbadiKhasraListByKhewatKhatoniOnline")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getAbadiKhasraListByKhewatKhatoniOnline(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Period", name = "Period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat,
        @WebParam(partName = "khatoni", name = "khatoni", targetNamespace = "http://jamabandi.org/")
        java.lang.String khatoni
    );

    @WebMethod(operationName = "GetVillages")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getVillages(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "SCode", name = "SCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String sCode,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode
    );

    @WebMethod(operationName = "GetBoardCorporationKhewats")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getBoardCorporationKhewats(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode
    );

    @WebMethod(operationName = "GetAreaUnitsByVillage")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getAreaUnitsByVillage(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode
    );

    @WebMethod(operationName = "GetKhasraListByKhewatOnline2")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKhasraListByKhewatOnline2(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Period", name = "Period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat
    );

    @WebMethod(operationName = "GetArea")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getArea(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Mustno", name = "Mustno", targetNamespace = "http://jamabandi.org/")
        java.lang.String mustno,
        @WebParam(partName = "Khasra", name = "Khasra", targetNamespace = "http://jamabandi.org/")
        java.lang.String khasra
    );

    @WebMethod(operationName = "GetKhasraListByKhewatOnline3")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKhasraListByKhewatOnline3(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Period", name = "Period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat
    );

    @WebMethod(operationName = "GetNijiKhewatsMorni")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getNijiKhewatsMorni(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode
    );

    @WebMethod(operationName = "GetFasalSeason")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getFasalSeason(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key
    );

    @WebMethod(operationName = "GetOnlineKhatonisMorni")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getOnlineKhatonisMorni(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "period", name = "period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat
    );

    @WebMethod(operationName = "GetOnlineKhatonis")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getOnlineKhatonis(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "period", name = "period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat
    );

    @WebMethod(operationName = "GetKhasraListByMurabaParatPatwarLGCode")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKhasraListByMurabaParatPatwarLGCode(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "LGVillCode", name = "LGVillCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String lgVillCode,
        @WebParam(partName = "Muraba", name = "Muraba", targetNamespace = "http://jamabandi.org/")
        java.lang.String muraba
    );

    @WebMethod(operationName = "GetAbadiKhasraListByKhewatOnlineMorni")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getAbadiKhasraListByKhewatOnlineMorni(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Period", name = "Period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat
    );

    @WebMethod(operationName = "GetOwners")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getOwners(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Mustno", name = "Mustno", targetNamespace = "http://jamabandi.org/")
        java.lang.String mustno,
        @WebParam(partName = "Khasra", name = "Khasra", targetNamespace = "http://jamabandi.org/")
        java.lang.String khasra
    );

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getSwamitvaFull(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "propertyid", name = "propertyid", targetNamespace = "http://jamabandi.org/")
        java.lang.String propertyid
    );

    @WebMethod(operationName = "GetKhewats")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKhewats(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode
    );

    @WebMethod(operationName = "GetMurabaByNVCODE")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getMurabaByNVCODE(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode
    );

    @WebMethod(operationName = "GetAllKhewatsExceptGovt")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getAllKhewatsExceptGovt(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode
    );

    @WebMethod(operationName = "GetVillageDetailsLGCode")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getVillageDetailsLGCode(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "LGVillCode", name = "LGVillCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String lgVillCode
    );

    @WebMethod(operationName = "GetOwnerList2")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getOwnerList2(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "OwnerName", name = "OwnerName", targetNamespace = "http://jamabandi.org/")
        java.lang.String ownerName
    );

    @WebMethod(operationName = "GetOwnersByLGCode")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getOwnersByLGCode(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "LGVillCode", name = "LGVillCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String lgVillCode,
        @WebParam(partName = "Mustno", name = "Mustno", targetNamespace = "http://jamabandi.org/")
        java.lang.String mustno,
        @WebParam(partName = "Khasra", name = "Khasra", targetNamespace = "http://jamabandi.org/")
        java.lang.String khasra
    );

    @WebMethod(operationName = "GetOwnerList3")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getOwnerList3(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "OwnerName", name = "OwnerName", targetNamespace = "http://jamabandi.org/")
        java.lang.String ownerName
    );

    @WebMethod(operationName = "GetFasalCategory")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getFasalCategory(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "fasalseason", name = "fasalseason", targetNamespace = "http://jamabandi.org/")
        java.lang.String fasalseason
    );

    @WebMethod(operationName = "GetOwnerList4")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getOwnerList4(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Khewat", name = "Khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat
    );

    @WebMethod(operationName = "GetUrbanWithinMCSegmentsforRegistration")
    @WebResult(name = "DataTable", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public DataTable getUrbanWithinMCSegmentsforRegistration(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode
    );

    @WebMethod(operationName = "GetNijiKhewats")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getNijiKhewats(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode
    );

    @WebMethod(operationName = "GetVillages3")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getVillages3(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode
    );

    @WebMethod(operationName = "GetVillages2")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getVillages2(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "SCode", name = "SCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String sCode,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode
    );

    @WebMethod(operationName = "GetKharabaOwners")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKharabaOwners(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "jamperiod", name = "jamperiod", targetNamespace = "http://jamabandi.org/")
        java.lang.String jamperiod,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat,
        @WebParam(partName = "khatoni", name = "khatoni", targetNamespace = "http://jamabandi.org/")
        java.lang.String khatoni
    );

    @WebMethod(operationName = "GetJamabandiPeriod")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getJamabandiPeriod(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode
    );

    @WebMethod(operationName = "GetKhasraListByKhewat")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKhasraListByKhewat(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Period", name = "Period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat
    );

    @WebMethod(operationName = "GetConsignmentStatusByNVCode")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getConsignmentStatusByNVCode(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode
    );

    @WebMethod(operationName = "GetDistrictWH")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getDistrictWH(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "SCode", name = "SCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String sCode
    );

    @WebMethod(operationName = "GetOwnersbykhewatOnline")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getOwnersbykhewatOnline(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "_Khewat", name = "_Khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat
    );

    @WebMethod(operationName = "GetCultivatorListByKhewat")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getCultivatorListByKhewat(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "period", name = "period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat,
        @WebParam(partName = "kashatCode", name = "kashatCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String kashatCode
    );

    @WebMethod(operationName = "GetUELitigations")
    @WebResult(name = "DataTable", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public DataTable getUELitigations(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "period", name = "period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "must", name = "must", targetNamespace = "http://jamabandi.org/")
        java.lang.String must,
        @WebParam(partName = "khas", name = "khas", targetNamespace = "http://jamabandi.org/")
        java.lang.String khas
    );

    @WebMethod(operationName = "GetDBName")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getDBName(

        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode
    );

    @WebMethod(operationName = "GetKhasraListByKhewatOnline")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKhasraListByKhewatOnline(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Period", name = "Period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat
    );

    @WebMethod(operationName = "GetUrbanWithinMCVillagesforRegistration")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getUrbanWithinMCVillagesforRegistration(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode
    );

    @WebMethod(operationName = "GetKhasraListByMuraba")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getKhasraListByMuraba(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "Muraba", name = "Muraba", targetNamespace = "http://jamabandi.org/")
        java.lang.String muraba
    );

    @WebMethod(operationName = "GetOwnerList")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getOwnerList(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "period", name = "period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "OwnerName", name = "OwnerName", targetNamespace = "http://jamabandi.org/")
        java.lang.String ownerName
    );

    @WebMethod(operationName = "GetJurisdictionDetail")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getJurisdictionDetail(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode
    );

    @WebMethod(operationName = "GetOnlineVillForCMDB")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getOnlineVillForCMDB(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key
    );

    @WebMethod(operationName = "GetSegmentsFromTehsil")
    @WebResult(name = "DataTable", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public DataTable getSegmentsFromTehsil(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode
    );

    @WebMethod(operationName = "GetMuraba")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getMuraba(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "period", name = "period", targetNamespace = "http://jamabandi.org/")
        java.lang.String period,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat,
        @WebParam(partName = "khatoni", name = "khatoni", targetNamespace = "http://jamabandi.org/")
        java.lang.String khatoni
    );

    @WebMethod(operationName = "GetUpdateInsuredKharabaOwners")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getUpdateInsuredKharabaOwners(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode,
        @WebParam(partName = "jamperiod", name = "jamperiod", targetNamespace = "http://jamabandi.org/")
        java.lang.String jamperiod,
        @WebParam(partName = "khewat", name = "khewat", targetNamespace = "http://jamabandi.org/")
        java.lang.String khewat,
        @WebParam(partName = "khatoni", name = "khatoni", targetNamespace = "http://jamabandi.org/")
        java.lang.String khatoni,
        @WebParam(partName = "kashat", name = "kashat", targetNamespace = "http://jamabandi.org/")
        java.lang.String kashat,
        @WebParam(partName = "block", name = "block", targetNamespace = "http://jamabandi.org/")
        java.lang.String block,
        @WebParam(partName = "nameid", name = "nameid", targetNamespace = "http://jamabandi.org/")
        java.lang.String nameid,
        @WebParam(partName = "chk", name = "chk", targetNamespace = "http://jamabandi.org/")
        java.lang.String chk,
        @WebParam(partName = "remarks", name = "remarks", targetNamespace = "http://jamabandi.org/")
        java.lang.String remarks
    );

    @WebMethod(operationName = "GetTehsil")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getTehsil(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "SCode", name = "SCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String sCode,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode
    );

    @WebMethod(operationName = "GetNVCodeFromJurisdiction")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getNVCodeFromJurisdiction(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "vcode", name = "vcode", targetNamespace = "http://jamabandi.org/")
        java.lang.String vcode
    );

    @WebMethod(operationName = "GetAllKhewatsOnline")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getAllKhewatsOnline(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode
    );

    @WebMethod(operationName = "GetRuralVillagesforRegistration")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getRuralVillagesforRegistration(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode
    );

    @WebMethod(operationName = "GetAbadiKhewatsMorni")
    @WebResult(name = "string", targetNamespace = "http://jamabandi.org/", partName = "Body")
    public java.lang.String getAbadiKhewatsMorni(

        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://jamabandi.org/")
        java.lang.String key,
        @WebParam(partName = "DCode", name = "DCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String dCode,
        @WebParam(partName = "TCode", name = "TCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String tCode,
        @WebParam(partName = "NVCode", name = "NVCode", targetNamespace = "http://jamabandi.org/")
        java.lang.String nvCode
    );
}
