/*
 * eChallan System
 * ### API Specs For eChallan System ### 1. Generate the new challan. 2. Update the details of existing challan 3. Search the existing challan 4. Generate the demand and bill for the challan amount so that collection can be done in online and offline mode. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.egov.echallancalculation.model;

import java.util.Objects;

import org.egov.common.contract.response.ResponseInfo;
import org.egov.echallancalculation.web.models.calculation.Calculation;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

/**
 * Capture the challan details 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-10T16:46:24.044+05:30[Asia/Calcutta]")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Challan {

  @JsonProperty("citizen")

  private UserInfo citizen = null;

  @JsonProperty("id")

  private String id = null;

  @JsonProperty("tenantId")

  private String tenantId = null;

  @JsonProperty("businessService")

  private String businessService = null;

  @JsonProperty("challanNo")

  private String challanNo = null;

  @JsonProperty("referenceId")

  private String referenceId = null;

  @JsonProperty("description")

  private String description = null;

  @JsonProperty("accountId")

  private String accountId = null;

  @JsonProperty("additionalDetail")

  private Object additionalDetail = null;

  @JsonProperty("applicationStatus")

  private String applicationStatus = null;

  @JsonProperty("source")

  private String source = null;
  
  @JsonProperty("taxPeriodFrom")
  private Long taxPeriodFrom = null;

  @JsonProperty("taxPeriodTo")
  private Long taxPeriodTo = null;

  @JsonProperty("calculation")
  private Calculation calculation;
  
  @JsonProperty("amount")
  private List<Amount> amount;

  @JsonProperty("address")

  private Address address = null;

  @JsonProperty("auditDetails")

  private AuditDetails auditDetails = null;
  public Challan citizen(UserInfo citizen) {
    this.citizen = citizen;
    return this;
  }

  
}
