export const SHOW_MENU = "SHOW_MENU";
export const CHANGE_BOTTOM_NAVIGATION_INDEX = "CHANGE_BOTTOM_NAVIGATION_INDEX";
export const SHOW_DIALOG = "SHOW_DIALOG";
export const SHOW_TOAST = "SHOW_TOAST";
export const SET_LOGO = "SET_LOGO";
export const SET_APP_NAME = "SET_APP_NAME";
export const SET_ROUTE = "SET_ROUTE";
export const ADD_LOCALIZATION = "ADD_LOCALIZATION";
export const UPDATE_LOCALIZATION = "UPDATE_LOCALIZATION";
export const SET_USER_INFO = "SET_USER_INFO";
export const SET_USER_CURRENT_LOCATION = "SET_USER_CURRENT_LOCATION";
export const ADD_BREADCRUMB_ITEM = "ADD_BREADCRUMBS_ITEM";
export const REMOVE_BREADCRUMB_ITEM = "REMOVE_BREADCRUMB_ITEM";
export const FETCH_ACTIONMENU = "FETCH_ACTIONMENU";
export const FETCH_UI_COMMON_CONFIG = "FETCH_UI_COMMON_CONFIG";
export const FETCH_UI_COMMON_CONSTANTS = "FETCH_UI_COMMON_CONSTANTS";
export const UPDATE_ACTIVE_ROUTE_PATH = "UPDATE_ACTIVE_ROUTE_PATH";
export const SET_PREVIOUS_ROUTE = "SET_PREVIOUS_ROUTE";
export const GET_NOTIFICATION_COUNT = "GET_NOTIFICATION_COUNT";
export const GET_NOTIFICATIONS_COMPLETE = "GET_NOTIFICATIONS_COMPLETE";
export const GET_NOTIFICATIONS_PENDING = "GET_NOTIFICATIONS_PENDING";
export const GET_NOTIFICATIONS_ERROR = "GET_NOTIFICATIONS_ERROR";
export const FETCH_INBOX_COUNT = "FETCH_INBOX_COUNT";
export const FETCH_INBOX_RECORDS = "FETCH_INBOX_RECORDS";
export const FETCH_INBOX_RECORDS_ERROR = "FETCH_INBOX_RECORDS_ERROR";
export const FETCH_INBOX_RECORDS_PENDING = "FETCH_INBOX_RECORDS_PENDING";
export const FETCH_REM_INBOX_RECORDS_COMPLETE = "FETCH_REM_INBOX_RECORDS_COMPLETE";
export const FETCH_REM_INBOX_RECORDS_ERROR = "FETCH_REM_INBOX_RECORDS_ERROR";
export const FETCH_REM_INBOX_RECORDS_PENDING = "FETCH_REM_INBOX_RECORDS_PENDING";
export const FETCH_RESET_INBOX_RECORDS = "FETCH_RESET_INBOX_RECORDS";
export const FETCH_ACTIONMENU_PENDING = "FETCH_ACTIONMENU_PENDING";
export const FETCH_ACTIONMENU_ERROR = "FETCH_ACTIONMENU_ERROR";
export const FETCH_ESCALATED_INBOX_RECORDS_COMPLETE = "FETCH_ESCALATED_INBOX_RECORDS_COMPLETE";



