const constants = {
    APISTATUS: 'APISTATUS',
    CHANGE_NAME: 'CHANGE_NAME',
    RECEIVE_DASHBOARD_CONFIG_DATA: 'RECEIVE_DASHBOARD_CONFIG_DATA',
    GLOBAL_FILTER: 'GLOBAL_FILTER',
    DEMAND_AND_COLLECTION: 'DEMAND_AND_COLLECTION',
    GLOBAL_FILTER_DATA: 'GLOBAL_FILTER_DATA',
    CHARTS: 'CHARTS',
    LANGUAGE_CHANGE: 'LANGUAGE_CHANGE',
    FILE_UPLOAD: 'FILE_UPLOAD',
    FILE_UPLOAD_MOBILE: 'FILE_UPLOAD_MOBILE',
    FILE_UPLOAD_CARD: 'FILE_UPLOAD_CARD',
    S3_IMAGE: 'S3_IMAGE',
    S3_IMAGE_MOBILE: 'S3_IMAGE_MOBILE',
    S3_IMAGE_CARD: 'S3_IMAGE_CARD',
    MDMS: 'MDMS',
    ULBS_FILTER: 'ULBS_FILTER',
    TENENTS: 'TENENTS',
    WARD_DATA: 'WARD_DATA',
    ULBS_OVERVIEW_FILTER: 'ULBS_OVERVIEW_FILTER'
}

export default constants