var dat = {
    'swm.create': {
        numCols: 4,
        useTimestamp: true,
        objectName: 'vendorContracts',
        title: 'vendorcontracts.create.group.title.vendorContract',
        groups: [
          {
            name: 'VendorContractDetails',
            label: 'vendorcontracts.create.group.title.VendorContractDetails',
           // jsonPath: 'vendorContracts',
            fields: [
              {
                name: 'vendor',
                jsonPath: 'vendorContracts[0].vendor.vendorNo',
                label: 'vendorcontracts.create.vendorNo',
                type: 'windowsSingleValueList',
                isRequired: true,
                isDisabled: true,
                maxLength: 265,
                minLength: 1,
                patternErrorMsg: '',
                url: '/swm-services/vendors/_search?|$.vendors.*.vendorNo|$.vendors.*.name',
                 depedants:[
                {
                "jsonPath":"servicesOffered",
                "type":"autoFill",
                "pattern":'/swm-services/vendors/_search?&vendorNo={vendorContracts[0].vendor.vendorNo}|$..code|$..name',
                "autoFillFields":{
                "servicesOffered":"vendors[0].servicesOffered",
                },
                },
                      ],
              },
              {
                name: 'contractDate',
                jsonPath: 'contractDate',
                label: 'vendorcontracts.create.contractDate',
                pattern: '',
                type: 'datePicker',
                isRequired: true,
                isDisabled: false,
                defaultValue: '',
                patternErrorMsg: '',
              },
              {
                name: 'contractPeriodFrom',
                jsonPath: 'contractPeriodFrom',
                label: 'vendorcontracts.create.contractPeriodFrom',
                pattern: '',
                type: 'datePicker',
                isRequired: true,
                isDisabled: false,
                defaultValue: '',
                patternErrorMsg: '',
              },
              {
                name: 'contractPeriodTo',
                jsonPath: 'contractPeriodTo',
                label: 'vendorcontracts.create.contractPeriodTo',
                pattern: '',
                type: 'datePicker',
                isRequired: true,
                isDisabled: false,
                defaultValue: '',
                patternErrorMsg: '',
              },
              {
                name: 'securityDeposit',
                jsonPath: 'securityDeposit',
                label: 'vendorcontracts.create.securityDeposit',
                pattern: '',
                type: 'number',
                isRequired: true,
                isDisabled: false,
                defaultValue: '',
                patternErrorMsg: '',
              },
              {
                name: 'paymentAmount',
                jsonPath: 'paymentAmount',
                label: 'vendorcontracts.create.paymentAmount',
                pattern: '',
                type: 'number',
                isRequired: true,
                isDisabled: false,
                defaultValue: '',
                patternErrorMsg: '',
              },
              {
                name: 'paymentTerms',
                jsonPath: 'paymentTerms.label',
                label: 'vendorcontracts.search.result.paymentTerms',
                pattern: '',
                type: 'radio',
                styleObj: {
                  display: '-webkit-box',
                  width:'30%'
                },
                url: '',
                isRequired: false,
                isDisabled: false,
                requiredErrMsg: '',
                patternErrMsg: '',
                values: [
                  { label: 'Monthly', value: 'Monthly' },
                  { label: 'BiMonthly', value: 'BiMonthly' },
                  { label: 'Quarterly', value: 'Quarterly' },
                  { label: 'Yearly', value: 'Yearly' }
                ],
                defaultValue: 'Monthly',
              },
              {
                name: 'remarks',
                jsonPath: 'remarks',
                label: 'vendorcontracts.create.remarks',
                pattern: '.{15,300}$',
                type: 'textarea',
                fullWidth:true,
                isRequired: false,
                isDisabled: false,
                defaultValue: '',
                maxLength: 300,
                minLength: 15,
                patternErrMsg: 'swm.vendorcontracts.create.description.errormsg',
              },
            ],
          },
          {
            name: 'ServicesOffered',
            label: 'swm.create.servicesOffered',
            jsonPath: 'services[0]',
            fields: [
              {
                name: 'servicesOffered',
                label: 'swm.create.servicesOffered',
                jsonPath: 'servicesOffered',
                type: 'multiValueList',
                pattern: '',
                isRequired: true,
                isDisabled: false,
                maxLength: 128,
                url:'',
                minLength: 1,
                patternErrorMsg: '',
                mdms: {
                  "moduleName": "swm",
                  "masterName": "SwmProcess",
                  "filter": "",
                  "key": "$..code",
                  "value": "$..name",
                },
                hasATOAATransform:true,
                aATransformInfo:{
                  to:'servicesOffered',
                  key:'code'
                },
              },
              ],
            },
        ],
        // url: '/swm-services/vendorcontracts/_create',
         tenantIdRequired: true,
      }
};
export default dat;