var dat = {
'swm.update':{
    numCols: 3,
    useTimestamp: true,
    objectName: 'processing',
    title: 'swm.processingplant.create.title',
    groups:[
    {
        name :'LocationDetails',
        label: 'swm.processingplant.create.title.LocationDetails',
        jsonPath: "processing.location",
        fields:[
        {
            name : 'Ward',
            label : 'swm.processingplant.create.title.Ward',
            jsonPath: "processing.ward",
            type : 'singleValueList',
            isRequired: false,
            isDisabled: false,
            url :'',
            patternErrorMsg: '',
        },
        {
            name: 'Zone',
            label: 'swm.processingplant.create.Zone',
            jsonPath: "processing.zone",
            type: 'singleValueList',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            
          },
          {
            name: 'RoadStreet', 
            label: 'swm.processingplant.create.block',
            type: 'singleValueList',
            jsonPath: "processing.Road",
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            
          },
          {
            name: 'Colony',
            label: 'swm.processingplant.create.Colony',
            type: 'singleValueList',
            jsonPath: "processing.colony",
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
          
        ],  
    },
    {
        name: 'BankGuaranteeDetails',
        label: 'swm.processingplant.create.BankGuaranteeDetails',
        fields: [
          {
            name: 'mpcbAuthorisation',
            label: 'swm.processingplant.create.mpcbAuthorization',
            type: 'checkbox',
            jsonPath: "processing.mpcbAuthorizations",
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
            defaultValue: false,
            url: '',
          },
          {
            name: 'BankGuarantee',
            label: 'swm.processingplant.create.BankGuarantee',
            pattern: '',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
            jsonPath: "processing.bankGuarantee",
            url: '',
          },
          {
            name: 'BankName',
            jsonPath: 'processing.bankName',
            label: 'swm.processingplant.create.BankName',
            pattern: '',
            type: 'singleValueList',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url: '',
          },
          {
            name: 'BankGuaranteeFrom',
            jsonPath: 'processing.BankGuaranteeFrom',
            label: 'swm.processingplant.create.BankGuarantee',
            pattern: '',
            type: 'datePicker',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url: '',
          },
          {
            name: 'BankGuaranteeTo',
            jsonPath: 'processing.BankGuaranteeto',
            label: 'swm.processingplant.create.BankGuaranteeTo',
            pattern: '',
            type: 'datePicker',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url: '',
          },
          ],
      },
      {
      name: 'ProcessingSiteDeatils',
        label: 'swm.processingplant.create.title.ProcessingSiteDeatils',
        fields:[
        {
            name: 'ProcessingSiteName',
            label: 'swm.processingplant.create.ProcessingSiteName',
            type: 'text',
            jsonPath: "processing.ProcessingSiteName",
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
            url: '',
          },
          {
            name: 'ProcessingSiteArea',
            label: 'swm.processingplant.create.ProcessingSiteArea',
            type: 'text',
            jsonPath: "processing.ProcessingSiteArea",
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url: '',
          },
          {
            name: 'ProcessingSiteCapacity',
            label: 'swm.processingplant.create.ProcessingSiteCapacity',
            type: 'text',
            jsonPath: "processing.ProcessingSiteCapacity",
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url: '',
          },
          {
            name: 'ProcessingSiteAddress',
            label: 'swm.processingplant.create.ProcessingSiteAddress',
            type: 'textarea',
            jsonPath: "processing.ProcessingSiteAddress",
            isRequired: false,
            isDisabled: false,
            maxLength: 500,
            minLength: 10,
            fullWidth: true,
            patternErrorMsg: '',
            url: '',
          },
          ],
      },
      {
        name: 'GeoCordinates',
        label: 'swm.processingplant.create.title.GeoCordinates',
        fields: [
          {
            name: 'Latitude',
            label: 'swm.processingplant.create.Latitude',
            type: 'text',
            jsonPath: "processing.Latitude",
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url: '',
          },

          {
            name: 'Longitude',
            label: 'swm.processingplant.create.Longitude',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.Longitude",
            url: '',
          },
     
        ],

      },
      {
        name: 'WasteType',
        label: 'swm.processingplant.create.title.WasteType',
        fields: [
          {
            name: 'HouseHoldWaste',
            label: 'swm.processingplant.create.HouseHoldWaste',
            type: 'checkbox',
            jsonPath: "processing.HouseHoldWaste",
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url: '',
          },

          {
            name: 'CommericalWaste',
            label: 'swm.processingplant.create.CommericalWaste',
            pattern: '',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.CommericalWaste",
            url: '',
          },
          {
            name: 'StreetSheepingWaste',
            label: 'swm.processingplant.create.StreetSheepingWaste',
            pattern: '',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.StreetSheepingWaste",
            url: '',
          },
          {
            name: 'MedicineWaste',
            label: 'swm.processingplant.create.MedicineWaste',
            pattern: '',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.MedicineWaste",
            url: '',
          },
          {
            name: 'MarketWaste',
            label: 'swm.processingplant.create.MarketWaste',
            pattern: '',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.MarketWaste",
            url: '',
          },
          {
            name: 'RestaurantWaste',
            label: 'swm.processingplant.create.RestaurantWaste',
            pattern: '',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.RestaurantWaste",
            url: '',
          },
          {
            name: 'InstitutionWaste',
            label: 'swm.processingplant.create.InstitutionWaste',
            pattern: '',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.InstitutionWaste",
            url: '',
          },
          {
            name: 'SlaughterHouseWaste',
            label: 'swm.processingplant.create.SlaughterHouseWaste',
            pattern: '',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.SlaughterHouseWaste",
            url: '',
          },
     
        ],

      },

    ], 
},

'swm.create': { //ghg
    numCols: 3,
    useTimestamp: true,
    objectName: 'processing',
    title: 'swm.processingplant.create.title',
    groups:[
    {
        name :'LocationDetails',
        label: 'swm.processingplant.create.title.LocationDetails',
        jsonPath: "processing.location",
        fields:[
        {
            name : 'Ward',
            label : 'swm.processingplant.create.title.Ward',
            jsonPath: "processing.ward",
            type : 'singleValueList',
            isRequired: false,
            isDisabled: false,
            url :'',
            patternErrorMsg: '',
        },
        {
            name: 'Zone',
            label: 'swm.processingplant.create.Zone',
            jsonPath: "processing.zone",
            type: 'singleValueList',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            
          },
          {
            name: 'RoadStreet', 
            label: 'swm.processingplant.create.block',
            type: 'singleValueList',
            jsonPath: "processing.Road",
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            
          },
          {
            name: 'Colony',
            label: 'swm.processingplant.create.Colony',
            type: 'singleValueList',
            jsonPath: "processing.colony",
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
          
        ],  
    },
    {
        name: 'BankGuaranteeDetails',
        label: 'swm.processingplant.create.BankGuaranteeDetails',
        fields: [
          {
            name: 'mpcbAuthorisation',
            label: 'swm.processingplant.create.mpcbAuthorization',
            type: 'checkbox',
            jsonPath: "processing.mpcbAuthorizations",
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
            defaultValue: false,
            url: '',
          },
          {
            name: 'BankGuarantee',
            label: 'swm.processingplant.create.BankGuarantee',
            pattern: '',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
            jsonPath: "processing.bankGuarantee",
            url: '',
          },
          {
            name: 'BankName',
            jsonPath: 'processing.bankName',
            label: 'swm.processingplant.create.BankName',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            fullWidth: true,
            patternErrorMsg: '',
            url: '',
          },
          {
            name: 'BankGuaranteeFrom',
            jsonPath: 'processing.BankGuaranteeFrom',
            label: 'swm.processingplant.create.BankGuarantee',
            pattern: '',
            type: 'datePicker',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url: '',
          },
          {
            name: 'BankGuaranteeTo',
            jsonPath: 'processing.BankGuaranteeto',
            label: 'swm.processingplant.create.BankGuaranteeTo',
            pattern: '',
            type: 'datePicker',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url: '',
          },
          ],
      },
      {
      name: 'ProcessingSiteDeatils',
        label: 'swm.processingplant.create.title.ProcessingSiteDeatils',
        fields:[
        {
            name: 'ProcessingSiteName',
            label: 'swm.processingplant.create.ProcessingSiteName',
            type: 'text',
            jsonPath: "processing.ProcessingSiteName",
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
            url: '',
          },
          {
            name: 'ProcessingSiteArea',
            label: 'swm.processingplant.create.ProcessingSiteArea',
            type: 'number',
            pattern: '^\\b[0-9]\\b|\\b([1-4][0-9])\\b|\\b50\\b$',
            jsonPath: "processing.ProcessingSiteArea",
            isRequired: false,
            isDisabled: false,
            patternErrMsg: 'Invalid Value',
            url: '',
          },
          {
            name: 'ProcessingSiteCapacity',
            label: 'swm.processingplant.create.ProcessingSiteCapacity',
            pattern: '^([1-9][0-9]{0,3}|10000|0|[1-4][0-9]{0,4}|50000)$',
            type: 'text',
            jsonPath: "processing.ProcessingSiteCapacity",
            maxLength: '5',
            minLength: '1',
            isRequired: false,
            isDisabled: false,
            patternErrMsg: 'Invalid Value',
            url: '',
          },
          {
            name: 'ProcessingSiteAddress',
            label: 'swm.processingplant.create.ProcessingSiteAddress',
            type: 'textarea',
            jsonPath: "processing.ProcessingSiteAddress",
            isRequired: false,
            isDisabled: false,
            maxLength: 500,
            minLength: 10,
            fullWidth: true,
            patternErrorMsg: '',
            url: '',
          },
          ],
      },
      {
        name: 'GeoCordinates',
        label: 'swm.processingplant.create.title.GeoCordinates',
        fields: [
          {
            name: 'Latitude',
            label: 'swm.processingplant.create.Latitude',
            type: 'text',
            jsonPath: "processing.Latitude",
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url: '',
          },

          {
            name: 'Longitude',
            label: 'swm.processingplant.create.Longitude',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.Longitude",
            url: '',
          },
     
        ],

      },
      {
        name: 'WasteType',
        label: 'swm.processingplant.create.title.WasteType',
        fields: [
          {
            name: 'HouseHoldWaste',
            label: 'swm.processingplant.create.HouseHoldWaste',
            type: 'checkbox',
            jsonPath: "processing.HouseHoldWaste",
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url: '',
          },

          {
            name: 'CommericalWaste',
            label: 'swm.processingplant.create.CommericalWaste',
            pattern: '',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.CommericalWaste",
            url: '',
          },
          {
            name: 'StreetSheepingWaste',
            label: 'swm.processingplant.create.StreetSheepingWaste',
            pattern: '',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.StreetSheepingWaste",
            url: '',
          },
          {
            name: 'MedicineWaste',
            label: 'swm.processingplant.create.MedicineWaste',
            pattern: '',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.MedicineWaste",
            url: '',
          },
          {
            name: 'MarketWaste',
            label: 'swm.processingplant.create.MarketWaste',
            pattern: '',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.MarketWaste",
            url: '',
          },
          {
            name: 'RestaurantWaste',
            label: 'swm.processingplant.create.RestaurantWaste',
            pattern: '',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.RestaurantWaste",
            url: '',
          },
          {
            name: 'InstitutionWaste',
            label: 'swm.processingplant.create.InstitutionWaste',
            pattern: '',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.InstitutionWaste",
            url: '',
          },
          {
            name: 'SlaughterHouseWaste',
            label: 'swm.processingplant.create.SlaughterHouseWaste',
            pattern: '',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.SlaughterHouseWaste",
            url: '',
          },
     
        ],

      },

    ], 
},
'swm.search': {
    numCols: 4,
    useTimestamp: true,
    objectName: 'processing',

    groups: [
      {
        name: 'processing',
        label: 'swm.processingplant.search.title',
        fields: [
          {
            name: 'area',
            jsonPath: 'name',
            label: 'swm.processingplant.create.area',
            pattern: '',
            type: 'text',
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
            url: ''
          },
          {
            name: 'capacity',
            jsonPath: 'name',
            label: 'swm.processingplant.create.capacity',
            pattern: '',
            type: 'text',
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
            url: ''
          },
          {
            name: 'address',
            jsonPath: 'name',
            label: 'swm.processingplant.create.address',
            pattern: '',
            type: 'text',
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
            url: ''
          },
          {
            name: 'name',
            jsonPath: 'name',
            label: 'swm.processingplant.create.name',
            pattern: '',
            type: 'text',
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
            url: ''
          },
          
        ],
      },
    ],
    result: {
      header: [
        {
          label: 'swm.processingplant.create.area',
        },
        {
          label: 'swm.processingplant.create.capacity',
        },
        {
            label : 'swm.processingplant.create.address',
        },
        {
            label : 'swm.processingplant.create.name',
        },
      ],
      values: [
       
      ],
      resultPath: 'MdmsRes.swm.processing',
      rowClickUrlUpdate: '/update/swm/processingplant/{code}',
      rowClickUrlView: '/view/swm/processingplant/{code}',
      isMasterScreen: true
      
    },
  },

'swm.view': { 
    numCols: 3,
    useTimestamp: true,
    objectName: 'processing',
    title: 'swm.processingplant.create.title',
    groups:[
    {
        name :'LocationDetails',
        label: 'swm.processingplant.create.title.LocationDetails',
        jsonPath: "processing.location",
        fields:[
        {
            name : 'Ward',
            label : 'swm.processingplant.create.title.Ward',
            jsonPath: "processing.ward",
            type : 'label',
            isRequired: false,
            isDisabled: false,
            url :'',
            patternErrorMsg: '',
        },
        {
            name: 'Zone',
            label: 'swm.processingplant.create.Zone',
            jsonPath: "processing.zone",
            type: 'label',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            
          },
          {
            name: 'RoadStreet', 
            label: 'swm.processingplant.create.block',
            type: 'label',
            jsonPath: "processing.Road",
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            
          },
          {
            name: 'Colony',
            label: 'swm.processingplant.create.Colony',
            type: 'label',
            jsonPath: "processing.colony",
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
          },
          
        ],  
    },
    {
        name: 'BankGuaranteeDetails',
        label: 'swm.processingplant.create.BankGuaranteeDetails',
        fields: [
          {
            name: 'mpcbAuthorisation',
            label: 'swm.processingplant.create.mpcbAuthorization',
            type: 'label',
            jsonPath: "processing.mpcbAuthorizations",
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
            defaultValue: false,
            url: '',
          },
          {
            name: 'BankGuarantee',
            label: 'swm.processingplant.create.BankGuarantee',
            pattern: '',
            type: 'label',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
            jsonPath: "processing.bankGuarantee",
            url: '',
          },
          {
            name: 'BankName',
            jsonPath: 'processing.bankName',
            label: 'swm.processingplant.create.BankName',
            pattern: '',
            type: 'label',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url: '',
          },
          {
            name: 'BankGuaranteeFrom',
            jsonPath: 'processing.BankGuaranteeFrom',
            label: 'swm.processingplant.create.BankGuarantee',
            pattern: '',
            type: 'label',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url: '',
          },
          {
            name: 'BankGuaranteeTo',
            jsonPath: 'processing.BankGuaranteeto',
            label: 'swm.processingplant.create.BankGuaranteeTo',
            pattern: '',
            type: 'label',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url: '',
          },
          ],
      },
      {
      name: 'ProcessingSiteDeatils',
        label: 'swm.processingplant.create.title.ProcessingSiteDeatils',
        fields:[
        {
            name: 'ProcessingSiteName',
            label: 'swm.processingplant.create.ProcessingSiteName',
            type: 'label',
            jsonPath: "processing.ProcessingSiteName",
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
            url: '',
          },
          {
            name: 'ProcessingSiteArea',
            label: 'swm.processingplant.create.ProcessingSiteArea',
            type: 'label',
            jsonPath: "processing.ProcessingSiteArea",
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url: '',
          },
          {
            name: 'ProcessingSiteCapacity',
            label: 'swm.processingplant.create.ProcessingSiteCapacity',
            type: 'label',
            jsonPath: "processing.ProcessingSiteCapacity",
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url: '',
          },
          {
            name: 'ProcessingSiteAddress',
            label: 'swm.processingplant.create.ProcessingSiteAddress',
            type: 'label',
            jsonPath: "processing.ProcessingSiteAddress",
            isRequired: false,
            isDisabled: false,
            maxLength: 500,
            minLength: 10,
            fullWidth: true,
            patternErrorMsg: '',
            url: '',
          },
          ],
      },
      {
        name: 'GeoCordinates',
        label: 'swm.processingplant.create.title.GeoCordinates',
        fields: [
          {
            name: 'Latitude',
            label: 'swm.processingplant.create.Latitude',
            type: 'label',
            jsonPath: "processing.Latitude",
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url: '',
          },

          {
            name: 'Longitude',
            label: 'swm.processingplant.create.Longitude',
            pattern: '',
            type: 'label',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.Longitude",
            url: '',
          },
     
        ],

      },
      {
        name: 'WasteType',
        label: 'swm.processingplant.create.title.WasteType',
        fields: [
          {
            name: 'HouseHoldWaste',
            label: 'swm.processingplant.create.HouseHoldWaste',
            type: 'label',
            jsonPath: "processing.HouseHoldWaste",
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            url: '',
          },

          {
            name: 'CommericalWaste',
            label: 'swm.processingplant.create.CommericalWaste',
            pattern: '',
            type: 'label',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.CommericalWaste",
            url: '',
          },
          {
            name: 'StreetSheepingWaste',
            label: 'swm.processingplant.create.StreetSheepingWaste',
            pattern: '',
            type: 'label',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.StreetSheepingWaste",
            url: '',
          },
          {
            name: 'MedicineWaste',
            label: 'swm.processingplant.create.MedicineWaste',
            pattern: '',
            type: 'label',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.MedicineWaste",
            url: '',
          },
          {
            name: 'MarketWaste',
            label: 'swm.processingplant.create.MarketWaste',
            pattern: '',
            type: 'label',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.MarketWaste",
            url: '',
          },
          {
            name: 'RestaurantWaste',
            label: 'swm.processingplant.create.RestaurantWaste',
            pattern: '',
            type: 'label',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.RestaurantWaste",
            url: '',
          },
          {
            name: 'InstitutionWaste',
            label: 'swm.processingplant.create.InstitutionWaste',
            pattern: '',
            type: 'label',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.InstitutionWaste",
            url: '',
          },
          {
            name: 'SlaughterHouseWaste',
            label: 'swm.processingplant.create.SlaughterHouseWaste',
            pattern: '',
            type: 'label',
            isRequired: false,
            isDisabled: false,
            patternErrorMsg: '',
            jsonPath: "processing.SlaughterHouseWaste",
            url: '',
          },
     
        ],

      },
    ], 
 

},

}

    
export default dat;
  