var dat = {
  'swm.search': {
    numCols: 3,
    useTimestamp: true,
    objectName: '',
    url: '/swm-services/vendors/_search',
    title:'swm.search.page.title.vendors',
    groups: [
      {
        name: 'search',
        label: 'swm.search.vendor.title',
        fields: [
          {
            name: 'name',
            jsonPath: 'name',
            label: 'swm.create.supplier.name',
            pattern: '',
            type: 'autoCompelete',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            maxLength: 256,
            minLength: 1,
            patternErrorMsg: 'swm.create.field.message.name',
            url: 'swm-services/vendors/_search?|$..vendors.*.name|$..vendors.*.name'
          },
          {
            name: 'vendorNo',
            jsonPath: 'vendorNo',
            label: 'swm.create.vendorNo',
            pattern: '',
            type: 'autoCompelete',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            maxLength: 128,
            minLength: 1,
            patternErrorMsg: 'swm.create.field.message.vendorNo',
            url: 'swm-services/vendors/_search?|$..vendors.*.vendorNo|$..vendors.*.vendorNo'
          },
          {
            name: 'registrationNo',
            jsonPath: 'registrationNo',
            label: 'swm.create.vendorregistrationNo',
            pattern: '',
            type: 'autoCompelete',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            maxLength: 256,
            minLength: 1,
            patternErrorMsg: 'swm.create.field.message.registrationNo',
            url: 'swm-services/vendors/_search?|$..vendors.*.registrationNo|$..vendors.*.registrationNo'
          }
        ],
      },
    ],
    result: {
      header: [
        {label: 'swm.create.supplier.name'},
        {label: 'swm.create.vendorNo'},
        {label: 'swm.create.vendorregistrationNoHeader'}
      ],
      values: ['name', 'vendorNo', 'registrationNo'/*, 'servicesOffered.name'*/],
      resultPath: 'vendors',
      rowClickUrlUpdate: '/update/swm/vendors/{vendorNo}',
      rowClickUrlView: '/view/swm/vendors/{vendorNo}',
    },
  },
  'swm.create': {
    numCols: 3,
    useTimestamp: true,
    objectName: 'vendors',
    idJsonPath: 'vendors[0].vendorNo',
    title: 'swm.create.group.title.Vendors',
    groups: [
      {
        name: 'VendorDetails',
        label: 'swm.create.group.title.VendorDetails',
        fields: [
          {
            name: 'name',
            jsonPath: 'vendors[0].name',
            label: 'swm.create.supplier.name',
            pattern: '',
            type: 'text',
            isRequired: true,
            isDisabled: false,
            //defaultValue: '',
            maxLength: 256,
            minLength: 1,
            patternErrorMsg: '',
          },
          {
            name: 'mobileNo',
            jsonPath: 'vendors[0].supplier.mobileNo',
            label: 'swm.create.supplier.mobileNo',
            pattern: '^([a-zA-Z0-9_-\\s]){10}$',
            type: 'mobileNumber',
            isRequired: false,
            isDisabled: false,
            // defaultValue: '',
            maxLength: 10,
            minLength: 10,
            patternErrMsg: 'The Phone number structure is as follows: 999XXXX999.',
          },
          {
            name: 'registrationNo',
            jsonPath: 'vendors[0].registrationNo',
            label: 'swm.create.vendorregistrationNo',
            pattern: '',
            type: 'text',
            isRequired: true,
            isDisabled: false,
            // defaultValue: '',
            maxLength: 256,
            minLength: 1,
            patternErrorMsg: '',
          },
          {
            name: 'contactNo',
            jsonPath: 'vendors[0].supplier.contactNo',
            label: 'swm.create.supplier.contactNo',
            pattern: '^([a-zA-Z0-9_-\\s]){10}$',
            type: 'mobileNumber',
            isRequired: true,
            isDisabled: false,
            // defaultValue: '',
            maxLength: 10,
            minLength: 10,
            patternErrMsg: 'The contact number structure is as follows: 999XXXX999.',
          },
          {
            name: 'email',
            jsonPath: 'vendors[0].supplier.email',
            label: 'swm.create.supplier.email',
            pattern: '',
            type: 'email',
            isRequired: true,
            isDisabled: false,
            // defaultValue: '',
            maxLength: 100,
            minLength: 6,
            patternErrMsg: 'pattern.error.message.email',
          },
          {
            name: 'faxNumber',
            jsonPath: 'vendors[0].supplier.faxNumber',
            label: 'swm.create.supplier.faxNumber',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            // defaultValue: '',
            maxLength: 10,
            minLength: 10,
            patternErrorMsg: '',
          },
          {
            name: 'tinNumber',
            jsonPath: 'vendors[0].supplier.tinNumber',
            label: 'swm.create.supplier.tinNumber',
            pattern: '^([0-9]){11}$',
            type: 'text',
            isRequired: true,
            isDisabled: false,
            // defaultValue: '',
          maxLength: 11,
            minLength: 11,
            patternErrMsg: 'pattern.error.message.tinNumber',
          },
          {
            name: 'address',
            jsonPath: 'vendors[0].supplier.address',
            label: 'swm.create.supplier.address',
            pattern: '.{15,300}$',
            type: 'textarea',
            isRequired: true,
            isDisabled: false,
            maxLength: 300,
            minLength: 15,
            patternErrMsg: 'Address shall be of minimum 15 And maximum 300 Characters',
          },
          {
            name: 'gst',
            jsonPath: 'vendors[0].supplier.gst',
            label: 'swm.create.supplier.gst',
            pattern: '',
            type: 'text',
            isRequired: true,
            isDisabled: false,
            maxLength: 256,
            minLength: 1,
            patternErrMsg: 'pattern.error.message.gstNumber'
          },
        ],
      },
      {
        name: 'agreementCopyDetails',
        label: 'swm.vendors.create.group.title.agreementCopyDetails',
        fields: [
          {
            name: 'uploadAgreementCopy',
            jsonPath: 'vendors[0].agreementDocument.fileStoreId',
            label: 'swm.vendor.create.agreement.details',
            type: 'singleFileUpload',
            pathToArray: 'documentTypes',
            displayNameJsonPath: 'name',
            isRequired: false,
            isDisabled: false,
            maxLength: 256,
            minLength: 1,
            patternErrorMsg: '',
          },
        ],
      },

      {
        name: 'LocationDetails',
        multiple:true,
        label: 'swm.collectionpoints.create.group.title.LocationDetails',
        jsonPath: "vendors[0].servicedLocations",
         "fields": [
          {
            "type": "boundary",
            "label": "",
            "hierarchyType": "REVENUE",
            "jsonPath": "vendors[0].servicedLocations[0].code",
            "isRequired": true,
            "patternErrorMsg": "",
            "multiple": true,
            "fullWidth": true,
          }
        ]
      },
      {
        name: 'ServicesOffered',
        label: 'swm.create.servicesOffered',
        // children: [serviceProvided],
        fields: [
          {
            name: 'ServicesOffered',
            label: 'swm.create.servicesOffered',
            jsonPath: 'vendors[0].servicesOffered',
            type: 'multiValueList',
            pattern: '',
            isRequired: true,
            isDisabled: false,
            maxLength: 128,
            url:'',
            minLength: 1,
            patternErrorMsg: '',
            mdms: {
              "moduleName": "swm",
              "masterName": "SwmProcess",
              "filter": "",
              "key": "$..code",
              "value": "$..name",
            },
            hasATOAATransform:true,
            aATransformInfo:{
              to:'vendors[0].servicesOffered',
              key:'code'
            },
            reqNotReqFields: [{
              ifValue: 'Process 6',
              require: [{
                     name: 'details',
                     jsonPath:'vendors[0].details',
                     isGroup: false,
                     isField: true,
                   
                    }
                   ],
                   notrequire: [ ]
            }],
          },
          {
            name: 'details',
            jsonPath: 'vendors[0].details',
            label: 'swm.create.details',
            pattern: '',
            type: 'textarea',
            isRequired: false,
            isDisabled: false,
            maxLength: 500,
            minLength: 10,
            patternErrorMsg: 'length must be between 10 and 500',
          }
        ],
      },
    ],
    url: '/swm-services/vendors/_create',
    tenantIdRequired: true,
  },
  'swm.view': {
    numCols: 4,
    useTimestamp: true,
    objectName: 'vendors',
    groups: [
      {
        name: 'vendors',
        label: 'swm.create.group.title.vendors',
        fields: [
          {
            name: 'vendorNo',
            jsonPath: 'vendors[0].vendorNo',
            label: 'swm.create.vendorNo',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            maxLength: 128,
            minLength: 1,
            patternErrorMsg: '',
          },
        ],
      },
      {
        name: 'VendorDetails',
        label: 'swm.create.group.title.VendorDetails',
        fields: [
          {
            name: 'name',
            jsonPath: 'vendors[0].name',
            label: 'swm.create.supplier.name',
            pattern: '',
            type: 'text',
            isRequired: true,
            isDisabled: false,
            defaultValue: '',
            maxLength: 256,
            minLength: 1,
            patternErrorMsg: '',
          },
          {
            name: 'mobileNo',
            jsonPath: 'vendors[0].supplier.mobileNo',
            label: 'swm.create.supplier.mobileNo',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            maxLength: 10,
            minLength: 10,
            patternErrorMsg: '',
          },
          {
            name: 'registrationNo',
            jsonPath: 'vendors[0].registrationNo',
            label: 'swm.create.vendorregistrationNo',
            pattern: '',
            type: 'text',
            isRequired: true,
            isDisabled: false,
            defaultValue: '',
            maxLength: 256,
            minLength: 1,
            patternErrorMsg: '',
          },
          {
            name: 'contactNo',
            jsonPath: 'vendors[0].supplier.contactNo',
            label: 'swm.create.supplier.contactNo',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            maxLength: 10,
            minLength: 10,
            patternErrorMsg: '',
          },
          {
            name: 'email',
            jsonPath: 'vendors[0].supplier.email',
            label: 'swm.create.supplier.email',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            maxLength: 100,
            minLength: 6,
            patternErrorMsg: '',
          },
          {
            name: 'faxNumber',
            jsonPath: 'vendors[0].supplier.faxNumber',
            label: 'swm.create.supplier.faxNumber',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            maxLength: 10,
            minLength: 10,
            patternErrorMsg: '',
          },
          {
            name: 'tinNumber',
            jsonPath: 'vendors[0].supplier.tinNumber',
            label: 'swm.create.supplier.tinNumber',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            maxLength: 256,
            minLength: 1,
            patternErrorMsg: '',
          },
          {
            name: 'address',
            jsonPath: 'vendors[0].supplier.address',
            label: 'swm.create.supplier.address',
            pattern: '.{15,300}$',
            type: 'textarea',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            maxLength: 300,
            minLength: 15,
            patternErrorMsg: '',
          },
          {
            name: 'gst',
            jsonPath: 'vendors[0].supplier.gst',
            label: 'swm.create.supplier.gst',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            maxLength: 256,
            minLength: 1,
            patternErrorMsg: '',
          },
        ],
      },
      {
        name: 'agreementCopyDetails',
        label: 'swm.vendors.create.group.title.agreementCopyDetails',
        fields: [
          {
            name: 'uploadAgreementCopy',
            jsonPath: 'vendors[0].agreementDocument.fileStoreId',
            label: 'swm.vendor.create.downloadagreement.details',
            type: 'singleFileUpload',
            pathToArray: 'documentTypes',
            displayNameJsonPath: 'name',
            isRequired: false,
            isDisabled: false,
            maxLength: 256,
            minLength: 1,
            patternErrorMsg: '',
            readonly:true
          },
        ],
      },
      {
        name: 'LocationDetails',
        multiple:true,
        label: 'swm.collectionpoints.create.group.title.LocationDetails',
        jsonPath: "vendors[0].servicedLocations",
         "fields": [
          {
            "type": "boundary",
            "label": "",
            "hierarchyType": "REVENUE",
            "jsonPath": "vendors[0].servicedLocations[0].code",
            "isRequired": false,
            "patternErrorMsg": "",
            "multiple": true,
            "fullWidth": true,
          }
        ]
      },
      {
        name: 'ServicesOffered',
        label: 'swm.create.group.title.ServicesOffered',
        fields: [
          {
            name: 'ServicesOffered',
            label: 'swm.create.servicesOffered',
            jsonPath: 'vendors[0].servicesOffered',
            type: 'multiValueList',
            pattern: '',
            isRequired: true,
            isDisabled: false,
            maxLength: 128,
            url: '/egov-mdms-service/v1/_get?&moduleName=swm&masterName=SwmProcess|$..code|$..name',
            minLength: 1,
            patternErrorMsg: '',
            hasATOAATransform:true,
            aATransformInfo:{
              to:'vendors[0].servicesOffered',
              key:'code'
            }
          },
          {
            name: 'details',
            jsonPath: 'vendors[0].details',
            label: 'swm.create.details',
            pattern: '',
            type: 'textarea',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            maxLength: 500,
            minLength: 10,
            patternErrorMsg: '',
          },
        ],
      },
    ],
    tenantIdRequired: true,
    url: '/swm-services/vendors/_search?vendorNo={vendorNo}',
  },
  'swm.update': {
    numCols: 3,
    useTimestamp: true,
    idJsonPath: 'vendors[0].vendorNo',
    objectName: 'vendors',
    title: 'swm.create.group.title.Vendors',
    groups: [
      {
        name: 'VendorDetails',
        label: 'swm.create.group.title.VendorDetails',
        fields: [
          {
            name: 'name',
            jsonPath: 'vendors[0].name',
            label: 'swm.create.supplier.name',
            pattern: '',
            type: 'text',
            isRequired: true,
            isDisabled: false,
            maxLength: 256,
            minLength: 1,
            patternErrMsg: '',
          },
          {
            name: 'mobileNo',
            jsonPath: 'vendors[0].supplier.mobileNo',
            label: 'swm.create.supplier.mobileNo',
            pattern: '^([a-zA-Z0-9_-\\s]){10}$',
            type: 'mobileNumber',
            isRequired: false,
            isDisabled: false,
            maxLength: 10,
            minLength: 10,
            patternErrMsg:'The Phone number structure is as follows: 999XXXX999 ',
          },
          {
            name: 'registrationNo',
            jsonPath: 'vendors[0].registrationNo',
            label: 'swm.create.vendorregistrationNo',
            pattern: '',
            type: 'text',
            isRequired: true,
            isDisabled: false,
            maxLength: 256,
            minLength: 1,
            patternErrorMsg: '',
          },
          {
            name: 'contactNo',
            jsonPath: 'vendors[0].supplier.contactNo',
            label: 'swm.create.supplier.contactNo',
            pattern: '^([a-zA-Z0-9_-\\s]){10}$',
            type: 'mobileNumber',
            isRequired: true,
            isDisabled: false,
            maxLength: 10,
            minLength: 10,
            patternErrMsg: 'The Contact number structure is as follows: 999XXXX999.',
          },
          {
            name: 'email',
            jsonPath: 'vendors[0].supplier.email',
            label: 'swm.create.supplier.email',
            pattern: '',
            type: 'email',
            isRequired: true,
            isDisabled: false,
            maxLength: 100,
            minLength: 6,
            patternErrMsg: 'pattern.error.message.email',
          },
          {
            name: 'faxNumber',
            jsonPath: 'vendors[0].supplier.faxNumber',
            label: 'swm.create.supplier.faxNumber',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            maxLength: 10,
            minLength: 10,
            patternErrorMsg: '',
          },
          {
            name: 'tinNumber',
            jsonPath: 'vendors[0].supplier.tinNumber',
            label: 'swm.create.supplier.tinNumber',
            pattern: '^([0-9]){11}$',
            type: 'text',
            isRequired: true,
            isDisabled: false,
            // defaultValue: '',
            maxLength: 11,
            minLength: 11,
            patternErrMsg: 'pattern.error.message.tinNumber',
          },
          {
            name: 'address',
            jsonPath: 'vendors[0].supplier.address',
            label: 'swm.create.supplier.address',
            pattern: '.{15,300}$',
            type: 'textarea',
            isRequired: true,
            isDisabled: false,
            maxLength: 300,
            minLength: 15,
            patternErrMsg: 'Address shall be of minimum 15 And maximum 300 Characters',
          },
          {
            name: 'gst',
            jsonPath: 'vendors[0].supplier.gst',
            label: 'swm.create.supplier.gst',
            pattern: '',
            type: 'text',
            isRequired: true,
            isDisabled: false,
            maxLength: 256,
            minLength: 1,
            patternErrorMsg: '',
          },
        ],
      },
      {
        name: 'agreementCopyDetails',
        label: 'swm.vendors.create.group.title.agreementCopyDetails',
        fields: [
          {
            name: 'uploadAgreementCopy',
            jsonPath: 'vendors[0].agreementDocument.fileStoreId',
            label: 'swm.vendor.create.downloadagreement.details',
            type: 'singleFileUpload',
            pathToArray: 'documentTypes',
            readonly : true,
            optionForNew:true,
            displayNameJsonPath: 'name',
            isRequired: false,
            isDisabled: false,
            maxLength: 256,
            minLength: 1,
            patternErrorMsg: '',
          },
        ],
      },

      {
        name: 'LocationDetails',
        multiple:true,
        label: 'swm.collectionpoints.create.group.title.LocationDetails',
        jsonPath: "vendors[0].servicedLocations",
         "fields": [
          {
            "type": "boundary",
            "label": "",
            "hierarchyType": "REVENUE",
            "jsonPath": "vendors[0].servicedLocations[0].code",
            "isRequired": true,
            "patternErrorMsg": "",
            "multiple": true,
            "fullWidth": true,
          }
        ]
      },
      {
        name: 'ServicesOffered',
        label: 'swm.create.servicesOffered',
        // children: [serviceProvided],
        fields: [
          {
            name: 'ServicesOffered',
            label: 'swm.create.servicesOffered',
            jsonPath: 'vendors[0].servicesOffered',
            type: 'multiValueList',
            pattern: '',
            isRequired: true,
            isDisabled: false,
            maxLength: 128,
            url:'',
            minLength: 1,
            patternErrorMsg: '',
            mdms: {
              "moduleName": "swm",
              "masterName": "SwmProcess",
              "filter": "",
              "key": "$..code",
              "value": "$..name",
            },
            hasATOAATransform:true,
            aATransformInfo:{
              to:'vendors[0].servicesOffered',
              key:'code'
            },
            reqNotReqFields: [{
              ifValue: 'Process 6',
              require: [{
                     name: 'details',
                     jsonPath:'vendors[0].details',
                     isGroup: false,
                     isField: true,
                   
                    }
                   ],
                   notrequire: [ ]
            }]
          },

          {
            name: 'details',
            jsonPath: 'vendors[0].details',
            label: 'swm.create.details',
            pattern: '',
            type: 'textarea',
            isRequired: false,
            isDisabled: false,
            maxLength: 500,
            minLength: 10,
            patternErrorMsg: 'length must be between 10 and 500',
          }
        ],
      },
    ],
    url: '/swm-services/vendors/_update',
    tenantIdRequired: true,
    searchUrl: '/swm-services/vendors/_search?vendorNo={vendorNo}',
  },
};
export default dat;