var dat = {
    'lcms.search': {
      numCols: 3,
      useTimestamp: true,
      objectName: 'court',
      url: '/egov-mdms-service/v1/_search',
      groups: [
        {
          name:'courtDetails',
          label: 'lcms.create.group.title.courtDetails',
          fields: [
            {
              name: 'courtName',
              jsonPath: 'name',
              label: 'MdmsMetadata.masterData.lcms.Court.name',
              pattern: '',
              type: 'text',
              isRequired: false,
              isDisabled: false,
              defaultValue: '',
              maxLength: 100,
              minLength: 1,
              //url: '/egov-mdms-service/v1/_get?&moduleName=swm&masterName=ShiftType|$..ShiftType.*.code|$..ShiftType.*.name',
            },
            {
              name: 'courtCode',
              jsonPath: 'code',
              label: 'MdmsMetadata.masterData.lcms.Court.code',
              pattern: '',
              type: 'text',
              isRequired: false,
              isDisabled: false,
              defaultValue: '',
              maxLength: 100,
              minLength: 1,
              patternErrorMsg: '',
              /*url: "/egov-mdms-service/v1/_get?&moduleName=common-masters&masterName=Department|$..code|$..name",
              hasIdConverion: true,*/
            },
          ]
        },
      ],
      result: {
        header: [
          {
            label: 'MdmsMetadata.masterData.lcms.Court.name',
          },
          {
            label: 'MdmsMetadata.masterData.lcms.Court.code',
          },
          {
            label: 'MdmsMetadata.masterData.lcms.Court.addressLine1',
          },
          {
            label: 'MdmsMetadata.masterData.lcms.Court.addressLine2',
          },
          {
            label: 'MdmsMetadata.masterData.lcms.Court.city',
          },
          {
            label: 'MdmsMetadata.masterData.lcms.Court.pincode',
          },
          {
            label: 'MdmsMetadata.masterData.lcms.Court.active',
          },
        ],
        values: [
          'name',
          'code',
          'address.addressLine1',
          'address.addressLine2',
          'address.city',
          'address.pincode',
          'active',
        ],
        resultPath: 'MdmsRes.lcms.court',
        rowClickUrlUpdate: '/update/lcms/court/{code}',
        rowClickUrlView: '/view/lcms/court/{code}',
        isMasterScreen: true
      },
    },
    'lcms.create': {
      numCols: 3,
      useTimestamp: true,
      objectName: 'MasterMetaData',
      idJsonPath: 'MdmsRes.lcms.court[0].code',
      groups: [
        {
          name:'courtDetails',
          label: 'lcms.create.group.title.courtDetails',
          fields: [
            {
              name: 'courtName',
              jsonPath: 'MasterMetaData.masterData[0].name',
              label: 'MdmsMetadata.masterData.lcms.Court.name',
              pattern: '',
              type: 'text',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: 100,
              minLength: 1,
              //url: '/egov-mdms-service/v1/_get?&moduleName=swm&masterName=ShiftType|$..ShiftType.*.code|$..ShiftType.*.name',
            },
            {
              name: 'courtCode',
              jsonPath: 'MasterMetaData.masterData[0].code',
              label: 'MdmsMetadata.masterData.lcms.Court.code',
              pattern: '',
              type: 'text',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: 128,
              minLength: 1,
              patternErrorMsg: '',
              /*url: "/egov-mdms-service/v1/_get?&moduleName=common-masters&masterName=Department|$..code|$..name",
              hasIdConverion: true,*/
            },
           {
              name: 'address1',
              jsonPath: 'MasterMetaData.masterData[0].address.addressLine1',
              label: 'MdmsMetadata.masterData.lcms.Court.addressLine1',
              pattern: '',
              type: 'text',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: '',
              minLength: 1,
              patternErrorMsg: '',
              //url: '/hr-masters/designations/_search?tenantId=default|$..id|$..name',
            },
            {
              name: 'address2',
              jsonPath: 'MasterMetaData.masterData[0].address.addressLine2',
              label: 'MdmsMetadata.masterData.lcms.Court.addressLine2',
              pattern: '',
              type: 'text',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: '',
              minLength: 1,
              patternErrorMsg: '',
            },
            {
              name: 'courtCity',
              jsonPath: 'MasterMetaData.masterData[0].address.city',
              label: 'MdmsMetadata.masterData.lcms.Court.city',
              pattern: '',
              type: 'text',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: '',
              minLength: 1,
              patternErrorMsg: '',
            }, 
            {
              name: 'courtPincode',
              jsonPath: 'MasterMetaData.masterData[0].address.pincode',
              label: 'MdmsMetadata.masterData.lcms.Court.pincode',
              pattern: '',
              type: 'pinCode',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: '',
              minLength: 1,
              patternErrMsg: 'Pincode should be 6 digit number',
            },
            {
              name: 'courtActive',
              jsonPath: 'MasterMetaData.masterData[0].active',
              label: 'MdmsMetadata.masterData.lcms.Court.active',
              pattern: '',
              type: 'checkbox',
              isRequired: false,
              isDisabled: false,
              patternErrorMsg: '',
              defaultValue: true,
            },
            {
              name: 'tenantId',
              jsonPath: 'MasterMetaData.masterData[0].tenantId',
              type: 'text',             
              defaultValue: localStorage.getItem("tenantId"),
              hide: true
            },
            {
              name: 'moduleName',
              jsonPath: 'MasterMetaData.moduleName',
              type: 'text',             
              defaultValue: 'lcms',
              hide: true
            },
            {
              name: 'masterName',
              jsonPath: 'MasterMetaData.masterName',              
              type: 'text',
              defaultValue: 'court',
              hide: true
            },
          ]
        },       
      ],
      url: '/egov-mdms-create/v1/_create',
      tenantIdRequired: true
    },
    'lcms.view': {
      numCols: 4,
      useTimestamp: true,
      objectName: 'court',
      //searchUrl: '/egov-mdms-service/v1/_search?code={code}',
      groups: [
        {
          name:'courtDetails',
          label: 'lcms.create.group.title.courtDetails',
          fields: [
            
            {
              name: 'courtName',
              jsonPath: 'MdmsRes.lcms.court[0].name',
              label: 'MdmsMetadata.masterData.lcms.Court.name',
              pattern: '',
              type: 'text',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: '',
              minLength: '',
              //url: '/egov-mdms-service/v1/_get?&moduleName=swm&masterName=ShiftType|$..ShiftType.*.code|$..ShiftType.*.name',
            },
            {
              name: 'courtCode',
              jsonPath: 'MdmsRes.lcms.court[0].code',
              label: 'MdmsMetadata.masterData.lcms.Court.code',
              pattern: '',
              type: 'text',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: 128,
              minLength: 1,
              patternErrorMsg: '',
              /*url: "/egov-mdms-service/v1/_get?&moduleName=common-masters&masterName=Department|$..code|$..name",
              hasIdConverion: true,*/
            },
           {
              name: 'address1',
              jsonPath: 'MdmsRes.lcms.court[0].address.addressLine1',
              label: 'MdmsMetadata.masterData.lcms.Court.addressLine1',
              pattern: '',
              type: 'text',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: 128,
              minLength: 1,
              patternErrorMsg: '',
              //url: '/hr-masters/designations/_search?tenantId=default|$..id|$..name',
            },
            {
              name: 'address2',
              jsonPath: 'MdmsRes.lcms.court[0].address.addressLine2',
              label: 'MdmsMetadata.masterData.lcms.Court.addressLine2',
              pattern: '',
              type: 'text',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: 128,
              minLength: 1,
              patternErrorMsg: '',
            },
            {
              name: 'courtCity',
              jsonPath: 'MdmsRes.lcms.court[0].address.city',
              label: 'MdmsMetadata.masterData.lcms.Court.city',
              pattern: '',
              type: 'text',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: 128,
              minLength: 1,
              patternErrorMsg: '',
            }, 
            {
              name: 'courtPincode',
              jsonPath: 'MdmsRes.lcms.court[0].address.pincode',
              label: 'MdmsMetadata.masterData.lcms.Court.pincode',
              pattern: '',
              type: 'text',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: 128,
              minLength: 1,
              patternErrorMsg: '',
            },
            {
              name: 'courtActive',
              jsonPath: 'MdmsRes.lcms.court[0].active',
              label: 'MdmsMetadata.masterData.lcms.Court.active',
              pattern: '',
              type: 'text',
              isRequired: false,
              isDisabled: false,
              patternErrorMsg: '',
              defaultValue: true,
            },
          ]
        },
        
      ],
      tenantIdRequired: true,
      url: '/egov-mdms-service/v1/_search?code={code}',
    },
    'lcms.update': {
      numCols: 3,
      useTimestamp: true,
      objectName: 'court',
      idJsonPath : 'MasterMetaData.masterData[0].code',
      //idJsonPath: 'MdmsRes.lcms.court[0].code',
      groups: [
        {
          name:'courtDetails',
          label: 'lcms.create.group.title.courtDetails',
          fields: [
            {
              name: 'courtName',
              jsonPath: 'MasterMetaData.masterData[0].name',
              label: 'MdmsMetadata.masterData.lcms.Court.name',
              pattern: '',
              type: 'text',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: 100,
              minLength: 1,
              //url: '/egov-mdms-service/v1/_get?&moduleName=swm&masterName=ShiftType|$..ShiftType.*.code|$..ShiftType.*.name',
            },
            {
              name: 'courtCode',
              jsonPath: 'MasterMetaData.masterData[0].code',
              label: 'MdmsMetadata.masterData.lcms.Court.code',
              pattern: '',
              type: 'text',
              isRequired: true,
              isDisabled: true,
              defaultValue: '',
              maxLength: 128,
              minLength: 1,
              patternErrorMsg: '',
              /*url: "/egov-mdms-service/v1/_get?&moduleName=common-masters&masterName=Department|$..code|$..name",
              hasIdConverion: true,*/
            },
           {
              name: 'address1',
              jsonPath: 'MasterMetaData.masterData[0].address.addressLine1',
              label: 'MdmsMetadata.masterData.lcms.Court.addressLine1',
              pattern: '',
              type: 'text',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: '',
              minLength: 1,
              patternErrorMsg: '',
              //url: '/hr-masters/designations/_search?tenantId=default|$..id|$..name',
            },
            {
              name: 'address2',
              jsonPath: 'MasterMetaData.masterData[0].address.addressLine2',
              label: 'MdmsMetadata.masterData.lcms.Court.addressLine2',
              pattern: '',
              type: 'text',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: '',
              minLength: 1,
              patternErrorMsg: '',
            },
            {
              name: 'courtCity',
              jsonPath: 'MasterMetaData.masterData[0].address.city',
              label: 'MdmsMetadata.masterData.lcms.Court.city',
              pattern: '',
              type: 'text',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: '',
              minLength: 1,
              patternErrorMsg: '',
            }, 
            {
              name: 'courtPincode',
              jsonPath: 'MasterMetaData.masterData[0].address.pincode',
              label: 'MdmsMetadata.masterData.lcms.Court.pincode',
              pattern: '',
              type: 'pinCode',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: '',
              minLength: 1,
              patternErrMsg: 'Pincode should be 6 digit number',
            },
            {
              name: 'courtActive',
              jsonPath: 'MasterMetaData.masterData[0].active',
              label: 'MdmsMetadata.masterData.lcms.Court.active',
              pattern: '',
              type: 'checkbox',
              isRequired: false,
              isDisabled: false,
              patternErrorMsg: '',
              defaultValue: true,
            },
            {
              name: 'tenantId',
              jsonPath: 'MasterMetaData.masterData[0].tenantId',
              type: 'text',             
              defaultValue: localStorage.getItem("tenantId"),
              hide: true
            },
            {
              name: 'moduleName',
              jsonPath: 'MasterMetaData.moduleName',
              type: 'text',             
              defaultValue: 'lcms',
              hide: true
            },
            {
              name: 'masterName',
              jsonPath: 'MasterMetaData.masterName',              
              type: 'text',
              defaultValue: 'court',
              hide: true
            },
          ]
        },
        
      ],
      url: '/egov-mdms-create/v1/_update',
      tenantIdRequired: true,
      isMDMSScreen: true,
      searchUrl: '/egov-mdms-service/v1/_search?code={code}',
    },
  };
  export default dat;