/*
 * eChallan System
 * ### API Specs For eChallan System ### 1. Generate the new challan. 2. Update the details of existing challan 3. Search the existing challan 4. Generate the demand and bill for the challan amount so that collection can be done in online and offline mode. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.egov.echallan.model;

import java.util.Objects;

import org.egov.common.contract.response.ResponseInfo;
import org.egov.echallan.web.models.calculation.Calculation;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.validator.constraints.SafeHtml;

import javax.validation.Valid;
import java.util.ArrayList;
import java.util.List;

/**
 * Capture the challan details 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-10T16:46:24.044+05:30[Asia/Calcutta]")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Challan {

  @JsonProperty("citizen")
  @Valid
  private UserInfo citizen = null;

  @JsonProperty("id")
  @SafeHtml
  private String id = null;

  @JsonProperty("tenantId")
  @SafeHtml
  private String tenantId = null;

  @JsonProperty("businessService")
  @SafeHtml
  private String businessService = null;

  @JsonProperty("challanNo")
  @SafeHtml
  private String challanNo = null;

  @JsonProperty("referenceId")
  @SafeHtml
  private String referenceId = null;

  @JsonProperty("description")
  @SafeHtml
  private String description = null;

  @JsonProperty("accountId")
  @SafeHtml
  private String accountId = null;

  @JsonProperty("additionalDetail")

  private Object additionalDetail = null;

  @JsonProperty("source")
  @SafeHtml
  private String source = null;
  
  @JsonProperty("taxPeriodFrom")
  private Long taxPeriodFrom = null;

  @JsonProperty("taxPeriodTo")
  private Long taxPeriodTo = null;

  @JsonProperty("calculation")
  private Calculation calculation;
  
  @JsonProperty("amount")
  private List<Amount> amount;

  @JsonProperty("address")

  private Address address = null;
  
  @JsonProperty("filestoreid")
  @SafeHtml
  private String filestoreid = null;

  @JsonProperty("auditDetails")

  private AuditDetails auditDetails = null;
  public Challan citizen(UserInfo citizen) {
    this.citizen = citizen;
    return this;
  }

  public enum StatusEnum {
	  ACTIVE("ACTIVE"),

	  CANCELLED("CANCELLED"),

	  PAID("PAID");

      private String value;

      StatusEnum(String value) {
          this.value = value;
      }

      @Override
      @JsonValue
      public String toString() {
          return String.valueOf(value);
      }

      @JsonCreator
      public static StatusEnum fromValue(String text) {
          for (StatusEnum b : StatusEnum.values()) {
              if (String.valueOf(b.value).equals(text)) {
                  return b;
              }
          }
          return null;
      }
  }

  @JsonProperty("applicationStatus")
  private StatusEnum applicationStatus = null;

  @JsonProperty("receiptNumber")
    private String receiptNumber = null;
}
