export const SET_DROPDOWN_DATA = "SET_DROPDOWN_DATA";
export const EMPLOYEE_FETCH_SUCCESS = "EMPLOYEE_FETCH_SUCCESS";
export const EMPLOYEE_FETCH_ERROR = "EMPLOYEE_FETCH_ERROR";
export const CITIZEN_FETCH_SUCCESS = "CITIZEN_FETCH_SUCCESS";
export const CITIZEN_FETCH_ERROR = "CITIZEN_FETCH_ERROR";
export const MDMS_FETCH_SUCCESS = "MDMS_FETCH_SUCCESS";
export const MDMS_FETCH_ERROR = "MDMS_FETCH_ERROR";
