export const COMPLAINTS_FETCH_PENDING = "COMPLAINTS_FETCH_PENDING";
export const COMPLAINTS_FETCH_COMPLETE = "COMPLAINTS_FETCH_COMPLETE";
export const COMPLAINTS_FETCH_ERROR = "COMPLAINTS_FETCH_ERROR";
export const COMPLAINTS_CATEGORIES_FETCH_SUCCESS = "COMPLAINTS_CATEGORIES_FETCH_SUCCESS";
export const COMPLAINTS_CATEGORIES_FETCH_ERROR = "COMPLAINTS_CATEGORIES_FETCH_ERROR";
