INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),7,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 7',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 7', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),8,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 8',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 8', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),9,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 9',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 9', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),10,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 10',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 10', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),11,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 11',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 11', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),12,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 12',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 12', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),13,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 13',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 13', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),14,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 14',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 14', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),15,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 15',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 15', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),16,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 16',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 16', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),17,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 17',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 17', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),18,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 18',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 18', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),19,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 19',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 19', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),20,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 20',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 20', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),21,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 21',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 21', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),22,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 22',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 22', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),23,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 23',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 23', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),24,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 24',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 24', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),25,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 25',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 25', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),26,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 26',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 26', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),27,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 27',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 27', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),28,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 28',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 28', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),29,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 29',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 29', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),30,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 30',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 30', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),31,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 31',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 31', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),32,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 32',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 32', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),33,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 33',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 33', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),34,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 34',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 34', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),35,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 35',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 35', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),36,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 36',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 36', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),37,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 37',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 37', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),38,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 38',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 38', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),39,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 39',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 39', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),40,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 40',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 40', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),41,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 41',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 41', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),42,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 42',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 42', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),43,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 43',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 43', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),44,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 44',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 44', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),45,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 45',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 45', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),46,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 46',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 46', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),47,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 47',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 47', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),48,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 48',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 48', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),49,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 49',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 49', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),50,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 50',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 50', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');

INSERT INTO eg_boundary (id, boundarynum, parent, name, boundarytype, localname, bndry_name_old, bndry_name_old_local, fromdate, todate, bndryid, longitude, latitude, materializedpath, ishistory, createddate, lastmodifieddate, createdby, lastmodifiedby, version,tenantid)
VALUES(nextval('seq_eg_boundary'),51,(select id from eg_boundary where parent is null and boundarytype = (select id from eg_boundary_type where code = 'ADMCITY' and tenantid = 'default')),'Election Ward No 51',(select id from eg_boundary_type where name = 'Ward' and tenantid = 'default' and hierarchytype = (select id from eg_hierarchy_type where code = 'ADMIN' and tenantid = 'default')), 'Election Ward No No 51', NULL, NULL, '2004-04-01 00:00:00', '2099-04-01 00:00:00', NULL, NULL, NULL, '3.2', false, '2015-08-28 10:44:03.831086', '2015-08-28 10:44:03.831086', 1, 1,NULL,'default');
