CREATE TABLE EGDU_UPLOADREGISTRY
(
  ID SERIAL,
  CODE CHARACTER VARYING NOT NULL,
  TENANTID CHARACTER VARYING NOT NULL,
  REQUESTFILE_PATH CHARACTER VARYING NOT NULL,
  MODULE_NAME CHARACTER VARYING NOT NULL,
  DEF_NAME CHARACTER VARYING NOT NULL,
  REQUESTER_NAME CHARACTER VARYING NOT NULL,
  START_TIME BIGINT,
  END_TIME BIGINT,
  TOTAL_ROWS BIGINT,
  SUCCESS_ROWS BIGINT,
  FAILED_ROWS BIGINT,
  RESPONSEFILE_PATH CHARACTER VARYING,
  STATUS CHARACTER VARYING NOT NULL,
  CREATEDBY BIGINT NOT NULL,
  CREATEDDATE BIGINT NOT NULL,
  LASTMODIFIEDBY BIGINT NOT NULL,
  LASTMODIFIEDDATE BIGINT NOT NULL,
  
  CONSTRAINT PK_UPLOAD_REGISTRY PRIMARY KEY (CODE,TENANTID)
);