drop table IF EXISTS egcl_bank_remittance;
drop table IF EXISTS egcl_branchuser_map;
drop table IF EXISTS egcl_challanheader;
drop table IF EXISTS egcl_collectioninstrument;
drop table IF EXISTS egcl_collectionmis;
drop table IF EXISTS egcl_collectionvoucher;
drop table IF EXISTS egcl_dishonorchequesubdetail;
drop table IF EXISTS egcl_dishonorchequedetail;
drop table IF EXISTS egcl_dishonorcheque;
drop table IF EXISTS egcl_onlinepayments;
drop table IF EXISTS egcl_remittance_instrument;
drop table IF EXISTS egcl_service_dept_mapping;
drop table IF EXISTS egcl_service_instrumentaccounts;
drop table IF EXISTS egcl_servicemodule_mapping ;
alter table egcl_collectionheader drop column if exists location;
drop table IF EXISTS eg_collectionindex;
drop SEQUENCE IF EXISTS SEQ_EGCL_SERVICEMODULE_MAPPING;
drop SEQUENCE IF EXISTS seq_egcl_service_instrumentaccounts;
drop SEQUENCE IF EXISTS seq_egcl_remittance_instrument;
drop SEQUENCE IF EXISTS seq_egcl_onlinepayments;
drop SEQUENCE IF EXISTS seq_egcl_dishonorcheque;
drop SEQUENCE IF EXISTS seq_egcl_dishonorchequedetail;
drop SEQUENCE IF EXISTS seq_egcl_dishonorchequesubdetail;
drop SEQUENCE IF EXISTS seq_egcl_collectionvoucher;
drop SEQUENCE IF EXISTS seq_egcl_collectionmis;
drop SEQUENCE IF EXISTS seq_egcl_challanheader;
drop SEQUENCE IF EXISTS SEQ_EGCL_BRANCHUSER_MAP;
drop SEQUENCE IF EXISTS seq_egcl_bank_remittance;
