INSERT INTO egf_accountdetailtype (id, name, description, tablename, active, fully_qualified_name, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (1, 'Employee', 'Employee', 'eg_employee', true, 'org.egov.eis.entity.Employee', 1, NULL, NULL, NULL, 0, 'default');
INSERT INTO egf_accountdetailtype (id, name, description, tablename, active, fully_qualified_name, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (2, 'Telephone', 'Telephone', 'accountEntityMaster', true, 'org.egov.masters.model.AccountEntity', 1, NULL, NULL, NULL, 0, 'default');
INSERT INTO egf_accountdetailtype (id, name, description, tablename, active, fully_qualified_name, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (3, 'DrawingOfficer', 'Drawing Officer', 'EG_DRAWINGOFFICER', true, 'org.egov.eis.entity.DrawingOfficer', 1, NULL, NULL, NULL, 0, 'default');
INSERT INTO egf_accountdetailtype (id, name, description, tablename, active, fully_qualified_name, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (4, 'contractor', 'contractor', 'egw_contractor', true, 'org.egov.works.models.masters.Contractor', 1, NULL, NULL, NULL, 0, 'default');
INSERT INTO egf_accountdetailtype (id, name, description, tablename, active, fully_qualified_name, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (5, 'PROJECTCODE', 'PROJECTCODE', 'egw_projectcode', true, 'org.egov.works.models.estimate.ProjectCode', 1, NULL, NULL, NULL, 0, 'default');
INSERT INTO egf_accountdetailtype (id, name, description, tablename, active, fully_qualified_name, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (11, 'Supplier', 'Supplier', 'Supplier', true, 'org.egov.commons.Relation', 1, NULL, NULL, NULL, 0, 'default');
INSERT INTO egf_accountdetailtype (id, name, description, tablename, active, fully_qualified_name, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (12, 'DEPOSITCODE', 'DEPOSITCODE', 'egw_depositcode', true, 'org.egov.works.models.masters.DepositCode', 1, '2017-05-08', NULL, NULL, NULL, 'default');
INSERT INTO egf_accountdetailtype (id, name, description, tablename, active, fully_qualified_name, createdby, createddate, lastmodifiedby, lastmodifieddate, version, tenantid) VALUES (13, 'lawyer', 'Standing Counsel', 'eglc_advocate_master', true, 'org.egov.lcms.masters.entity.AdvocateMaster', 1, '2017-05-08', NULL, '2017-05-08', 0, 'default');

SELECT setval('seq_egf_accountdetailtype',(select max(id)+1 from egf_accountdetailtype));
