-----------------START--------------------
INSERT INTO eg_module (id, name, enabled, contextroot, parentmodule, displayname, ordernumber) select 1, 'Administration', true, 'egi', NULL, 'Administration', 1 where not exists (select name from eg_module where name='Administration');
INSERT INTO eg_module (id, name, enabled, contextroot, parentmodule, displayname, ordernumber) select 2, 'Boundary Module', true, NULL, 1, 'Jurisdiction', 1 where not exists (select name from eg_module where name='Boundary Module');
INSERT INTO eg_module (id, name, enabled, contextroot, parentmodule, displayname, ordernumber) select 3, 'Department', true, NULL, 1, 'Department', 4 where not exists (select name from eg_module where name='Department');
INSERT INTO eg_module (id, name, enabled, contextroot, parentmodule, displayname, ordernumber) select 5, 'User Module', true, NULL, 1, 'User Management', 2 where not exists (select name from eg_module where name='User Module');
INSERT INTO eg_module (id, name, enabled, contextroot, parentmodule, displayname, ordernumber) select 115, 'Configuration', true, NULL, 1, 'Configuration', 3 where not exists (select name from eg_module where name='Configuration');
INSERT INTO eg_module (id, name, enabled, contextroot, parentmodule, displayname, ordernumber) select 237, 'EGI-COMMON', false, 'egi', 1, 'EgiPortal', NULL where not exists (select name from eg_module where name='EGI-COMMON');
INSERT INTO eg_module (id, name, enabled, contextroot, parentmodule, displayname, ordernumber) select 379, 'Boundary Type', true, NULL, 2, 'Boundary Type', 2 where not exists (select name from eg_module where name='Boundary Type');
INSERT INTO eg_module (id, name, enabled, contextroot, parentmodule, displayname, ordernumber) select 380, 'Hierarchy Type', true, NULL, 2, 'Hierarchy Type', 1 where not exists (select name from eg_module where name='Hierarchy Type');
INSERT INTO eg_module (id, name, enabled, contextroot, parentmodule, displayname, ordernumber) select 381, 'Boundary', true, NULL, 2, 'Boundary', 3 where not exists (select name from eg_module where name='Boundary');
INSERT INTO eg_module (id, name, enabled, contextroot, parentmodule, displayname, ordernumber) select 411, 'EGI-SETUP', true, NULL, 1, 'Setups', 5 where not exists (select name from eg_module where name='EGI-SETUP');
------------------END---------------------

-----------------START--------------------
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 1049, 'ajaxuserlist', '/userRole/ajax/userlist', NULL, 237, NULL, 'ajaxuserlist', false, 'egi', 0, 1, '2015-08-28 10:43:42.414686', 1, '2015-08-28 10:43:42.414686', 1 where not exists (select name from eg_action where name='ajaxuserlist');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 69, 'ViewuserRoleForm', '/userrole/search', NULL, 5, 0, 'Search User Role', true, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='ViewuserRoleForm');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 1015, 'AppConfigModuleAutocomplete', '/appConfig/modules', NULL, 115, 0, 'AppConfigModuleAutocomplete', false, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='AppConfigModuleAutocomplete');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 1036, 'viewAppConfigAjaxResult', '/appConfig/ajax/result', NULL, 115, 3, 'ViewAppConfigAjax', false, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='viewAppConfigAjaxResult');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 1014, 'CreateAppConfig', '/appConfig/create', NULL, 115, 0, 'Create Configuration Value', true, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='CreateAppConfig');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 1016, 'modifyAppConfig', '/appConfig/update', NULL, 115, 1, 'Modify Configuration Value', true, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='modifyAppConfig');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 1035, 'viewAppConfig', '/appConfig/view', NULL, 115, 2, 'View Configuration Value', true, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='viewAppConfig');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 62, 'Role View', '/role/view', NULL, 237, 0, 'Role View', false, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='Role View');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 63, 'Role Update', '/role/update', NULL, 237, 0, 'Role Update', false, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='Role Update');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 25, 'CreateRoleForm', '/role/create', NULL, 5, 0, 'Create Role New', true, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='CreateRoleForm');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 26, 'ViewRoleForm', '/role/viewsearch', NULL, 5, 0, 'View Role', true, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='ViewRoleForm');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 27, 'UpdateRoleForm', '/role/updatesearch', NULL, 5, 0, 'Update Role', true, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='UpdateRoleForm');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 70, 'UpdateuserRoleForm', '/userrole/update', NULL, 5, 0, 'Update User Role', false, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='UpdateuserRoleForm');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 71, 'UpdateuserRole', '/userrole/update/updateUserRole', NULL, 5, 0, 'Update User Roles ', false, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='UpdateuserRole');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 72, 'viewuserRole', '/userrole/view', NULL, 5, 0, 'View User Roles ', false, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='viewuserRole');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 73, 'AjaxLoadRoleByUser', '/userRole/ajax/rolelist-for-user', NULL, 5, 0, 'AjaxLoadRoleByUser', false, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='AjaxLoadRoleByUser');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 1041, 'AppconfigPopulateList', '/appConfig/ajax-appConfigpopulate', NULL, 115, 0, 'AppconfigPopulateList', false, 'egi', 0, 1, '2015-08-28 10:43:36.565418', 1, '2015-08-28 10:43:36.565418', 1 where not exists (select name from eg_action where name='AppconfigPopulateList');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 1044, 'AppconfigValuesListForView', '/appConfig/viewList/', NULL, 115, 0, 'AppconfigValuesListForView', false, 'egi', 0, 1, '2015-08-28 10:43:38.270542', 1, '2015-08-28 10:43:38.270542', 1 where not exists (select name from eg_action where name='AppconfigValuesListForView');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 66, 'OfficialsProfileEdit', '/home/profile/edit', NULL, 237, NULL, 'OfficialsProfileEdit', false, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='OfficialsProfileEdit');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 67, 'OfficialSentFeedBack', '/home/feedback/sent', NULL, 237, NULL, 'OfficialSentFeedBack', false, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='OfficialSentFeedBack');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 68, 'OfficialChangePassword', '/home/password/update', NULL, 237, NULL, 'OfficialChangePassword', false, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='OfficialChangePassword');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 59, 'AddFavourite', '/home/favourite/add', NULL, 237, NULL, 'AddFavourite', false, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='AddFavourite');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 58, 'RemoveFavourite', '/home/favourite/remove', NULL, 237, NULL, 'RemoveFavourite', false, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='RemoveFavourite');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 1181, 'CitySetup', '/city/setup/view', NULL, 411, 1, 'City Setup', true, 'egi', 0, 1, '2015-08-28 10:45:30.565663', 1, '2015-08-28 10:45:30.565663', 1 where not exists (select name from eg_action where name='CitySetup');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 1182, 'CitySetupUpdate', '/city/setup/update', NULL, 411, 1, 'CitySetupUpdate', false, 'egi', 0, 1, '2015-08-28 10:45:30.565663', 1, '2015-08-28 10:45:30.565663', 1 where not exists (select name from eg_action where name='CitySetupUpdate');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 1192, 'GisFileDownload', '/downloadfile/gis', NULL, 411, 1, 'GisFileDownload', false, 'egi', 0, 1, '2015-08-28 10:45:31.664804', 1, '2015-08-28 10:45:31.664804', 1 where not exists (select name from eg_action where name='GisFileDownload');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 1224, 'AadhaarInfo', '/aadhaar', NULL, 237, 0, 'AadhaarInfo', false, 'egi', 0, 1, '2015-08-28 10:45:34.775828', 1, '2015-08-28 10:45:34.775828', 1 where not exists (select name from eg_action where name='AadhaarInfo');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 37, 'Official Home Page', '/home', NULL, 237, 0, 'User Login', false, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='Official Home Page');
INSERT INTO eg_action (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) select 56, 'File Download', '/downloadfile', NULL, 237, 0, 'File Download', false, 'egi', 0, 1, '2015-08-28 10:43:35.552035', 1, '2015-08-28 10:43:35.552035', 1 where not exists (select name from eg_action where name='File Download');

DROP SEQUENCE SEQ_EG_ACTION;

CREATE SEQUENCE SEQ_EG_ACTION
    START WITH 1343
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
------------------END---------------------

-----------------START--------------------
INSERT INTO eg_messagetemplate (id, templatename, template, locale, version) select 1, 'user.pwd.recovery', 'Click the link below to reset your password {2} {0}{1} {2} If clicking the link above doesn''''t work, please copy and paste the URL in a new browser window instead.{2}If you''''ve received this in error, it''''s likely that another user entered your email address or mobile number by mistake while trying to reset a password. If you didn''''t initiate the request, you don''''t need to take any further action and can safely disregard this email.', 'en_IN', NULL where not exists (select templatename from eg_messagetemplate where templatename='user.pwd.recovery');
INSERT INTO eg_messagetemplate (id, templatename, template, locale, version) select 2, 'user.pwd.reset', 'Hi {0}, {2} Your password has been reset, your new password is {2} {1} {2} Please change this password as soon as you login for more security.', 'en_IN', NULL where not exists (select templatename from eg_messagetemplate where templatename='user.pwd.reset');
------------------END---------------------

-----------------START--------------------
INSERT INTO eg_role (id, name, description, createddate, createdby, lastmodifiedby, lastmodifieddate, version) select nextval('SEQ_EG_ROLE'), 'CSC Operator', 'Collection Operator mans the Citizen Service Centers.', '2010-01-01 00:00:00', 1, 1, '2015-01-01 00:00:00', 0 where not exists (select name from eg_role where name='CSC Operator');
INSERT INTO eg_role (id, name, description, createddate, createdby, lastmodifiedby, lastmodifieddate, version) select nextval('SEQ_EG_ROLE'), 'Citizen', 'Citizen who can raise complaint', '2010-01-01 00:00:00', 1, 1, '2015-01-01 00:00:00', 0 where not exists (select name from eg_role where name='Citizen');
INSERT INTO eg_role (id, name, description, createddate, createdby, lastmodifiedby, lastmodifieddate, version) select nextval('SEQ_EG_ROLE'), 'Employee', 'Default role for all employees', '2015-08-28 00:00:00', 1, 1, '2015-08-28 00:00:00', 0 where not exists (select name from eg_role where name='Employee');
INSERT INTO eg_role (id, name, description, createddate, createdby, lastmodifiedby, lastmodifieddate, version) select nextval('SEQ_EG_ROLE'), 'ULB Operator', 'ULB Operator', '2015-08-28 10:45:17.567676', 1, 1, '2015-08-28 10:45:17.567676', 0 where not exists (select name from eg_role where name='ULB Operator');
INSERT INTO eg_role (id, name, description, createddate, createdby, lastmodifiedby, lastmodifieddate, version) select nextval('SEQ_EG_ROLE'), 'Super User', 'System Administrator. Can change all master data and has access to all the system screens.', '2010-01-01 00:00:00', 1, 1, '2015-01-01 00:00:00', 0 where not exists (select name from eg_role where name='Super User');
------------------END---------------------

-----------------START--------------------
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation) select 1, NULL, NULL, NULL, 'en_IN', 'egovernments', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2020-12-31 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'Admin', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL where not exists (select username from eg_user where username='egovernments');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation) select 2, NULL, 'MR.', NULL, 'en_IN', 'anonymous', 'XYZ', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'Anonymous', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL where not exists (select username from eg_user where username='anonymous');
------------------END---------------------

-----------------START--------------------
INSERT into eg_userrole select (select id from eg_role where name = 'Super User'), (select id from eg_user where username ='egovernments') where not exists (SELECT * FROM eg_userrole WHERE roleid in (select id from eg_role where name = 'Super User') and userid in (select id from eg_user where username ='egovernments'));
------------------END---------------------

-----------------START--------------------
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Employee'),37 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Employee') and actionid in (37));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),1049 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (1049));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),69 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (69));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),1014 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (1014));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),1015 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (1015));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),1016 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (1016));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),1035 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (1035));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),1036 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (1036));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),62 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (62));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),63 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (63));

Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),66 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (66));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),25 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (25));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),26 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (26));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),27 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (27));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),70 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (70));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),71 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (71));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),72 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (72));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),73 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (73));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),1041 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (1041));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),1044 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (1044));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),66 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (66));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),67 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (67));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),68 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (68));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),58 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (58));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),59 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (59));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),1181 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (1181));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),1182 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (1182));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),1192 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (1192));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),1224 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (1224));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),37 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (37));
Insert into EG_ROLEACTION (roleid, actionid) select (select id from eg_role where name='Super User'),56 where not exists (SELECT * FROM EG_ROLEACTION WHERE roleid in (select id from eg_role where name = 'Super User') and actionid in (56));
------------------END---------------------