ALTER TABLE EDCR_DXF_DOCUMENT RENAME TO EDCR_DOCUMENT;

ALTER SEQUENCE SEQ_EDCR_DXF_DOCUMENT RENAME TO SEQ_EDCR_DOCUMENT;

ALTER TABLE EDCR_DOCUMENT RENAME COLUMN filestoreid to dxffileid;

ALTER TABLE EDCR_DOCUMENT ADD COLUMN reportoutputid bigint;