ALTER TABLE egf_accountdetailkey RENAME detailtypeid TO accountdetailtypeid;
ALTER TABLE egf_accountdetailtype RENAME fully_qualified_name TO fullyqualifiedname;
ALTER TABLE egf_accountentitymaster RENAME TO egf_accountentity;
ALTER TABLE egf_accountentity RENAME detailtypeid TO accountdetailtypeid;
ALTER TABLE egf_bankaccount RENAME branchid TO bankbranchid;
ALTER TABLE egf_bankaccount RENAME glcodeid TO chartofaccountid;
ALTER TABLE egf_bankaccount RENAME type TO typeid;
ALTER TABLE egf_budgetgroup RENAME accounttype TO accounttypeid;
ALTER TABLE egf_budgetgroup RENAME budgetingtype TO budgetingtypeid;
ALTER TABLE egf_chartofaccount RENAME purposeid TO accountcodepurposeid;
ALTER TABLE egf_chartofaccountdetail RENAME glcodeid TO chartofaccountid;
ALTER TABLE egf_chartofaccountdetail RENAME detailtypeid TO accountdetailtypeid;
ALTER TABLE egf_financialyear RENAME financialyear TO finyearrange;
ALTER TABLE egf_subscheme RENAME scheme TO schemeid;
ALTER TABLE egf_supplier RENAME bankaccount TO bankaccountid;
ALTER TABLE egf_supplier RENAME bank TO bankid;
ALTER TABLE egf_accountcodepurpose ALTER COLUMN id TYPE varchar(256);
ALTER TABLE egf_accountcodepurpose ALTER COLUMN createdby TYPE varchar(256);
ALTER TABLE egf_accountcodepurpose ALTER COLUMN lastmodifiedby TYPE varchar(256);
ALTER TABLE egf_accountdetailkey ALTER COLUMN id TYPE varchar(256);
ALTER TABLE egf_accountdetailkey ALTER COLUMN createdby TYPE varchar(256);
ALTER TABLE egf_accountdetailkey ALTER COLUMN lastmodifiedby TYPE varchar(256);
ALTER TABLE egf_accountdetailkey ALTER COLUMN accountdetailtypeid TYPE varchar(256);
ALTER TABLE egf_accountdetailtype ALTER COLUMN id TYPE varchar(256);
ALTER TABLE egf_accountdetailtype ALTER COLUMN createdby TYPE varchar(256);
ALTER TABLE egf_accountdetailtype ALTER COLUMN lastmodifiedby TYPE varchar(256);
ALTER TABLE egf_accountentity ALTER COLUMN id TYPE varchar(256);
ALTER TABLE egf_accountentity ALTER COLUMN createdby TYPE varchar(256);
ALTER TABLE egf_accountentity ALTER COLUMN lastmodifiedby TYPE varchar(256);
ALTER TABLE egf_accountentity ALTER COLUMN accountdetailtypeid TYPE varchar(256);
ALTER TABLE egf_bankaccount ALTER COLUMN id TYPE varchar(256);
ALTER TABLE egf_bankaccount ALTER COLUMN createdby TYPE varchar(256);
ALTER TABLE egf_bankaccount ALTER COLUMN lastmodifiedby TYPE varchar(256);
ALTER TABLE egf_bankaccount ALTER COLUMN bankbranchid TYPE varchar(256);
ALTER TABLE egf_bankaccount ALTER COLUMN chartofaccountid TYPE varchar(256);
ALTER TABLE egf_bankaccount ALTER COLUMN fundid TYPE varchar(256);
ALTER TABLE egf_bankbranch ALTER COLUMN id TYPE varchar(256);
ALTER TABLE egf_bankbranch ALTER COLUMN createdby TYPE varchar(256);
ALTER TABLE egf_bankbranch ALTER COLUMN lastmodifiedby TYPE varchar(256);
ALTER TABLE egf_budgetgroup ALTER COLUMN id TYPE varchar(256);
ALTER TABLE egf_budgetgroup ALTER COLUMN createdby TYPE varchar(256);
ALTER TABLE egf_budgetgroup ALTER COLUMN lastmodifiedby TYPE varchar(256);
ALTER TABLE egf_budgetgroup ALTER COLUMN accounttypeid TYPE varchar(256);
ALTER TABLE egf_chartofaccountdetail ALTER COLUMN id TYPE varchar(256);
ALTER TABLE egf_chartofaccountdetail ALTER COLUMN createdby TYPE varchar(256);
ALTER TABLE egf_chartofaccountdetail ALTER COLUMN lastmodifiedby TYPE varchar(256);
ALTER TABLE egf_chartofaccountdetail ALTER COLUMN chartofaccountid TYPE varchar(256);
ALTER TABLE egf_chartofaccountdetail ALTER COLUMN accountdetailtypeid TYPE varchar(256);
ALTER TABLE egf_chartofaccount ALTER COLUMN id TYPE varchar(256);
ALTER TABLE egf_chartofaccount ALTER COLUMN createdby TYPE varchar(256);
ALTER TABLE egf_chartofaccount ALTER COLUMN lastmodifiedby TYPE varchar(256);
ALTER TABLE egf_chartofaccount ALTER COLUMN accountcodepurposeid TYPE varchar(256);
ALTER TABLE egf_chartofaccount ALTER COLUMN parentid TYPE varchar(256);
ALTER TABLE egf_fiscalperiod ALTER COLUMN id TYPE varchar(256);
ALTER TABLE egf_fiscalperiod ALTER COLUMN createdby TYPE varchar(256);
ALTER TABLE egf_fiscalperiod ALTER COLUMN lastmodifiedby TYPE varchar(256);
ALTER TABLE egf_fiscalperiod DROP CONSTRAINT fk_egf_fiscalperiod_FinancialYearid;
ALTER TABLE egf_fiscalperiod ALTER COLUMN financialyearid TYPE varchar(256);
ALTER TABLE egf_financialyear ALTER COLUMN id TYPE varchar(256);
ALTER TABLE egf_financialyear ALTER COLUMN createdby TYPE varchar(256);
ALTER TABLE egf_financialyear ALTER COLUMN lastmodifiedby TYPE varchar(256);
alter table egf_fiscalperiod add constraint fk_egf_fiscalperiod_FinancialYearid  FOREIGN KEY (FinancialYearid) REFERENCES egf_financialyear(id);
ALTER TABLE egf_functionary ALTER COLUMN id TYPE varchar(256);
ALTER TABLE egf_functionary ALTER COLUMN createdby TYPE varchar(256);
ALTER TABLE egf_functionary ALTER COLUMN lastmodifiedby TYPE varchar(256);
ALTER TABLE egf_function ALTER COLUMN id TYPE varchar(256);
ALTER TABLE egf_function ALTER COLUMN createdby TYPE varchar(256);
ALTER TABLE egf_function ALTER COLUMN lastmodifiedby TYPE varchar(256);
ALTER TABLE egf_function ALTER COLUMN parentid TYPE varchar(256);
ALTER TABLE egf_fund ALTER COLUMN id TYPE varchar(256);
ALTER TABLE egf_fund ALTER COLUMN createdby TYPE varchar(256);
ALTER TABLE egf_fund ALTER COLUMN lastmodifiedby TYPE varchar(256);
ALTER TABLE egf_fund ALTER COLUMN parentid TYPE varchar(256);
ALTER TABLE egf_fundsource ALTER COLUMN createdby TYPE varchar(256);
ALTER TABLE egf_fundsource ALTER COLUMN lastmodifiedby TYPE varchar(256);
ALTER TABLE egf_fundsource DROP CONSTRAINT fk_egf_fundsource_parentid;
ALTER TABLE egf_fundsource ALTER COLUMN id TYPE varchar(256);
ALTER TABLE egf_fundsource ALTER COLUMN parentid TYPE varchar(256);
alter table egf_fundsource add constraint fk_egf_fundsource_parentid  FOREIGN KEY (parentid) REFERENCES egf_fundsource(id);
ALTER TABLE egf_scheme ALTER COLUMN id TYPE varchar(256);
ALTER TABLE egf_scheme ALTER COLUMN createdby TYPE varchar(256);
ALTER TABLE egf_scheme ALTER COLUMN lastmodifiedby TYPE varchar(256);
ALTER TABLE egf_scheme ALTER COLUMN fundid TYPE varchar(256);
ALTER TABLE egf_scheme ALTER COLUMN boundary TYPE varchar(256);
ALTER TABLE egf_subscheme ALTER COLUMN id TYPE varchar(256);
ALTER TABLE egf_subscheme ALTER COLUMN createdby TYPE varchar(256);
ALTER TABLE egf_subscheme ALTER COLUMN lastmodifiedby TYPE varchar(256);
ALTER TABLE egf_subscheme ALTER COLUMN schemeid TYPE varchar(256);
ALTER TABLE egf_supplier ALTER COLUMN id TYPE varchar(256);
ALTER TABLE egf_supplier ALTER COLUMN createdby TYPE varchar(256);
ALTER TABLE egf_supplier ALTER COLUMN lastmodifiedby TYPE varchar(256);
ALTER TABLE egf_supplier ALTER COLUMN bankaccountid TYPE varchar(256);
ALTER TABLE egf_supplier ALTER COLUMN bankid TYPE varchar(256);

alter table egf_bank alter column id TYPE varchar(256);
alter table egf_bank alter column createdby TYPE varchar(256);
alter table egf_bank alter column lastmodifiedby TYPE varchar(256);
alter table egf_bankbranch  alter column bankid TYPE varchar(250);
ALTER TABLE egf_bankaccount RENAME  COLUMN typeid TO  type;
ALTER TABLE egf_budgetgroup RENAME maxcode TO maxcodeid ;
ALTER TABLE egf_budgetgroup alter maxcodeid type  varchar(256) ;
ALTER TABLE egf_budgetgroup RENAME mincode TO mincodeid ;
ALTER TABLE egf_budgetgroup alter mincodeid type  varchar(256) ;
ALTER TABLE egf_budgetgroup RENAME majorcode TO majorcodeid ;
ALTER TABLE egf_budgetgroup alter majorcodeid type  varchar(256) ;
ALTER TABLE egf_accountdetailkey ALTER COLUMN key TYPE varchar(256);



--rollback ALTER TABLE egf_fiscalperiod DROP CONSTRAINT fk_egf_fiscalperiod_FinancialYearid;
--rollback ALTER TABLE egf_fundsource DROP CONSTRAINT fk_egf_fundsource_parentid;
--rollback ALTER TABLE egf_supplier ALTER COLUMN id TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_chartofaccount RENAME accountcodepurposeid TO purposeid;
--rollback ALTER TABLE egf_supplier ALTER COLUMN bankaccountid TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_supplier ALTER COLUMN bankid TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_supplier ALTER COLUMN createdby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_supplier ALTER COLUMN lastmodifiedby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_subscheme ALTER COLUMN id TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_subscheme ALTER COLUMN schemeid TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_subscheme ALTER COLUMN createdby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_subscheme ALTER COLUMN lastmodifiedby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_scheme ALTER COLUMN id TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_scheme ALTER COLUMN fundid TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_scheme ALTER COLUMN boundary TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_scheme ALTER COLUMN createdby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_scheme ALTER COLUMN lastmodifiedby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_fundsource ALTER COLUMN id TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_fundsource ALTER COLUMN parentid TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_fundsource ALTER COLUMN createdby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_fundsource ALTER COLUMN lastmodifiedby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_fund ALTER COLUMN id TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_fund ALTER COLUMN parentid TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_fund ALTER COLUMN createdby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_fund ALTER COLUMN lastmodifiedby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_function ALTER COLUMN id TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_function ALTER COLUMN parentid TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_function ALTER COLUMN createdby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_function ALTER COLUMN lastmodifiedby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_functionary ALTER COLUMN id TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_functionary ALTER COLUMN createdby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_functionary ALTER COLUMN lastmodifiedby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_fiscalperiod ALTER COLUMN financialyearid TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_fiscalperiod ALTER COLUMN id TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_fiscalperiod ALTER COLUMN createdby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_fiscalperiod ALTER COLUMN lastmodifiedby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_financialyear ALTER COLUMN id TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_financialyear ALTER COLUMN createdby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_financialyear ALTER COLUMN lastmodifiedby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_chartofaccount ALTER COLUMN purposeid TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_chartofaccount ALTER COLUMN parentid TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_chartofaccount ALTER COLUMN id TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_chartofaccount ALTER COLUMN createdby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_chartofaccount ALTER COLUMN lastmodifiedby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_chartofaccountdetail ALTER COLUMN chartofaccountid TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_chartofaccountdetail ALTER COLUMN accountdetailtypeid TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_chartofaccountdetail ALTER COLUMN id TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_chartofaccountdetail ALTER COLUMN createdby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_chartofaccountdetail ALTER COLUMN lastmodifiedby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_budgetgroup ALTER COLUMN accounttypeid TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_budgetgroup ALTER COLUMN id TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_budgetgroup ALTER COLUMN createdby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_budgetgroup ALTER COLUMN lastmodifiedby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_bankbranch ALTER COLUMN id TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_bankbranch ALTER COLUMN createdby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_bankbranch ALTER COLUMN lastmodifiedby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_bankaccount ALTER COLUMN bankbranchid TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_bankaccount ALTER COLUMN chartofaccountid TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_bankaccount ALTER COLUMN fundid TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_bankaccount ALTER COLUMN id TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_bankaccount ALTER COLUMN createdby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_bankaccount ALTER COLUMN lastmodifiedby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_accountentity ALTER COLUMN accountdetailtypeid TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_accountentity ALTER COLUMN id TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_accountentity ALTER COLUMN createdby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_accountentity ALTER COLUMN lastmodifiedby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_accountdetailtype ALTER COLUMN id TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_accountdetailtype ALTER COLUMN createdby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_accountdetailtype ALTER COLUMN lastmodifiedby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_accountdetailkey ALTER COLUMN accountdetailtypeid TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_accountdetailkey ALTER COLUMN id TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_accountdetailkey ALTER COLUMN createdby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_accountdetailkey ALTER COLUMN lastmodifiedby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_accountcodepurpose ALTER COLUMN id TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_accountcodepurpose ALTER COLUMN createdby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_accountcodepurpose ALTER COLUMN lastmodifiedby TYPE bigint USING id::bigint;
--rollback ALTER TABLE egf_supplier RENAME bankaccountid TO bankaccount;
--rollback ALTER TABLE egf_supplier RENAME bankid TO bank;
--rollback ALTER TABLE egf_subscheme RENAME schemeid TO scheme;
--rollback ALTER TABLE egf_financialyear RENAME finyearrange TO financialyear;
--rollback ALTER TABLE egf_chartofaccountdetail RENAME chartofaccountid TO glcodeid;
--rollback ALTER TABLE egf_chartofaccountdetail RENAME accountdetailtypeid TO detailtypeid;
--rollback ALTER TABLE egf_budgetgroup RENAME accounttypeid TO accounttype;
--rollback ALTER TABLE egf_budgetgroup RENAME budgetingtypeid TO budgetingtype;
--rollback ALTER TABLE egf_bankaccount RENAME bankbranchid TO branchid;
--rollback ALTER TABLE egf_bankaccount RENAME chartofaccountid TO glcodeid;
--rollback ALTER TABLE egf_bankaccount RENAME typeid TO type;
--rollback ALTER TABLE egf_accountdetailtype RENAME fullyqualifiedname TO fully_qualified_name;
--rollback ALTER TABLE egf_accountdetailkey RENAME accountdetailtypeid TO detailtypeid;
--rollback ALTER TABLE egf_accountentity RENAME TO egf_accountentitymaster;
--rollback ALTER TABLE egf_accountentitymaster RENAME accountdetailtypeid TO detailtypeid;
--rollback alter table egf_fundsource add constraint fk_egf_fundsource_parentid  FOREIGN KEY (parentid) REFERENCES egf_fundsource(id);
--rollback alter table egf_fiscalperiod add constraint fk_egf_fiscalperiod_FinancialYearid  FOREIGN KEY (FinancialYearid) REFERENCES egf_financialyear(id);
