CREATE INDEX IDX_EG_USER_USERNAME ON EG_USER (username);
CREATE INDEX IDX_EG_USER_NAME ON EG_USER (name);
CREATE INDEX IDX_EG_USER_ACTIVE ON EG_USER (active);
CREATE INDEX IDX_EG_USER_MOBILE ON EG_USER (mobilenumber);
CREATE INDEX IDX_EG_USER_TYPE ON EG_USER (type);
CREATE INDEX IDX_EG_USER_UUID ON EG_USER (uuid);
CREATE INDEX IDX_EG_ROLE_CODE ON EG_ROLE (code);
