CREATE SEQUENCE  IF NOT EXISTS seq_expense_billnumber_2017_18
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1;

CREATE SEQUENCE  IF NOT EXISTS seq_expense_billnumber_2018_19
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1;