update chartofaccounts set scheduleid=null where scheduleid in(select id from schedulemapping where reporttype='IE');
delete from schedulemapping where reporttype='IE';

insert into schedulemapping(id,reporttype,schedule,schedulename,createdby,createddate) values(nextval('seq_schedulemapping'),'IE','I-01','TAX REVENUE',1,current_date);
insert into schedulemapping(id,reporttype,schedule,schedulename,createdby,createddate) values(nextval('seq_schedulemapping'),'IE','I-02','ASSIGNED REVENUE  AND  COMPENSATIONS',1,current_date);
insert into schedulemapping(id,reporttype,schedule,schedulename,createdby,createddate) values(nextval('seq_schedulemapping'),'IE','I-03','RENTAL INCOME FROM MUNICIPAL PROPERTIES',1,current_date);
insert into schedulemapping(id,reporttype,schedule,schedulename,createdby,createddate) values(nextval('seq_schedulemapping'),'IE','I-04','FEES  AND  USER CHARGES',1,current_date);
insert into schedulemapping(id,reporttype,schedule,schedulename,createdby,createddate) values(nextval('seq_schedulemapping'),'IE','I-05','SALE  AND  HIRE CHARGES',1,current_date);
insert into schedulemapping(id,reporttype,schedule,schedulename,createdby,createddate) values(nextval('seq_schedulemapping'),'IE','I-06','Revenue Grants, Contribution and Subsidies',1,current_date);
insert into schedulemapping(id,reporttype,schedule,schedulename,createdby,createddate) values(nextval('seq_schedulemapping'),'IE','I-07','Income from Investment',1,current_date);
insert into schedulemapping(id,reporttype,schedule,schedulename,createdby,createddate) values(nextval('seq_schedulemapping'),'IE','I-08','INTEREST EARNED',1,current_date);
insert into schedulemapping(id,reporttype,schedule,schedulename,createdby,createddate) values(nextval('seq_schedulemapping'),'IE','I-09','OTHER INCOME',1,current_date);
insert into schedulemapping(id,reporttype,schedule,schedulename,createdby,createddate) values(nextval('seq_schedulemapping'),'IE','I-10','INCOME-PRIOR PERIOD ITEM',1,current_date);
insert into schedulemapping(id,reporttype,schedule,schedulename,createdby,createddate) values(nextval('seq_schedulemapping'),'IE','I-11','Establishment Expenses',1,current_date);
insert into schedulemapping(id,reporttype,schedule,schedulename,createdby,createddate) values(nextval('seq_schedulemapping'),'IE','I-12','Administrative Expenses',1,current_date);
insert into schedulemapping(id,reporttype,schedule,schedulename,createdby,createddate) values(nextval('seq_schedulemapping'),'IE','I-13','OPERATION AND  MAINTENANCE EXPENSES',1,current_date);
insert into schedulemapping(id,reporttype,schedule,schedulename,createdby,createddate) values(nextval('seq_schedulemapping'),'IE','I-14','INTEREST  AND  FINANCE CHARGES',1,current_date);
insert into schedulemapping(id,reporttype,schedule,schedulename,createdby,createddate) values(nextval('seq_schedulemapping'),'IE','I-15','Programme Expenses',1,current_date);
insert into schedulemapping(id,reporttype,schedule,schedulename,createdby,createddate) values(nextval('seq_schedulemapping'),'IE','I-16','Revenue Grants and Contributions',1,current_date);
insert into schedulemapping(id,reporttype,schedule,schedulename,createdby,createddate) values(nextval('seq_schedulemapping'),'IE','I-17','PROVISIONS AND WRITE OFF',1,current_date);
insert into schedulemapping(id,reporttype,schedule,schedulename,createdby,createddate) values(nextval('seq_schedulemapping'),'IE','I-18','MISCELLANEOUS EXPENSES',1,current_date);
insert into schedulemapping(id,reporttype,schedule,schedulename,createdby,createddate) values(nextval('seq_schedulemapping'),'IE','I-19','Depreciation',1,current_date);
insert into schedulemapping(id,reporttype,schedule,schedulename,createdby,createddate) values(nextval('seq_schedulemapping'),'IE','I-20','EXPENSE-PRIOR PERIOD ITEMS',1,current_date);
