import { useState } from "react";

const TENANTS = [
  {
    i18nKey: "TENANT_TENANTS_PB_JALANDHAR",
    code: "pb.jalandhar",
    name: "Jalandhar",
    description: "Jalandhar",
    logoId: "",
    imageId: "",
    domainUrl: "www.mcjalandhar.in",
    type: "CITY",
    twitterUrl: "https://twitter.com/search?q=%23jalandhar",
    facebookUrl: "https://www.facebook.com/city/jalandhar-Punjab",
    emailId: "complaints.mcj@gmail.com",
    OfficeTimings: {
      "Mon - Fri": "9.00 AM - 6.00 PM",
    },
    city: {
      name: "",
      localName: null,
      districtCode: null,
      districtName: null,
      regionName: null,
      ulbGrade: "",
      longitude: 75.5761829,
      latitude: 31.3260152,
      shapeFileLocation: null,
      captcha: null,
      code: "1013",
      ddrName: "Jalandhar-MC",
    },
    address: "Municipal Corporation Office, Dr. B.R.Ambedkar Admin Complex, Nehru Garden, Jalandhar City-144001",
    pincode: [144001, 144002, 144003, 144004, 144005, 144006, 144007, 144008, 144009, 144010],
    contactNumber: "0181-2227015",
    pdfHeader: "PB_JALANDHAR_PDF_HEADER",
    pdfContactDetails: "PB_JALANDHAR_CONTACT_DETAILS",
  },
  {
    i18nKey: "TENANT_TENANTS_PB_PHAGWARA",
    code: "pb.phagwara",
    name: "Phagwara",
    description: "Phagwara",
    logoId: "https://s3.ap-south-1.amazonaws.com/pb-egov-assets/pb.phagwara/logo.png",
    imageId: "https://s3.ap-south-1.amazonaws.com/pb-egov-assets/pb.phagwara/logo.png",
    domainUrl: "http://www.mcphagwara.com/index.php",
    type: "CITY",
    twitterUrl: null,
    facebookUrl: null,
    emailId: "comm.mcpgr@punjab.gov.in",
    OfficeTimings: {
      "Mon - Fri": "9.00 AM - 6.00 PM",
    },
    city: {
      name: "Phagwara",
      localName: null,
      districtCode: null,
      districtName: null,
      regionName: null,
      ulbGrade: "MC Class I",
      longitude: 75.7708,
      latitude: 31.224,
      shapeFileLocation: null,
      captcha: null,
      code: "807",
      ddrName: "Phagwara-MC",
    },
    address: "Town Hall, Phagwara, Punjab - 144401",
    pincode: [144401, 144402, 144403],
    contactNumber: "01824-260426",
    pdfHeader: "PB_PHAGWARA_PDF_HEADER",
    pdfContactDetails: "PB_PHAGWARA_CONTACT_DETAILS",
  },
  {
    i18nKey: "TENANT_TENANTS_PB_AMRITSAR",
    code: "pb.amritsar",
    name: "Amritsar",
    description: null,
    logoId: "https://s3.ap-south-1.amazonaws.com/pb-egov-assets/pb.amritsar/logo.png",
    imageId: "/pb-egov-assets/pb.amritsar/logo.png",
    domainUrl: "www.amritsarcorp.com",
    type: "CITY",
    twitterUrl: "https://twitter.com/search?q=%23AMRITSAR",
    facebookUrl: "https://www.facebook.com/city/Amritsar-Punjab",
    emailId: "cmcasr@gmail.com",
    OfficeTimings: {
      "Mon - Fri": "9.00 AM - 6.00 PM",
      Sat: "9.00 AM - 12.00 PM",
    },
    city: {
      name: "Amritsar",
      localName: null,
      districtCode: null,
      districtName: null,
      regionName: null,
      ulbGrade: "MC1",
      longitude: 74.8722642,
      latitude: 31.6339793,
      shapeFileLocation: null,
      captcha: null,
      code: "107",
      ddrName: "Amritsar-MC",
    },
    address: "Municipal Corporation Amritsar, Town Hall, Amritsar,Punjab",
    pincode: [143001, 143002, 143003, 143004, 143005, 143006, 143007, 143008, 143009, 143010],
    contactNumber: "0183-2545155",
    helpLineNumber: "0183-2210300",
    pdfHeader: "PB_AMRITSAR_PDF_HEADER",
    pdfContactDetails: "PB_AMRITSAR_CONTACT_DETAILS",
  },
];

const useTenants = () => {
  const tenantInfo = TENANTS;
  console.log("tenantInfo", tenantInfo);
  const [tenants, setTenants] = useState(tenantInfo ? tenantInfo : null);
  return tenants;
};

export default useTenants;
