var dat = {
  'inventory.search': {


    preApiCalls: [
      {
        url: "/inventory-services/stores/_search",
        jsonPath: "store.code",
        jsExpForDD: {
          key: "$..code",
          value: "$..name",
        }
      },
    ],
    numCols: 4,
    useTimestamp: true,
    objectName: '',
    url: '/inventory-services/purchaseorders/_search',
    groups: [{
      name: 'search',
      label: 'inventory.purchaseorder.search.group.title',
      fields: [
        // {
        //   name: 'ids',
        //   jsonPath: 'ids',
        //   label: 'purchaseorder.create.ids',
        //   type: '',
        //   isDisabled: false,
        //   patternErrorMsg: 'purchaseorder.create.field.message.ids',
        // },
        {
          name: 'store',
          jsonPath: 'store',
          label: 'inventory.store.name',
          type: 'number',
          isDisabled: false,
          patternErrorMsg: 'purchaseorder.create.field.message.store',
          
        },
        {
          name: 'purchaseOrderNumber',
          jsonPath: 'purchaseOrderNumber',
          label: 'inventory.purchaseorder.number',
          type: 'text',
          isDisabled: false,
          patternErrorMsg: 'purchaseorder.create.field.message.purchaseOrderNumber',
        },
        {
          name: 'purchaseOrderDate',
          jsonPath: 'purchaseOrderDate',
          label: 'inventory.purchaseorder.date',
          type: 'number',
          isDisabled: false,
          patternErrorMsg: 'purchaseorder.create.field.message.purchaseOrderDate',
        },
        {
          name: 'rateType',
          jsonPath: 'rateType',
          label: 'inventory.rateType',
          type: 'singleValueList',
          isDisabled: false,
          patternErrorMsg: 'purchaseorder.create.field.message.rateType',
        },
        {
          name: 'supplierCode',
          jsonPath: 'supplierCode',
          label: 'inventory.supplier.name',
          type: 'text',
          isDisabled: false,
          patternErrorMsg: 'purchaseorder.create.field.message.supplierCode',
        },
        {
          name: 'status',
          jsonPath: 'status',
          label: 'inventory.status',
          type: 'text',
          isDisabled: false,
          patternErrorMsg: 'purchaseorder.create.field.message.status',
        },
      ],
    },],
    result: {
      header: [{
        label: 'inventory.purchaseorder.number',
      },
      {
        label: 'inventory.purchaseorder.date',
        isDate:true
      },
      {
        label: 'inventory.store.name',
      },
      ],
      values: [
        'purchaseOrderNumber',
       'purchaseOrderDate', 
        { jsonPath: 'store.code', reduxObject: "store.code", isObj: true, cToN: true },
       ],
      resultPath: 'purchaseOrders',
      resultIdKey: 'code',
      rowClickUrlUpdate: '/update/inventory/purchaseorders/{purchaseOrderNumber}',
      rowClickUrlView: '/view/inventory/purchaseorders/{purchaseOrderNumber}',
    },
  },
  'inventory.create': {
    numCols: 4,
    useTimestamp: true,
    objectName: 'purchaseOrders',
    preApiCalls: [
      {
        url: "/hr-employee/employees/_search?&id={}&isPrimary=true",
        jsonPath: "purchaseOrders[0].designation",
        defaultValue: JSON.parse(localStorage.getItem('userRequest')).id,
        dependentUrl: '/hr-masters/designations/_search',
        dependantPath: 'Designation',
        dependentKey: 'id',
        jsExpForDD: {
          key: "$.Employee[0].assignments[0].designation",
          value: "$.Employee[0].assignments[0].designation",
        }
      },
      {
        url: '/inventory-services/pricelists/_search',
        jsonPath: "pricelists",
        jsExpForDD: {
          key: "$..tenant.*.code",
          value: "$..tenant.*.name",
        }
      }
    ],
    groups: [{
      name: 'Group1',
      label: 'inventory.purchaseorder.create.group.title',
      fields: [{
        name: 'code',
        jsonPath: 'purchaseOrders[0].store.code',
        label: 'inventory.store.name',
        pattern: '^[a-zA-Z0-9]+$',
        type: 'singleValueList',
        isRequired: true,
        isDisabled: false,
        defaultValue: '',
        maxLength: 50,
        minLength: 5,
        patternErrorMsg: 'purchaseorder.create.field.message.code',
        url: 'inventory-services/stores/_search?|$.stores[*].code|$.stores[*].name',
      },
      {
        name: 'purchaseOrderNumber',
        jsonPath: 'purchaseOrders[0].purchaseOrderNumber',
        label: 'inventory.purchaseorder.number',
        pattern: '',
        type: 'text',
        isRequired: false,
        isDisabled: true,
        defaultValue: '',
        patternErrorMsg: '',
        isHidden: true,
      },
         {
          name: 'purchaseType',
          jsonPath: 'purchaseOrders[0].purchaseType',
          label: '',
          pattern: '',
          type: 'text',
          isRequired: false,
          isDisabled: false,
          defaultValue: 'Non Indent',
          maxLength: 50,
          minLength: 5,
          patternErrorMsg: '',
          isHidden: true,

        },
        {
          name: 'receivedQuantity',
          jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].receivedQuantity',
          label: '',
          pattern: '',
          type: 'text',
          isRequired: false,
          isDisabled: false,
          // defaultValue: 3,
          maxLength: 50,
          minLength: 5,
          patternErrorMsg: '',
          isHidden: true,
        },
      {
        name: 'purchaseOrderDate',
        jsonPath: 'purchaseOrders[0].purchaseOrderDate',
        label: 'inventory.purchaseorder.date',
        pattern: '',
        type: 'datePicker',
        maxDate: 'today',
        isRequired: true,
        isDisabled: false,
        defaultValue: '',
        patternErrorMsg: '',
        expression: '$purchaseOrders[0].purchaseOrderDate <= $purchaseOrders[0].expectedDeliveryDate',
        expressionMsg: 'Expected Delivery Date should be greater than or equal to Purchase Order Date',
        depedants: [{
          jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.rateContractNumber',
          type: 'griddropDown',
          gridjsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].material.code',
          // pattern: '/inventory-services/pricelists/_search?tenantId=default&supplierName={purchaseOrders[0].supplier.code}&rateType={purchaseOrders[0].rateType}&active=true&asOnDate={purchaseOrders[0].purchaseOrderDate}|$..rateContractNumber|$..rateContractNumber',
        },
      ],
      },
      {
        name: 'rateType',
        jsonPath: 'purchaseOrders[0].rateType',
        label: 'inventory.rateType',
        pattern: '',
        type: 'singleValueList',
        defaultValue: [{
          key: null,
          value: '-- Please Select --'
        },
        {
          key: 'DGSC Rate Contract',
          value: 'DGSC Rate Contract',
        },
        {
          key: 'ULB Rate Contract',
          value: 'ULB Rate Contract',
        },
        {
          key: 'One Time Tender',
          value: 'One Time Tender',
        },
        {
          key: 'Quotation',
          value: 'Quotation',
        },
        ],
        isRequired: true,
        isDisabled: false,
        patternErrorMsg: '',
        depedants: [{
          jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.rateContractNumber',
          type: 'griddropDown',
          gridjsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].material.code',
          // pattern: '/inventory-services/pricelists/_search?tenantId=default&supplierName={purchaseOrders[0].supplier.code}&rateType={purchaseOrders[0].rateType}&active=true&asOnDate={purchaseOrders[0].purchaseOrderDate}|$..rateContractNumber|$..rateContractNumber',
        },],
      },
      {
        name: 'code',
        jsonPath: 'purchaseOrders[0].supplier.code',
        label: 'inventory.supplier.name',
        pattern: '^[a-zA-Z0-9]+$',
        type: 'singleValueList',
        isRequired: true,
        isDisabled: false,
        // defaultValue: '',
        maxLength: 50,
        minLength: 5,
        patternErrorMsg: 'purchaseorder.create.field.message.code',
        url: '/inventory-services/suppliers/_search?status="ACTIVE"|$..code|$..name',
        depedants: [{
          jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.rateContractNumber',
          type: 'griddropDown',
          gridjsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].material.code',
          // pattern: '/inventory-services/pricelists/_search?tenantId=default&supplierName={purchaseOrders[0].supplier.code}&rateType={purchaseOrders[0].rateType}&active=true&asOnDate={purchaseOrders[0].purchaseOrderDate}|$..rateContractNumber|$..rateContractNumber',
        },],
      },
      {
        name: 'advanceAmount',
        jsonPath: 'purchaseOrders[0].advanceAmount',
        label: 'inventory.advanceAmount',
        pattern: '',
        type: 'number',
        isRequired: false,
        isDisabled: false,
        defaultValue: '',
        maxLength: 10,
        patternErrorMsg: '',
        depedants: [{
          jsonPath: 'purchaseOrders[0].advancePercentage',
          type: 'textField',
          pattern: "`${getVal('purchaseOrders[0].advanceAmount')!=''?getVal('purchaseOrders[0].advanceAmount'):0} / ${getVal('purchaseOrders[0].totalAdvancePaidAmount')!=''?getVal('purchaseOrders[0].totalAdvancePaidAmount'):1} *  ${getVal('purchaseOrders[0].totalAdvancePaidAmount')!=''?100:0} `", /// getVal('purchaseOrders.totalAdvancePaidAmount') 
          rg: '',
          isRequired: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        }],
      },
      {
        name: 'advancePercentage',
        jsonPath: 'purchaseOrders[0].advancePercentage',
        label: 'inventory.advancePercentage',
        pattern: '',
        type: 'number',
        isRequired: false,
        isDisabled: false,
        defaultValue: '',
        maxLength: 3,
        patternErrorMsg: '',
        depedants: [{
          jsonPath: 'purchaseOrders[0].advanceAmount',
          type: 'textField',
          pattern: "`${getVal('purchaseOrders[0].advancePercentage')!=''?getVal('purchaseOrders[0].advancePercentage'):0} * ${getVal('purchaseOrders[0].totalAdvancePaidAmount')!=''?getVal('purchaseOrders[0].totalAdvancePaidAmount'):0} / 100 `", /// getVal('purchaseOrders.totalAdvancePaidAmount') 
          rg: '',
          isRequired: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        }],
      },
      {
        name: 'expectedDeliveryDate',
        jsonPath: 'purchaseOrders[0].expectedDeliveryDate',
        label: 'inventory.expectedDeliveryDate',
        pattern: '',
        type: 'datePicker',
        isRequired: false,
        isDisabled: false,
        defaultValue: '',
        patternErrorMsg: '',
        expression: '$purchaseOrders[0].expectedDeliveryDate >= $purchaseOrders[0].purchaseOrderDate',
        expressionMsg: 'Expected Delivery Date should be greater than or equal to Purchase Order Date',
      },
      {
        name: 'deliveryTerms',
        jsonPath: 'purchaseOrders[0].deliveryTerms',
        label: 'inventory.deliveryTerms',
        pattern: '',
        type: 'textarea',
        isRequired: false,
        isDisabled: false,
        defaultValue: '',
        maxLength: 512,
        patternErrorMsg: '',
      },
      {
        name: 'paymentTerms',
        jsonPath: 'purchaseOrders[0].paymentTerms',
        label: 'inventory.paymentTerms',
        pattern: '',
        type: 'textarea',
        isRequired: false,
        isDisabled: false,
        defaultValue: '',
        maxLength: 512,
        patternErrorMsg: '',
      },
      {
        name: 'remarks',
        jsonPath: 'purchaseOrders[0].remarks',
        label: 'inventory.remarks',
        pattern: '',
        type: 'textarea',
        isRequired: false,
        isDisabled: false,
        defaultValue: '',
        maxLength: 1000,
        patternErrorMsg: '',
      },
      {
        name: 'poCreatedBy',
        jsonPath: 'purchaseOrders[0].auditDetails.createdBy',
        label: 'inventory.poCreatedBy',
        pattern: '',
        type: 'text',
        isRequired: false,
        isDisabled: false,
        defaultValue: JSON.parse(localStorage.getItem('userRequest')).name,
        maxLength: 128,
        patternErrorMsg: '',
      },
      {
        name: 'designation',
        jsonPath: 'purchaseOrders[0].designation',
        label: 'inventory.designation',
        pattern: '',
        type: 'text',
        isRequired: false,
        isDisabled: true,
        defaultValue: '',
        maxLength: 128,
        patternErrorMsg: '',
      },
      {
        type: 'tableList',
        jsonPath: 'purchaseOrders[0].purchaseOrderDetails',
        tableList: {
          header: [{
            label: 'inventory.materialName',
          },
          // {
          //   label: 'inventory.indent.number',
          // },
          {
            label: 'inventory.materialDesc',
          },
          {
            label: 'inventory.balance.quantity',
          },
          {
            label: 'inventory.Uom',
          },
          {
            label: 'inventory.ratecontract',
          },
          {
            label: 'inventory.orderqty',
          },
          {
            label: 'inventory.unitRate',
            style: {
              width: '80px',
            },
          },
          {
            label: 'reports.inventory.openbal.TotalAmount',
          },
          {
            label: 'inventory.TenderQuantity',
          },
          {
            label: 'inventory.usedQuantity',
          },
           {
            label: 'inventory.ratecontract',
          },
          ],
          values: [{
            name: 'material',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].material.code',
            label: '',
            pattern: '',
            type: 'autoCompelete',
            isRequired: true,
            isDisabled: false,
            // defaultValue: '',
            maxLength: 50,
            patternErrorMsg: '',
            url: '/egov-mdms-service/v1/_get?&moduleName=inventory&masterName=Material|$..code|$..name|$..description|$..purchaseUom|$..name|$..materialType|$..baseUom|$..expenseAccount|$..stockingUom',
            depedants: [{
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].material.description',
              type: 'textField',
              valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].material.code', getVal('purchaseOrders[0].purchaseOrderDetails[*].material.code'), 'others[0]')",
            },
            {
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].uom.code',
              type: 'textField',
              dependentFlag: true,
              valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].material.code', getVal('purchaseOrders[0].purchaseOrderDetails[*].material.code'), 'others[1].code')",
            },
                {
                jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].material.name',
                type: 'textField',
                valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].material.code', getVal('purchaseOrders[0].purchaseOrderDetails[*].material.code'), 'others[2]')",
              },
              {
                jsonPath: 'purchaseOrders["0"].purchaseOrderDetails["0"].material.materialType',
                type: 'textField',
                valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].material.code', getVal('purchaseOrders[0].purchaseOrderDetails[*].material.code'), 'others[3]')",
              },
              {
                jsonPath: 'purchaseOrders["0"].purchaseOrderDetails["0"].material.baseUom',
                type: 'textField',
                valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].material.code', getVal('purchaseOrders[0].purchaseOrderDetails[*].material.code'), 'others[4]')",
              },
              {
                jsonPath: 'purchaseOrders["0"].purchaseOrderDetails["0"].material.expenseAccount',
                type: 'textField',
                valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].material.code', getVal('purchaseOrders[0].purchaseOrderDetails[*].material.code'), 'others[5]')",
              },
              {
                jsonPath: 'purchaseOrders["0"].purchaseOrderDetails["0"].material.stockingUom',
                type: 'textField',
                valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].material.code', getVal('purchaseOrders[0].purchaseOrderDetails[*].material.code'), 'others[6]')",
              },
            {
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.rateContractNumber',
              type: 'griddropDown',
              autoSelect: true,
              pattern: '/inventory-services/pricelists/_search?tenantId=default&supplierName={purchaseOrders[0].supplier.code}&rateType={purchaseOrders[0].rateType}&active=true&asOnDate={purchaseOrders[0].purchaseOrderDate}&materialCode={purchaseOrders[0].purchaseOrderDetails[0].material.code}|$..rateContractNumber|$..rateContractNumber|$..ratePerUnit|$..quantity|$..tenderUsedQuantity|$..agreementNumber|$..rateContractDate|$..agreementDate|$..agreementStartDate|$..agreementEndDate|$..id',
            },
            ],
          },
          // {
          //   name: 'indentNumber',
          //   jsonPath: 'purchaseOrders[0].purchaseIndentDetails[0].purchaseIndentDetails[0].indentDetail[0].indentNumber',
          //   label: '',
          //   pattern: '',
          //   type: 'text',
          //   isRequired: false,
          //   isDisabled: true,
          //   defaultValue: '',
          //   maxLength: 50,
          //   minLength: 5,
          //   patternErrorMsg: '',
          // },
          {
            name: 'materialDescription',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].material.description',
            label: '',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            // defaultValue: '',
            maxLength: 50,
            minLength: 5,
            patternErrorMsg: '',
          },
            {
            name: 'materialName',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].material.name',
            label: '',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            // defaultValue: '',
            maxLength: 50,
            minLength: 5,
            patternErrorMsg: '',
            isHidden: true,

          },
            {
              name: 'materialTypeName',
              jsonPath: 'purchaseOrders["0"].purchaseOrderDetails["0"].material.materialType',
              label: '',
              pattern: '',
              type: 'text',
              isRequired: false,
              isDisabled: false,
              // defaultValue: '',
              maxLength: 50,
              minLength: 5,
              patternErrorMsg: '',
              isHidden: true,
            },
            {
              name: 'purchaseUom',
              jsonPath: 'purchaseOrders["0"].purchaseOrderDetails["0"].material.purchaseUom',
              label: '',
              pattern: '',
              type: 'text',
              isRequired: false,
              isDisabled: false,
              // defaultValue: '',
              maxLength: 50,
              minLength: 5,
              patternErrorMsg: '',
              isHidden: true,
            },
            {
              name: 'baseUom',
              jsonPath: 'purchaseOrders["0"].purchaseOrderDetails["0"].material.baseUom',
              label: '',
              pattern: '',
              type: 'text',
              isRequired: false,
              isDisabled: false,
              // defaultValue: '',
              maxLength: 50,
              minLength: 5,
              patternErrorMsg: '',
              isHidden: true,
            },
            {
              name: 'expenseAccount',
              jsonPath: 'purchaseOrders["0"].purchaseOrderDetails["0"].material.expenseAccount',
              label: '',
              pattern: '',
              type: 'text',
              isRequired: false,
              isDisabled: false,
              // defaultValue: '',
              maxLength: 50,
              minLength: 5,
              patternErrorMsg: '',
              isHidden: true,
            },
          
            {
              name: 'stockingUom',
              jsonPath: 'purchaseOrders["0"].purchaseOrderDetails["0"].material.stockingUom',
              label: '',
              pattern: '',
              type: 'text',
              isRequired: false,
              isDisabled: false,
              // defaultValue: '',
              maxLength: 50,
              minLength: 5,
              patternErrorMsg: '',
              isHidden: true,
            }, 
          {
            name: 'balanceQuantity',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].purchaseIndentDetails[0].quantity',
            label: '',
            // pattern: '',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            // defaultValue: '',
            patternErrorMsg: '',
          },
          {
            name: 'uom',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].uom.code',
            label: '',
            // pattern: '',
            type: 'singleValueList',
            isRequired: true,
            isDisabled: false,
            // defaultValue: '',
            patternErrorMsg: '',
            url: '/egov-mdms-service/v1/_get?&moduleName=common-masters&masterName=Uom|$..code|$..description|$..conversionFactor',
            depedants: [
              {
                jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].tenderQuantity',
                type: 'autoFill',
                pattern: '/inventory-services/pricelists/_search?tenantId=default&rateContractNumber={purchaseOrders[0].purchaseOrderDetails[0].priceList.rateContractNumber}&uom={purchaseOrders[0].purchaseOrderDetails[0].uom.code}|$..quantity|$..quantity',
                autoFillFields: {
                  'purchaseOrders[0].purchaseOrderDetails[0].tenderQuantity': 'priceLists[0].priceListDetails[0].quantity',
                },
              },
              {
                jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].usedQuantity',
                type: 'autoFill',
                pattern: '/inventory-services/pricelists/_gettenderusedquantity?tenantId=default&material={purchaseOrders[0].purchaseOrderDetails[0].material.code}&priceListId={purchaseOrders[0].purchaseOrderDetails[0].priceList.id}&uom={purchaseOrders[0].purchaseOrderDetails[0].uom.code}|$..tenderUsedQuantity|$..tenderUsedQuantity',
                autoFillFields: {
                  'purchaseOrders[0].purchaseOrderDetails[0].usedQuantity': 'priceLists[0].priceListDetails[0].tenderUsedQuantity',
                },
              },
          //     {
          //       jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].balanceQuantity',
          //       type: 'autoFillBody',
          //       pattern: '/inventory-services/fifologic/_stock',
          //       paramName: 'Fifo',
          //       bodyParams:[{ key: 'tenantId', value: 'default' },
          //       { key: 'store', value: 'purchaseOrders[0].store.code' },
          //       { key: 'material', value: 'purchaseOrders[0].purchaseOrderDetails[0].material.code' },
          //       { key: 'uom', value: 'purchaseOrders[0].purchaseOrderDetails[0].uom.code' },
          //        ],
          //       autoFillFields: {
          //         'purchaseOrders[0].purchaseOrderDetails[0].balanceQuantity': 'stock',
          //       },
          //     },
          //     {
          //       jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].unitPrice',
          //        type: 'autoFillBody',
          //       pattern: '/inventory-services/fifologic/_unitrate',
          //       paramName: 'Fifo',
          //       bodyParams:[{ key: 'tenantId', values: 'default' },
          //       { key: 'userQuantityIssued', values: 'purchaseOrders[0].purchaseOrderDetails[0].userQuantity' },
          //       { key: 'material', values: 'purchaseOrders[0].purchaseOrderDetails[0].material.code' },
          //       { key: 'uom', values: 'purchaseOrders[0].purchaseOrderDetails[0].uom.code' },
          //        ],
          //       autoFillFields: {
          //         'purchaseOrders[0].purchaseOrderDetails[0].unitPrice': 'priceLists[0].priceListDetails[0].quantity',
          //       },
          //     },
             ],
          },
          {
            name: 'rateContractNumber',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.rateContractNumber',
            label: '',
            pattern: '',
            type: 'singleValueList',
            isRequired: true,
            isDisabled: false,
            // defaultValue: [],
            url: '/inventory-services/pricelists/_search?tenantId=default&rateContractNumber={purchaseOrders[0].purchaseOrderDetails[0].priceList.rateContractNumber}&priceListDetails.material.code={purchaseOrders[0].purchaseOrderDetails[0].material.code}|$..rateContractNumber|$..rateContractNumber|$..ratePerUnit|$..quantity',
            patternErrorMsg: '',
            depedants: [{
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].unitPrice',
              type: 'textField',
              dependentFlag: true,
              valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber', getVal('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber'), 'others[0]')",
            },
            {
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].tenderQuantity',
              type: 'textField',
              valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber', getVal('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber'), 'others[1]')",
            },
            // {
            //   jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].usedQuantity',
            //   type: 'textField',
            //   valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractDate', getVal('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber'), 'others[2]')",
            // },
            {
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.agreementNumber',
              type: 'textField',
              valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber', getVal('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber'), 'others[3]')",
            },
            {
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.rateContractDate',
              type: 'textField',
              valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber', getVal('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber'), 'others[4]')",
            },
            {
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.agreementDate',
              type: 'textField',
              valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber', getVal('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber'), 'others[5]')",
            },
            {
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.agreementStartDate',
              type: 'textField',
              valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber', getVal('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber'), 'others[6]')",
            },
            {
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.agreementEndDate',
              type: 'textField',
              valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber', getVal('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber'), 'others[7]')",
            },
            {
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.id',
              type: 'textField',
              valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber', getVal('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber'), 'others[8]')",
            },
            ],
          },
          {
            name: 'orderQuantity',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].userQuantity',
            label: '',
            pattern: '',
            type: 'number',
            isRequired: true,
            isDisabled: false,
            // defaultValue: '',
            patternErrorMsg: '',
            // dependency: 'purchaseOrders[0].totalAdvancePaidAmount:purchaseOrders[0].purchaseOrderDetails[0].unitPrice',
            depedants: [{
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].totalAmount',
              type: 'textField',
              valExp: "`${getVal('purchaseOrders[0].purchaseOrderDetails[*].unitPrice')!=''?getVal('purchaseOrders[0].purchaseOrderDetails[*].unitPrice'):0} * ${getVal('purchaseOrders[0].purchaseOrderDetails[*].userQuantity')!=''?getVal('purchaseOrders[0].purchaseOrderDetails[*].userQuantity'):0}`",
              dependentFlag: true,
              rg: '',
              isRequired: false,
              requiredErrMsg: '',
              patternErrMsg: '',
            }],
            dependantOn: [{
              jsonPath: 'purchaseOrders[0].rateType',
              key: 'One Time Tender',
            }],
            expression: '$purchaseOrders[0].purchaseOrderDetails[0].userQuantity <= $purchaseOrders[0].purchaseOrderDetails[0].tenderQuantity',
            expressionMsg: 'Order Quantity must be Less Than Tender Quantity',
          },
          {
            name: 'unitPrice',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].unitPrice',
            label: '',
            pattern: '',
            type: 'number',
            isRequired: true,
            isDisabled: false,
            // defaultValue: '',
            patternErrorMsg: '',
            // dependency: 'purchaseOrders[0].totalAdvancePaidAmount:purchaseOrders[0].purchaseOrderDetails[0].userQuantity',
            depedants: [{
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].totalAmount',
              type: 'textField',
              dependentFlag: true,
              valExp: "`${getVal('purchaseOrders[0].purchaseOrderDetails[*].unitPrice')!=''?getVal('purchaseOrders[0].purchaseOrderDetails[*].unitPrice'):0} * ${getVal('purchaseOrders[0].purchaseOrderDetails[*].userQuantity')!=''?getVal('purchaseOrders[0].purchaseOrderDetails[*].userQuantity'):0}`",
              rg: '',
              isRequired: false,
              requiredErrMsg: '',
              patternErrMsg: '',
            }],
          },
          {
            name: 'TotalAmount',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].totalAmount',
            label: '',
            pattern: '',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            // defaultValue: '',
            patternErrorMsg: '',
            dependency: 'purchaseOrders[0].totalAdvancePaidAmount',
          },
          {
            name: 'tenderQuantity',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].tenderQuantity',
            label: '',
            pattern: '',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            // defaultValue: '',
            patternErrorMsg: '',
          },
          {
            name: 'usedQuantity',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].usedQuantity',
            label: '',
            pattern: '',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            // defaultValue: '',
            patternErrorMsg: '',
          },
           {
            name: 'priceListId',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.id',
            label: 'inventory.create.rateContractDate',
            pattern: '',
            type: 'text',
            isRequired: false,
            isHidden: true,
            isDisabled: true,
            requiredErrMsg: '',
            // defaultValue: '83',
            patternErrMsg: '',
          },
          {
            name: 'rateContractDate',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.rateContractDate',
            label: 'inventory.create.rateContractDate',
            pattern: '',
            type: 'datePicker',
            isRequired: false,
            isHidden: true,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'agreementNumber',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.agreementNumber',
            label: 'inventory.create.agreementNumber',
            pattern: '',
            type: 'text',
            isRequired: false,
            isHidden: true,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'agreementDate',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.agreementDate',
            label: 'inventory.create.agreementDate',
            pattern: '',
            type: 'datePicker',
            isRequired: false,
            isHidden: true,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'agreementStartDate',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.agreementStartDate',
            label: 'inventory.create.agreementStartDate',
            pattern: '',
            type: 'datePicker',
            isRequired: false,
            isHidden: true,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'agreementEndDate',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.agreementEndDate',
            label: 'inventory.create.agreementEndDate',
            pattern: '',
            type: 'datePicker',
            isRequired: false,
            isHidden: true,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          ],
        },
      },
      {
        name: 'dummy',
        jsonPath: '',
        type: 'textArea',
        defaultValue: '',
        maxLength: 500,

      },
      {
        name: 'dummy',
        jsonPath: '',
        type: 'textArea',
        defaultValue: '',
        maxLength: 500,

      },
      {
        name: 'totalPoValue',
        jsonPath: 'purchaseOrders[0].totalAdvancePaidAmount',
        label: 'inventory.totalPoValue',
        pattern: '',
        type: 'text',
        isRequired: false,
        isDisabled: true,
        defaultValue: '',
        maxLength: 128,
        patternErrorMsg: '',
      },
      {
        name: 'additionalPurchaseWindow',
        jsonPath: 'purchaseOrders[0]',
        arrayPath: 'purchaseOrderDetails',
        label: 'inventory.purchasedetails.create.rateContractWindow',
        pattern: '',
        modulepath: 'inventory.create',
        actionsNotRequired: true,
        type: 'window',
        tableConfig: {
           header: [{
            label: 'inventory.create.rateContractNumber',
            style: {
              width: '700px',
            },
          },],
          rows: [{
            displayField: 'priceList.rateContractNumber',
          },],
        },
        subPath: 'inventory/master/subdetails',
        isRequired: false,
        isDisabled: true,
        requiredErrMsg: '',
        patternErrMsg: '',
        hideAddButton: true
      },
      ],
    },],
    url: '/inventory-services/purchaseorders/_create',
    // onloadFetchUrl: '/inventory-services/purchaseorders/_preparepofromindents',
    tenantIdRequired: true,
  },
  'inventory.view': {
    numCols: 4,
    useTimestamp: true,
    objectName: 'purchaseOrders',
    groups: [{
      name: 'Group1',
      label: 'inventory.purchaseorder.create.group.title',
      fields: [{
        name: 'code',
        jsonPath: 'purchaseOrders[0].store.code',
        label: 'inventory.store.name',
        pattern: '^[a-zA-Z0-9]+$',
        type: 'singleValueList',
        isRequired: true,
        isDisabled: false,
        defaultValue: '',
        maxLength: 50,
        minLength: 5,
        patternErrorMsg: 'purchaseorder.create.field.message.code',
        url: 'inventory-services/stores/_search?|$.stores[*].code|$.stores[*].name',
      },
      {
        name: 'purchaseOrderNumber',
        jsonPath: 'purchaseOrders[0].purchaseOrderNumber',
        label: 'inventory.purchaseorder.number',
        pattern: '',
        type: 'text',
        isRequired: false,
        isDisabled: true,
        defaultValue: '',
        patternErrorMsg: '',
        isHidden: true,
      },
      {
        name: 'purchaseOrderDate',
        jsonPath: 'purchaseOrders[0].purchaseOrderDate',
        label: 'inventory.purchaseorder.date',
        pattern: '',
        type: 'datePicker',
        maxDate: 'today',
        isRequired: true,
        isDisabled: false,
        defaultValue: '',
        patternErrorMsg: '',
        depedants: [{
          jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.rateContractNumber',
          type: 'griddropDown',
          gridjsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].material.code',
          pattern: '/inventory-services/pricelists/_search?tenantId=default&supplierName={purchaseOrders[0].supplier.code}&rateType={purchaseOrders[0].rateType}&active=true&asOnDate={purchaseOrders[0].purchaseOrderDate}|$..rateContractNumber|$..rateContractNumber',
        },],
      },
      {
        name: 'rateType',
        jsonPath: 'purchaseOrders[0].rateType',
        label: 'inventory.rateType',
        pattern: '',
        type: 'singleValueList',
        defaultValue: [{
          key: null,
          value: '-- Please Select --'
        },
        {
          key: 'DGSC Rate Contract',
          value: 'DGSC Rate Contract',
        },
        {
          key: 'ULB Rate Contract',
          value: 'ULB Rate Contract',
        },
        {
          key: 'One Time Tender',
          value: 'One Time Tender',
        },
        {
          key: 'Quotation',
          value: 'Quotation',
        },
        ],
        isRequired: true,
        isDisabled: false,
        patternErrorMsg: '',
      },
      {
        name: 'code',
        jsonPath: 'purchaseOrders[0].supplier.code',
        label: 'inventory.supplier.name',
        pattern: '^[a-zA-Z0-9]+$',
        type: 'singleValueList',
        isRequired: true,
        isDisabled: false,
        defaultValue: '',
        maxLength: 50,
        minLength: 5,
        patternErrorMsg: 'purchaseorder.create.field.message.code',
        url: '/inventory-services/suppliers/_search?status="ACTIVE"|$..code|$..name',
      },
      {
        name: 'advanceAmount',
        jsonPath: 'purchaseOrders[0].advanceAmount',
        label: 'inventory.advanceAmount',
        pattern: '',
        type: 'number',
        isRequired: false,
        isDisabled: false,
        defaultValue: '',
        maxLength: 10,
        patternErrorMsg: '',
      },
      {
        name: 'advancePercentage',
        jsonPath: 'purchaseOrders[0].advancePercentage',
        label: 'inventory.advancePercentage',
        pattern: '',
        type: 'number',
        isRequired: false,
        isDisabled: false,
        defaultValue: '',
        maxLength: 3,
        patternErrorMsg: '',
      },
      {
        name: 'expectedDeliveryDate',
        jsonPath: 'purchaseOrders[0].expectedDeliveryDate',
        label: 'inventory.expectedDeliveryDate',
        pattern: '',
        type: 'datePicker',
        isRequired: false,
        isDisabled: false,
        defaultValue: '',
        patternErrorMsg: '',
      },
      {
        name: 'deliveryTerms',
        jsonPath: 'purchaseOrders[0].deliveryTerms',
        label: 'inventory.deliveryTerms',
        pattern: '',
        type: 'textarea',
        isRequired: false,
        isDisabled: false,
        defaultValue: '',
        maxLength: 512,
        patternErrorMsg: '',
      },
      {
        name: 'paymentTerms',
        jsonPath: 'purchaseOrders[0].paymentTerms',
        label: 'inventory.paymentTerms',
        pattern: '',
        type: 'textarea',
        isRequired: false,
        isDisabled: false,
        defaultValue: '',
        maxLength: 512,
        patternErrorMsg: '',
      },
      {
        name: 'remarks',
        jsonPath: 'purchaseOrders[0].remarks',
        label: 'inventory.remarks',
        pattern: '',
        type: 'textarea',
        isRequired: false,
        isDisabled: false,
        defaultValue: '',
        maxLength: 1000,
        patternErrorMsg: '',
      },
      {
        name: 'designation',
        jsonPath: 'purchaseOrders[0].designation',
        label: 'inventory.designation',
        pattern: '',
        type: 'text',
        isRequired: false,
        isDisabled: true,
        defaultValue: '',
        maxLength: 128,
        patternErrorMsg: '',
      },
      {
        type: 'tableList',
        jsonPath: 'purchaseOrders[0].purchaseOrderDetails',
        tableList: {
          header: [{
            label: 'inventory.materialName',
          },
          // {
          //   label: 'inventory.indent.number',
          // },
          {
            label: 'inventory.materialDesc',
          },
          {
            label: 'inventory.balance.quantity',
          },
          {
            label: 'inventory.Uom',
          },
          {
            label: 'inventory.ratecontract',
          },
          {
            label: 'inventory.orderqty',
          },
          {
            label: 'inventory.unitRate',
            style: {
              width: '80px',
            },
          },
          {
            label: 'reports.inventory.openbal.TotalAmount',
          },
          {
            label: 'inventory.TenderQuantity',
          },
          {
            label: 'inventory.usedQuantity',
          },
          ],
          values: [{
            name: 'material',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].material.code',
            label: '',
            pattern: '',
            type: 'autoCompelete',
            isRequired: true,
            isDisabled: false,
            defaultValue: '',
            maxLength: 50,
            patternErrorMsg: '',
            url: '/egov-mdms-service/v1/_get?&moduleName=inventory&masterName=Material|$..code|$..name|$..description|$..purchaseUom.code',
          },
          {
            name: 'materialDescription',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].material.description',
            label: '',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            maxLength: 50,
            minLength: 5,
            patternErrorMsg: '',
          },
          {
            name: 'balanceQuantity',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].purchaseIndentDetails[0].quantity',
            label: '',
            pattern: '',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
          },
          {
            name: 'uom',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].uom.code',
            label: '',
            pattern: '',
            type: 'singleValueList',
            isRequired: true,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
            url: '/egov-mdms-service/v1/_get?&moduleName=common-masters&masterName=Uom|$..code|$..description',
          },
          {
            name: 'rateContractNumber',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.rateContractNumber',
            label: '',
            pattern: '',
            type: 'singleValueList',
            isRequired: true,
            isDisabled: false,
            defaultValue: [],
            url: '/inventory-services/pricelists/_search?tenantId=default&rateContractNumber={purchaseOrders[0].purchaseOrderDetails[0].priceList.rateContractNumber}&priceListDetails.material.code={purchaseOrders[0].purchaseOrderDetails[0].material.code}|$..rateContractNumber|$..rateContractNumber|$..ratePerUnit|$..quantity',
            patternErrorMsg: '',
          },
          {
            name: 'orderQuantity',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].userQuantity',
            label: '',
            pattern: '',
            type: 'number',
            isRequired: true,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
          },
          {
            name: 'unitPrice',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].unitPrice',
            label: '',
            pattern: '',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
          },
          {
            name: 'TotalAmount',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].totalAmount',
            label: '',
            pattern: '',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
          },
          {
            name: 'tenderQuantity',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].tenderQuantity',
            label: '',
            pattern: '',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
          },
          {
            name: 'usedQuantity',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].usedQuantity',
            label: '',
            pattern: '',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
          },
          ],
        },
      },
      {
        name: 'totalPoValue',
        jsonPath: 'purchaseOrders[0].totalAdvancePaidAmount',
        label: 'inventory.totalPoValue',
        pattern: '',
        type: 'text',
        isRequired: false,
        isDisabled: true,
        defaultValue: '',
        maxLength: 128,
        patternErrorMsg: '',
      },
      ],
    },],
    tenantIdRequired: true,
    url: '/inventory-services/purchaseorders/_search?tenantId={tenantId}',
  },
  'inventory.update': {
    numCols: 4,
    useTimestamp: true,
    objectName: 'purchaseOrders',
    groups: [{
      name: 'Group1',
      label: 'inventory.purchaseorder.create.group.title',
      fields: [{
        name: 'code',
        jsonPath: 'purchaseOrders[0].store.code',
        label: 'inventory.store.name',
        pattern: '^[a-zA-Z0-9]+$',
        type: 'singleValueList',
        isRequired: true,
        isDisabled: false,
        defaultValue: '',
        maxLength: 50,
        minLength: 5,
        patternErrorMsg: 'purchaseorder.create.field.message.code',
        url: 'inventory-services/stores/_search?|$.stores[*].code|$.stores[*].name',
      },
      {
        name: 'purchaseOrderNumber',
        jsonPath: 'purchaseOrders[0].purchaseOrderNumber',
        label: 'inventory.purchaseorder.number',
        pattern: '',
        type: 'text',
        isRequired: false,
        isDisabled: true,
        defaultValue: '',
        patternErrorMsg: '',
        isHidden: true,
      },
      {
        name: 'purchaseOrderDate',
        jsonPath: 'purchaseOrders[0].purchaseOrderDate',
        label: 'inventory.purchaseorder.date',
        pattern: '',
        type: 'datePicker',
        maxDate: 'today',
        isRequired: true,
        isDisabled: false,
        defaultValue: '',
        patternErrorMsg: '',
        expression: '$purchaseOrders[0].expectedDeliveryDate >= $purchaseOrders[0].purchaseOrderDate',
        expressionMsg: 'Expected Delivery Date should be greater than or equal to Purchase Order Date',
        depedants: [{
          jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.rateContractNumber',
          type: 'griddropDown',
          gridjsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].material.code',
          // pattern: '/inventory-services/pricelists/_search?tenantId=default&supplierName={purchaseOrders[0].supplier.code}&rateType={purchaseOrders[0].rateType}&active=true&asOnDate={purchaseOrders[0].purchaseOrderDate}|$..rateContractNumber|$..rateContractNumber',
        },],
      },
      {
        name: 'rateType',
        jsonPath: 'purchaseOrders[0].rateType',
        label: 'inventory.rateType',
        pattern: '',
        type: 'singleValueList',
        defaultValue: [{
          key: null,
          value: '-- Please Select --'
        },
        {
          key: 'DGSC Rate Contract',
          value: 'DGSC Rate Contract',
        },
        {
          key: 'ULB Rate Contract',
          value: 'ULB Rate Contract',
        },
        {
          key: 'One Time Tender',
          value: 'One Time Tender',
        },
        {
          key: 'Quotation',
          value: 'Quotation',
        },
        ],
        isRequired: true,
        isDisabled: false,
        patternErrorMsg: '',
        depedants: [{
          jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.rateContractNumber',
          type: 'griddropDown',
          gridjsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].material.code',
          // pattern: '/inventory-services/pricelists/_search?tenantId=default&supplierName={purchaseOrders[0].supplier.code}&rateType={purchaseOrders[0].rateType}&active=true&asOnDate={purchaseOrders[0].purchaseOrderDate}|$..rateContractNumber|$..rateContractNumber',
        },],
      },
      {
        name: 'code',
        jsonPath: 'purchaseOrders[0].supplier.code',
        label: 'inventory.supplier.name',
        pattern: '^[a-zA-Z0-9]+$',
        type: 'singleValueList',
        isRequired: true,
        isDisabled: false,
        defaultValue: '',
        maxLength: 50,
        minLength: 5,
        patternErrorMsg: 'purchaseorder.create.field.message.code',
        url: '/inventory-services/suppliers/_search?status="ACTIVE"|$..code|$..name',
        depedants: [{
          jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.rateContractNumber',
          type: 'griddropDown',
          gridjsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].material.code',
          // pattern: '/inventory-services/pricelists/_search?tenantId=default&supplierName={purchaseOrders[0].supplier.code}&rateType={purchaseOrders[0].rateType}&active=true&asOnDate={purchaseOrders[0].purchaseOrderDate}|$..rateContractNumber|$..rateContractNumber',
        },],
      },
      {
        name: 'advanceAmount',
        jsonPath: 'purchaseOrders[0].advanceAmount',
        label: 'inventory.advanceAmount',
        pattern: '',
        type: 'number',
        isRequired: false,
        isDisabled: false,
        defaultValue: '',
        maxLength: 10,
        patternErrorMsg: '',
        depedants: [{
          jsonPath: 'purchaseOrders[0].advancePercentage',
          type: 'textField',
          pattern: "`${getVal('purchaseOrders[0].advanceAmount')!=''?getVal('purchaseOrders[0].advanceAmount'):0} / ${getVal('purchaseOrders[0].totalAdvancePaidAmount')!=''?getVal('purchaseOrders[0].totalAdvancePaidAmount'):1} *  ${getVal('purchaseOrders[0].totalAdvancePaidAmount')!=''?100:0} `", /// getVal('purchaseOrders.totalAdvancePaidAmount') 
          rg: '',
          isRequired: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        }],
      },
      {
        name: 'advancePercentage',
        jsonPath: 'purchaseOrders[0].advancePercentage',
        label: 'inventory.advancePercentage',
        pattern: '',
        type: 'number',
        isRequired: false,
        isDisabled: false,
        defaultValue: '',
        maxLength: 3,
        patternErrorMsg: '',
        depedants: [{
          jsonPath: 'purchaseOrders[0].advanceAmount',
          type: 'textField',
          pattern: "`${getVal('purchaseOrders[0].advancePercentage')!=''?getVal('purchaseOrders[0].advancePercentage'):0} * ${getVal('purchaseOrders[0].totalAdvancePaidAmount')!=''?getVal('purchaseOrders[0].totalAdvancePaidAmount'):0} / 100 `", /// getVal('purchaseOrders.totalAdvancePaidAmount') 
          rg: '',
          isRequired: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        }],
      },
      {
        name: 'expectedDeliveryDate',
        jsonPath: 'purchaseOrders[0].expectedDeliveryDate',
        label: 'inventory.expectedDeliveryDate',
        pattern: '',
        type: 'datePicker',
        isRequired: false,
        isDisabled: false,
        defaultValue: '',
        patternErrorMsg: '',
        expression: '$purchaseOrders[0].expectedDeliveryDate >= $purchaseOrders[0].purchaseOrderDate',
        expressionMsg: 'Expected Delivery Date should be greater than or equal to Purchase Order Date',
      },
      {
        name: 'deliveryTerms',
        jsonPath: 'purchaseOrders[0].deliveryTerms',
        label: 'inventory.deliveryTerms',
        pattern: '',
        type: 'textarea',
        isRequired: false,
        isDisabled: false,
        defaultValue: '',
        maxLength: 512,
        patternErrorMsg: '',
      },
      {
        name: 'paymentTerms',
        jsonPath: 'purchaseOrders[0].paymentTerms',
        label: 'inventory.paymentTerms',
        pattern: '',
        type: 'textarea',
        isRequired: false,
        isDisabled: false,
        defaultValue: '',
        maxLength: 512,
        patternErrorMsg: '',
      },
      {
        name: 'remarks',
        jsonPath: 'purchaseOrders[0].remarks',
        label: 'inventory.remarks',
        pattern: '',
        type: 'textarea',
        isRequired: false,
        isDisabled: false,
        defaultValue: '',
        maxLength: 1000,
        patternErrorMsg: '',
      },
      {
        name: 'designation',
        jsonPath: 'purchaseOrders[0].designation',
        label: 'inventory.designation',
        pattern: '',
        type: 'text',
        isRequired: false,
        isDisabled: true,
        defaultValue: '',
        maxLength: 128,
        patternErrorMsg: '',
      },
      {
        type: 'tableList',
        jsonPath: 'purchaseOrders[0].purchaseOrderDetails',
        tableList: {
          header: [{
            label: 'inventory.materialName',
          },
          // {
          //   label: 'inventory.indent.number',
          // },
          {
            label: 'inventory.materialDesc',
          },
          {
            label: 'inventory.balance.quantity',
          },
          {
            label: 'inventory.Uom',
          },
          {
            label: 'inventory.ratecontract',
          },
          {
            label: 'inventory.orderqty',
          },
          {
            label: 'inventory.unitRate',
            style: {
              width: '80px',
            },
          },
          {
            label: 'reports.inventory.openbal.TotalAmount',
          },
          {
            label: 'inventory.TenderQuantity',
          },
          {
            label: 'inventory.usedQuantity',
          },
          ],
          values: [{
            name: 'material',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].material.code',
            label: '',
            pattern: '',
            type: 'autoCompelete',
            isRequired: true,
            isDisabled: false,
            defaultValue: '',
            maxLength: 50,
            patternErrorMsg: '',
            url: '/egov-mdms-service/v1/_get?&moduleName=inventory&masterName=Material|$..code|$..name|$..description|$..purchaseUom.code',
            depedants: [{
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].material.description',
              type: 'textField',
              valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].material.code', getVal('purchaseOrders[0].purchaseOrderDetails[*].material.code'), 'others[0]')",
            },
            {
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].uom.code',
              type: 'textField',
              valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].material.code', getVal('purchaseOrders[0].purchaseOrderDetails[*].material.code'), 'others[1]')",
            },
            {
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.rateContractNumber',
              type: 'griddropDown',
              autoSelect: true,
              pattern: '/inventory-services/pricelists/_search?tenantId=default&supplierName={purchaseOrders[0].supplier.code}&rateType={purchaseOrders[0].rateType}&active=true&asOnDate={purchaseOrders[0].purchaseOrderDate}&materialCode={purchaseOrders[0].purchaseOrderDetails[0].material.code}|$..rateContractNumber|$..rateContractNumber|$..ratePerUnit|$..quantity|$..usedQuantity|$..agreementNumber|$..rateContractDate|$..agreementDate|$..agreementStartDate|$..agreementEndDate',
            },
            ],
          },
          // {
          //   name: 'indentNumber',
          //   jsonPath: 'purchaseOrders[0].purchaseIndentDetails[0].purchaseIndentDetails[0].indentDetail[0].indentNumber',
          //   label: '',
          //   pattern: '',
          //   type: 'text',
          //   isRequired: false,
          //   isDisabled: true,
          //   defaultValue: '',
          //   maxLength: 50,
          //   minLength: 5,
          //   patternErrorMsg: '',
          // },
          {
            name: 'materialDescription',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].material.description',
            label: '',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            maxLength: 50,
            minLength: 5,
            patternErrorMsg: '',
          },
          {
            name: 'balanceQuantity',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].purchaseIndentDetails[0].quantity',
            label: '',
            pattern: '',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
          },
          {
            name: 'uom',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].uom.code',
            label: '',
            pattern: '',
            type: 'singleValueList',
            isRequired: true,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
            url: '/egov-mdms-service/v1/_get?&moduleName=common-masters&masterName=Uom|$..code|$..description',
          },
          {
            name: 'rateContractNumber',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.rateContractNumber',
            label: '',
            pattern: '',
            type: 'singleValueList',
            isRequired: true,
            isDisabled: false,
            defaultValue: [],
            url: '/inventory-services/pricelists/_search?tenantId=default&rateContractNumber={purchaseOrders[0].purchaseOrderDetails[0].priceList.rateContractNumber}&priceListDetails.material.code={purchaseOrders[0].purchaseOrderDetails[0].material.code}|$..rateContractNumber|$..rateContractNumber|$..ratePerUnit|$..quantity',
            patternErrorMsg: '',
            depedants: [{
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].unitPrice',
              type: 'textField',
              valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber', getVal('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber'), 'others[0]')",
            },
            {
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].tenderQuantity',
              type: 'textField',
              valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber', getVal('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber'), 'others[1]')",
            },
            {
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].usedQuantity',
              type: 'textField',
              valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractDate', getVal('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber'), 'others[2]')",
            },
            {
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.agreementNumber',
              type: 'textField',
              valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber', getVal('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber'), 'others[3]')",
            },
            {
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.rateContractDate',
              type: 'textField',
              valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber', getVal('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber'), 'others[4]')",
            },
            {
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.agreementDate',
              type: 'textField',
              valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber', getVal('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber'), 'others[5]')",
            },
            {
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.agreementStartDate',
              type: 'textField',
              valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber', getVal('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber'), 'others[6]')",
            },
            {
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.agreementEndDate',
              type: 'textField',
              valExp: "getValFromDropdownData('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber', getVal('purchaseOrders[0].purchaseOrderDetails[*].priceList.rateContractNumber'), 'others[7]')",
            },
            ],
          },
          {
            name: 'orderQuantity',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].userQuantity',
            label: '',
            pattern: '',
            type: 'number',
            isRequired: true,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
            dependency: 'purchaseOrders[0].totalAdvancePaidAmount:purchaseOrders[0].purchaseOrderDetails[0].unitPrice',
            depedants: [{
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].totalAmount',
              type: 'textField',
              pattern: "`${getVal('purchaseOrders[0].purchaseOrderDetails[*].unitPrice')!=''?getVal('purchaseOrders[0].purchaseOrderDetails[*].unitPrice'):0} * ${getVal('purchaseOrders[0].purchaseOrderDetails[*].userQuantity')!=''?getVal('purchaseOrders[0].purchaseOrderDetails[*].userQuantity'):0}`",
              rg: '',
              isRequired: false,
              requiredErrMsg: '',
              patternErrMsg: '',
            }],
          },
          {
            name: 'unitPrice',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].unitPrice',
            label: '',
            pattern: '',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
            dependency: 'purchaseOrders[0].totalAdvancePaidAmount:purchaseOrders[0].purchaseOrderDetails[0].userQuantity',
            depedants: [{
              jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].totalAmount',
              type: 'textField',
              pattern: "`${getVal('purchaseOrders[0].purchaseOrderDetails[*].unitPrice')!=''?getVal('purchaseOrders[0].purchaseOrderDetails[*].unitPrice'):0} * ${getVal('purchaseOrders[0].purchaseOrderDetails[*].userQuantity')!=''?getVal('purchaseOrders[0].purchaseOrderDetails[*].userQuantity'):0}`",
              rg: '',
              isRequired: false,
              requiredErrMsg: '',
              patternErrMsg: '',
            }],
          },
          {
            name: 'TotalAmount',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].totalAmount',
            label: '',
            pattern: '',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
            // dependency: 'purchaseOrders[0].totalAdvancePaidAmount',
          },
          {
            name: 'tenderQuantity',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].tenderQuantity',
            label: '',
            pattern: '',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
          },
          {
            name: 'usedQuantity',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].usedQuantity',
            label: '',
            pattern: '',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            defaultValue: '',
            patternErrorMsg: '',
          },
          {
            name: 'rateContractDate',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.rateContractDate',
            label: 'inventory.create.rateContractDate',
            pattern: '',
            type: 'datePicker',
            isRequired: false,
            isHidden: true,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'agreementNumber',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.agreementNumber',
            label: 'inventory.create.agreementNumber',
            pattern: '',
            type: 'text',
            isRequired: false,
            isHidden: true,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'agreementDate',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.agreementDate',
            label: 'inventory.create.agreementDate',
            pattern: '',
            type: 'datePicker',
            isRequired: false,
            isHidden: true,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'agreementStartDate',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.agreementStartDate',
            label: 'inventory.create.agreementStartDate',
            pattern: '',
            type: 'datePicker',
            isRequired: false,
            isHidden: true,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'agreementEndDate',
            jsonPath: 'purchaseOrders[0].purchaseOrderDetails[0].priceList.agreementEndDate',
            label: 'inventory.create.agreementEndDate',
            pattern: '',
            type: 'datePicker',
            isRequired: false,
            isHidden: true,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          ],
        },
      },
      {
        name: 'totalPoValue',
        jsonPath: 'purchaseOrders[0].totalAdvancePaidAmount',
        label: 'inventory.totalPoValue',
        pattern: '',
        type: 'text',
        hide: true
      },
      {
        name: 'totalPoValue',
        jsonPath: 'purchaseOrders[0].totalAdvancePaidAmount',
        label: 'inventory.totalPoValue',
        pattern: '',
        type: 'text',
        hide: true

      },
      {
        name: 'totalPoValue',
        jsonPath: 'purchaseOrders[0].totalAdvancePaidAmount',
        label: 'inventory.totalPoValue',
        pattern: '',
        type: 'text',
        isRequired: false,
        isDisabled: true,
        defaultValue: '',
        maxLength: 128,
        patternErrorMsg: '',
      },
      {
        name: 'additionalPurchaseWindow',
        jsonPath: 'purchaseOrders[0]',
        arrayPath: 'purchaseOrderDetails',
        label: 'inventory.purchasedetails.create.rateContractWindow',
        pattern: '',
        modulepath: 'inventory.create',
        actionsNotRequired: true,
        type: 'window',
        tableConfig: {
          header: [{
            label: 'inventory.create.rateContractNumber',
            style: {
              width: '700px',
            },
          },],
          rows: [{
            displayField: 'priceList.rateContractNumber',
          },],
        },
        subPath: 'inventory/master/subdetails',
        isRequired: false,
        isDisabled: true,
        requiredErrMsg: '',
        patternErrMsg: '',
      },
      ],
    },],
    url: '/inventory-services/purchaseorders/_update',
    tenantIdRequired: true,
    searchUrl: '/inventory-services/purchaseorders/_search?tenantId={tenantId}',
  },
};
export default dat;