-----------------START-------------------
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'gayathri', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'gayathri', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'manas', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'manas', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, 'MR.', NULL, 'en_IN', 'narasappa', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'narasappa', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, 'MR.', NULL, 'en_IN', 'krishna', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'krishna', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'elzan', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'elzan', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, 'MR.', NULL, 'en_IN', 'girish', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'girish', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, 'MR.', NULL, 'en_IN', 'iffath', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'iffath', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, 'MR.', NULL, 'en_IN', 'nirbhay', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'nirbhay', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, 'MR.', NULL, 'en_IN', 'prk', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'prk', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, 'MR.', NULL, 'en_IN', 'pradeep', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'pradeep', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'rajashree', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'rajashree', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'ramakrishna', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'ramakrishna', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'manikanta', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'manikanta', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'rishi', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'rishi', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'sathish', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'sathish', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, 'MR.', NULL, 'en_IN', 'mohanraj', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'mohanraj', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, 'MR.', NULL, 'en_IN', 'sankar', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'sankar', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, 'MR.', NULL, 'en_IN', 'vaibhav', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'vaibhav', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, 'MR.', NULL, 'en_IN', 'rajkumar', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'rajkumar', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, 'MR.', NULL, 'en_IN', 'jayashree', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'jayashree', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, 'MR.', NULL, 'en_IN', 'subhash', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'subhash', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'nayeemalla', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'nayeemalla', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'deepa', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'deepa', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'suresh', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'suresh', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'malathi', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'malathi', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'surya', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'surya ', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'satish', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'satish', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'satyam', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'satyam', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'shahid', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'shahid', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'sathyandra', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'sathyandra', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'syed', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'syed', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'seema', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'seema', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'roopa', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'roopa', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'parvati', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'parvati', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'manasa', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'manasa', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'makaraju', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'makaraju', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, 'MR.', NULL, 'en_IN', 'arun', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'arun', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'venkataramana', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'venkataramana', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'mahesh', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'mahesh', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'chandrashekar', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'chandrashekar', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'gireesh', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'gireesh', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'jitha', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'jitha', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'vijay', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'vijay', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'evlyn', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'evlyn', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'pramod', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'pramod', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'vasanth', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'vasanth', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'julian', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'julian', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'gauthami', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'gauthami', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'chetan', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'chetan', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'vikas', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'vikas', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'akash', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'akash', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'shamili', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'shamili', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'mussavir', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'mussavir', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'phanindra', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'phanindra', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'neetu', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'neetu', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'tilak', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'tilak', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO   eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'prabhu', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'prabhu', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'suhail', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'suhail', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'venkatesh', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'venkatesh', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'ramandeep ', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'ramandeep ', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'sumit', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'sumit', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'ravi', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'ravi', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation,
signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', 'dharmendra', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2099-01-01 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, 'dharmendra', NULL, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation, signature, bloodgroup, photo, identificationmark ,tenantid)
VALUES (nextval('seq_eg_user'), NULL, NULL, NULL, 'en_IN', '9999999999', '$2a$10$uheIOutTnD33x7CDqac1zOL8DMiuz7mWplToPgcf7oxAI9OzRKxmK', '2020-12-31 00:00:00', NULL, NULL, NULL, '2010-01-01 00:00:00', '2015-01-01 00:00:00', 1, 1, true, '999999999', NULL, NULL, NULL, 'CITIZEN', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,'identification mark','ap.public');
INSERT INTO eg_user (id, title, salutation, dob, locale, username, password, pwdexpirydate, mobilenumber, altcontactnumber, emailid, createddate, lastmodifieddate, createdby, lastmodifiedby, active, name, gender, pan, aadhaarnumber, type, version, guardian, guardianrelation, signature, bloodgroup,accountlocked,photo,identificationmark, tenantid)
VALUES (156, NULL, 'MR.', NULL, 'en_IN', 'ramana', '$2a$10$/pAdOFmv9h7jrnm2zkEQjOKnWO9/xt8T0t.gkT7rb7t4ugz7QUEPi', '2017-03-10 10:32:17.627', '0123456789', NULL, NULL, '2016-12-10 08:32:45.545', '2016-12-10 10:32:17.629', 1, 73, true, 'Ramana', 1, NULL, NULL, 'EMPLOYEE', 0, NULL, NULL, NULL, 'AB_POSITIVE', NULL,NULL,'identification mark','ap.public');
------------------END---------------------
