var dat = {
    'works.search':{
        numCols:12/2,
        useTimestamp: true,
        title: 'works.search.page.title',
        url: '/works-masters/v1/contractors/_search',
        objectName:'contractors',
        groups:[
              {
                  name: 'search',
                  label: '',
                  fields: [
                      {
                        name:'name',
                        jsonPath:'name',
                        objectName:'name',
                        label:'works.search.name',
                        type:'autoCompelete',
                        isRequired: false,
                        isDisabled: false,
                        url: '/works-masters/v1/contractors/_search?&moduleName=Works&masterName=name|$..code|$..name',
                      },
                      {
                        name:'name',
                        jsonPath:'codes',
                        objectName:'codes',
                        label:'works.search.codes',
                        type:'autoCompelete',
                        isRequired: false,
                        isDisabled: false,
                        url:'/works-masters/v1/contractors/_search?&moduleName=Works&masterName=name|$..code|$..name',
                      },
                      {
                        name:'name',
                        jsonPath:'contractorClass',
                        objectName:'contractorClass',
                        label:'works.search.contractorClass',
                        type:'singleValueList',
                        isRequired: false,
                        isDisabled: false,
                        url:'/egov-mdms-service/v1/_get?tenantId=default&masterName=ContractorClass&moduleName=works|$..description|$..class',
                      },
                      {
                        name:'name',
                        jsonPath:'status',
                        objectName:'status',
                        label:'works.search.statuses',
                        type:'singleValueList',
                        isRequired: false,
                        isDisabled: false,
                        url:'/works-masters/v1/contractors/_search?tenantId=default&masterName=status&moduleName=works|$..description|$..code'
                      }
                  ]
              },
        ],
        result: {
          header: [
            {
              label: 'works.search.result.contractor.codes',
            },
            {
              label: 'works.search.result.contractor.name',
            },
            {
              label: 'works.search.result.contractor.contractorClass',
            },
            {
              label: 'works.search.result.contractor.status',
            }
          ],
          values: ['code','name','contractorClass.class','status.code'],
          resultIdKey: 'id',
          resultPath: 'contractors',
          rowClickUrlUpdate: '/update/works/contractor/{id}',
          rowClickUrlView: '/view/works/contractor/{id}',
        }
    },
    'works.create': {
        numCols: 12/2,
        useTimestamp: true,
        title: 'works.create.page.title.createContrator',
        url: '/works-masters/v1/contractors/_create',
        idJsonPath: 'contractors[0].id',
        objectName: 'contractors',
        tenantIdRequired: true,
        groups: [
                  {
                    label: '',
                    name: 'Create Contractor',
                    stepIndex: 0,
                    fields: [
                              {
                                name: 'name',
                                jsonPath:'contractors[0].name',
                                label: 'works.create.groups.fields.name',
                                type: 'text',
                                isRequired:true,
                                isDisabled: false,
                                requiredErrMsg: '',
                                patternErrMsg: '',
                                maxLength:100,
                                minLength: 1,
                              },
                              {
                                name: 'name',
                                jsonPath:'contractors[0].localName',
                                label: 'works.create.groups.fields.localName',
                                type: 'text',
                                isRequired:false,
                                isDisabled: false,
                                requiredErrMsg: '',
                                patternErrMsg: '',
                                maxLength:100,
                                minLength: 1,
                                default:'null'
                              },
                              {
                                name: 'contactPerson',
                                jsonPath:'contractors[0].contactPerson',
                                label: 'works.create.groups.fields.contactPerson',
                                type: 'text',
                                isRequired:false,
                                isDisabled: false,
                                requiredErrMsg: '',
                                patternErrMsg: '',
                                maxLength:100,
                                minLength: 1,
                              },
                              {
                                name: 'contractorCode',
                                jsonPath:'contractors[0].code',
                                label: 'works.create.groups.fields.code',
                                type: 'text',
                                isRequired:true,
                                isDisabled: false,
                                requiredErrMsg: '',
                                patternErrMsg: '',
                                maxLength: 100,
                                minLength:1,
                              },
                              {
                                name: 'correspondenceAddress',
                                jsonPath: 'contractors[0].correspondenceAddress',
                                label: 'works.create.groups.fields.correspondenceAddress',
                                type: 'text',
                                isRequired:true,
                                isDisabled: false,
                                requiredErrMsg: 'Please enter valid correspondence address',
                                patternErrMsg: '',
                                maxLength:512,
                                minLength: 1,
                              },
                              {
                                name: 'paymentAddress',
                                jsonPath: 'contractors[0].paymentAddress',
                                label: 'works.create.groups.fields.paymentAddress',
                                type: 'text',
                                isRequired:false,
                                isDisabled: false,
                                requiredErrMsg: '',
                                patternErrMsg: '',
                                maxLength:512,
                                minLength: 1,
                              },
                              {
                                name: 'narration',
                                jsonPath: 'contractors[0].narration',
                                label: 'Narration',
                                type: 'text',
                                isRequired:false,
                                isDisabled:false,
                                requiredErrMsg: '',
                                patternErrMsg: '',
                                maxLength:1024,
                                minLength: 1,
                              },
                              {
                                name: 'email',
                                jsonPath: 'contractors[0].email',
                                label: 'works.create.groups.fields.email',
                                type: 'text',
                                isRequired:false,
                                isDisabled: false,
                                requiredErrMsg: '',
                                patternErrMsg: '',
                                maxLength:100,
                                minLength: 1,
                              },
                              {
                                name: 'panNumber',
                                jsonPath: 'contractors[0].panNumber',
                                label: 'works.create.groups.fields.panNumber',
                                type: 'text',
                                isRequired:false,
                                isDisabled: false,
                                requiredErrMsg: '',
                                patternErrMsg:'',
                                maxLength: 10,
                                minLength: 1,
                              },
                              {
                                name: 'mobileNumber',
                                jsonPath: 'contractors[0].mobileNumber',
                                label: 'works.create.groups.fields.mobileNumber',
                                type: 'text',
                                isRequired:true,
                                isDisabled: false,
                                requiredErrMsg: 'Please enter valid Mobile number',
                                patternErrMsg: '',
                                minLength:10,
                                minLength:10,
                              },
                              {
                                name: 'tinNumber',
                                jsonPath: 'contractors[0].tinNumber',
                                label: 'works.create.groups.fields.tinNumber',
                                type: 'text',
                                isRequired:false,
                                isDisabled: false,
                                requiredErrMsg: '',
                                patternErrMsg: '',
                                maxLength:12,
                                minLength: 1,
                              },
                              {
                                name: '',
                                jsonPath: '',
                                label: '',
                                type: 'hidden',
                                isRequired:false,
                                isDisabled: false,
                                requiredErrMsg: '',
                                patternErrMsg: '',
                                maxLength:'',
                                minLength:'',
                                defaultValue:"ACTIVE",
                              },
                              {
                                name: 'bank',
                                jsonPath: 'contractors[0].bank.name',
                                label: 'works.create.groups.fields.bank',
                                type: 'singleValueList',
                                isRequired:false,
                                isDisabled: false,
                                requiredErrMsg: 'Bank name is invalid',
                                patternErrMsg: '',
                                maxLength: 50,
                                minLength: 1,
                                url:'/egov-mdms-service/v1/_get?&moduleName=egf-master&masterName=Bank|$..code|$..name'
                              },
                              {
                                name: 'ifscCode',
                                jsonPath: 'contractors[0].ifscCode',
                                label: 'works.create.groups.fields.ifscCode',
                                type: 'text',
                                isRequired:false,
                                isDisabled: false,
                                requiredErrMsg: '',
                                patternErrMsg: '',
                                maxLength: 50,
                                minLength: 1,
                              },
                              {
                                name: 'bankAccountNumber',
                                jsonPath: 'contractors[0].bankAccountNumber',
                                label: 'works.create.groups.fields.bankAccountNumber',
                                type: 'text',
                                isRequired:false,
                                isDisabled: false,
                                requiredErrMsg: '',
                                patternErrMsg: '',
                                maxLength:20,
                                minLength: 1,
                              },
                              {
                                name: 'exemptedFrom',
                                jsonPath: 'contractors[0].exemptedFrom',
                                label: 'works.create.groups.fields.exemptedFrom',
                                type: 'singleValueList',
                                isRequired:false,
                                isDisabled: false,
                                requiredErrMsg: '',
                                patternErrMsg: '',
                                maxLength: 50,
                                minLength: 1,
                                url:'',
                                defaultValue: [
                                  {
                                    key: 'INCOME_TAX',
                                    value: 'INCOME TAX',
                                  },
                                  {
                                    key: 'EARNEST_MONEY_DEPOSIT',
                                    value: 'EARNEST MONEY DEPOSIT',
                                  },
                                  {
                                    key: 'VAT',
                                    value: 'VAT',
                                  },
                                ],
                              },
                              {
                                name: 'pwdApprovalCode',
                                jsonPath: 'contractors[0].pwdApprovalCode',
                                label: 'works.create.groups.fields.pwdApprovalCode',
                                type: 'text',
                                isRequired:false,
                                isDisabled: false,
                                requiredErrMsg: '',
                                patternErrMsg: '',
                                maxLength: 20,
                                minLength: 1,
                              },
                              {
                                name: 'pwdApprovalValidTill',
                                jsonPath: 'contractors[0].pwdApprovalValidTill',
                                label: 'works.create.groups.fields.pwdApprovalValidTill',
                                type: 'datePicker',
                                isRequired:false,
                                isDisabled: false,
                                requiredErrMsg: '',
                                requiredErrMsg: 'Please enter valid date',
                                maxLength: 50,
                                minLength: 1,
                              },
                              {
                                name: 'contractorClass',
                                jsonPath: 'contractors[0].contractorClass.class',
                                label: 'works.create.groups.fields.contractorClass',
                                type: 'singleValueList',
                                isRequired:true,
                                isDisabled: false,
                                requiredErrMsg: '',
                                patternErrMsg: '',
                                maxLength: 50,
                                minLength: 1,
                                url:'/egov-mdms-service/v1/_get?tenantId=default&masterName=ContractorClass&moduleName=works|$..class|$..description',
                              },
                              {
                                name: 'epfRegistrationNumber',
                                jsonPath: 'contractors[0].epfRegistrationNumber',
                                label: 'works.create.groups.fields.epfRegistrationNumber',
                                type: 'text',
                                isRequired:false,
                                isDisabled: false,
                                requiredErrMsg: '',
                                patternErrMsg: '',
                                maxLength: 50,
                                minLength: 1,
                              },
                              {
                                name:'accountCodeGlcode',
                                jsonPath:'contractors[0].accountCode.glcode',
                                label:'works.create.groups.fields.accountCode.glcode',
                                type:'text',
                                isRequired:false,
                                isDisabled:false,
                                requiredErrMsg: '',
                                patternErrMsg:'',
                                maxLength:128,
                                minLength:5,

                              },
                              {
                                name:'accountCode',
                                jsonPath:'contractors[0].accountCode.name',
                                label:'works.create.groups.fields.accountCode.name',
                                type:'autoCompelete',
                                isRequired:false,
                                isDisabled:false,
                                requiredErrMsg:'',
                                patternErrMsg:'',
                                maxLength:256,
                                minLength:3,
                              },
                              {
                                name: 'pmc',
                                jsonPath: 'contractors[0].pmc',
                                label: 'works.create.groups.fields.pmc',
                                type: 'checkbox',
                                isRequired:false,
                                isDisabled: false,
                                requiredErrMsg: '',
                                patternErrMsg: '',
                                maxLength:'',
                                minLength:'',
                                defaultValue:false,
                              },
                              {
                                name: 'status',
                                jsonPath: 'contractors[0].status',
                                label: '',
                                type: 'hidden',
                                isRequired:true,
                                isDisabled: false,
                                requiredErrMsg: '',
                                patternErrMsg: '',
                                maxLength:'',
                                minLength:'',
                                defaultValue:"Active",
                              }
                          ]
                    }

                ]
      },
    'works.view':{
      numCols: 12/2,
      useTimestamp: true,
      title: 'works.create.page.title.createContrator',
      url: '/works-masters/v1/contractors/_search?ids={id}',
      tenantIdRequired: true,
      objectName: 'contractors',
      groups: [
                {
                  label: '',
                  name: 'Create Contractor',
                  stepIndex: 0,
                  fields: [
                    {
                      name: 'name',
                      jsonPath:'contractors[0].name',
                      label: 'works.create.groups.fields.name',
                      type: 'text',
                      isRequired:true,
                      isDisabled: false,
                      requiredErrMsg: '',
                      patternErrMsg: '',
                      maxLength:100,
                      minLength: 1,
                    },
                    {
                      name: 'name',
                      jsonPath:'contractors[0].localName',
                      label: 'works.create.groups.fields.localName',
                      type: 'text',
                      isRequired:false,
                      isDisabled: false,
                      requiredErrMsg: '',
                      patternErrMsg: '',
                      maxLength:100,
                      minLength: 1,
                      default:'null'
                    },
                    {
                      name: 'contactPerson',
                      jsonPath:'contractors[0].contactPerson',
                      label: 'works.create.groups.fields.contactPerson',
                      type: 'text',
                      isRequired:false,
                      isDisabled: false,
                      requiredErrMsg: '',
                      patternErrMsg: '',
                      maxLength:100,
                      minLength: 1,
                    },
                    {
                      name: 'contractorCode',
                      jsonPath:'contractors[0].code',
                      label: 'works.create.groups.fields.code',
                      type: 'text',
                      isRequired:true,
                      isDisabled: false,
                      requiredErrMsg: '',
                      patternErrMsg: '',
                      maxLength: 100,
                      minLength:1,
                    },
                    {
                      name: 'correspondenceAddress',
                      jsonPath: 'contractors[0].correspondenceAddress',
                      label: 'works.create.groups.fields.correspondenceAddress',
                      type: 'text',
                      isRequired:true,
                      isDisabled: false,
                      requiredErrMsg: 'Please enter valid correspondence address',
                      patternErrMsg: '',
                      maxLength:512,
                      minLength: 1,
                    },
                    {
                      name: 'paymentAddress',
                      jsonPath: 'contractors[0].paymentAddress',
                      label: 'works.create.groups.fields.paymentAddress',
                      type: 'text',
                      isRequired:false,
                      isDisabled: false,
                      requiredErrMsg: '',
                      patternErrMsg: '',
                      maxLength:512,
                      minLength: 1,
                    },
                    {
                      name: 'narration',
                      jsonPath: 'contractors[0].narration',
                      label: 'Narration',
                      type: 'text',
                      isRequired:false,
                      isDisabled:false,
                      requiredErrMsg: '',
                      patternErrMsg: '',
                      maxLength:1024,
                      minLength: 1,
                    },
                    {
                      name: 'email',
                      jsonPath: 'contractors[0].email',
                      label: 'works.create.groups.fields.email',
                      type: 'text',
                      isRequired:false,
                      isDisabled: false,
                      requiredErrMsg: '',
                      patternErrMsg: '',
                      maxLength:100,
                      minLength: 1,
                    },
                    {
                      name: 'panNumber',
                      jsonPath: 'contractors[0].panNumber',
                      label: 'works.create.groups.fields.panNumber',
                      type: 'text',
                      isRequired:false,
                      isDisabled: false,
                      requiredErrMsg: '',
                      patternErrMsg:'',
                      maxLength: 10,
                      minLength: 1,
                    },
                    {
                      name: 'mobileNumber',
                      jsonPath: 'contractors[0].mobileNumber',
                      label: 'works.create.groups.fields.mobileNumber',
                      type: 'text',
                      isRequired:true,
                      isDisabled: false,
                      requiredErrMsg: 'Please enter valid Mobile number',
                      patternErrMsg: '',
                      minLength:10,
                      minLength:10,
                    },
                    {
                      name: 'tinNumber',
                      jsonPath: 'contractors[0].tinNumber',
                      label: 'works.create.groups.fields.tinNumber',
                      type: 'text',
                      isRequired:false,
                      isDisabled: false,
                      requiredErrMsg: '',
                      patternErrMsg: '',
                      maxLength:12,
                      minLength: 1,
                    },
                    {
                      name: '',
                      jsonPath: '',
                      label: '',
                      type: 'hidden',
                      isRequired:false,
                      isDisabled: false,
                      requiredErrMsg: '',
                      patternErrMsg: '',
                      maxLength:12,
                      minLength: 1,
                    },
                    {
                      name: 'bank',
                      jsonPath: 'contractors[0].bank.name',
                      label: 'works.create.groups.fields.bank',
                      type: 'singleValueList',
                      isRequired:true,
                      isDisabled: false,
                      requiredErrMsg: 'Bank name is invalid',
                      patternErrMsg: '',
                      maxLength: 50,
                      minLength: 1,
                      url:'/egov-mdms-service/v1/_get?&moduleName=egf-master&masterName=Bank|$..Bank.*.code|$..Bank.*.name'
                    },
                    {
                      name: 'ifscCode',
                      jsonPath: 'contractors[0].ifscCode',
                      label: 'works.create.groups.fields.ifscCode',
                      type: 'text',
                      isRequired:false,
                      isDisabled: false,
                      requiredErrMsg: '',
                      patternErrMsg: '',
                      maxLength: 50,
                      minLength: 1,
                    },
                    {
                      name: 'bankAccountNumber',
                      jsonPath: 'contractors[0].bankAccountNumber',
                      label: 'works.create.groups.fields.bankAccountNumber',
                      type: 'text',
                      isRequired:false,
                      isDisabled: false,
                      requiredErrMsg: '',
                      patternErrMsg: '',
                      maxLength:20,
                      minLength: 1,
                    },
                    {
                      name: 'exemptedFrom',
                      jsonPath: 'contractors[0].exemptedFrom',
                      label: 'works.create.groups.fields.exemptedFrom',
                      type: 'singleValueList',
                      isRequired:false,
                      isDisabled: false,
                      requiredErrMsg: '',
                      patternErrMsg: '',
                      maxLength: 50,
                      minLength: 1,
                      url:'',
                      defaultValue: [
                        {
                          key: 'INCOME_TAX',
                          value: 'INCOME TAX',
                        },
                        {
                          key: 'EARNEST_MONEY_DEPOSIT',
                          value: 'EARNEST MONEY DEPOSIT',
                        },
                        {
                          key: 'VAT',
                          value: 'VAT',
                        },
                      ],
                    },
                    {
                      name: 'pwdApprovalCode',
                      jsonPath: 'contractors[0].pwdApprovalCode',
                      label: 'works.create.groups.fields.pwdApprovalCode',
                      type: 'text',
                      isRequired:false,
                      isDisabled: false,
                      requiredErrMsg: '',
                      patternErrMsg: '',
                      maxLength: 20,
                      minLength: 1,
                    },
                    {
                      name: 'pwdApprovalValidTill',
                      jsonPath: 'contractors[0].pwdApprovalValidTill',
                      label: 'works.create.groups.fields.pwdApprovalValidTill',
                      type: 'datePicker',
                      isRequired:false,
                      isDisabled: false,
                      requiredErrMsg: '',
                      requiredErrMsg: 'Please enter valid date',
                      maxLength: 50,
                      minLength: 1,
                    },
                    {
                      name: 'pwdApprovalValidTill',
                      jsonPath: 'contractors[0].pwdApprovalValidTill',
                      label: 'works.create.groups.fields.pwdApprovalValidTill',
                      type: 'datePicker',
                      isRequired:false,
                      isDisabled: false,
                      requiredErrMsg: '',
                      requiredErrMsg: 'Please enter valid date',
                      maxLength: 50,
                      minLength: 1,
                    },
                    {
                      name: 'contractorClass',
                      jsonPath: 'contractors[0].contractorClass.class',
                      label: 'works.create.groups.fields.contractorClass',
                      type: 'singleValueList',
                      isRequired:false,
                      isDisabled: false,
                      requiredErrMsg: '',
                      patternErrMsg: '',
                      maxLength: 50,
                      minLength: 1,
                      url:'/works-masters/v1/contractors/_get?tenantId=default&masterName=ContractorClass&moduleName=works|$..description|$..class',
                    },
                    {
                      name: 'epfRegistrationNumber',
                      jsonPath: 'contractors[0].epfRegistrationNumber',
                      label: 'works.create.groups.fields.epfRegistrationNumber',
                      type: 'text',
                      isRequired:false,
                      isDisabled: false,
                      requiredErrMsg: '',
                      patternErrMsg: '',
                      maxLength: 50,
                      minLength: 1,
                    },
                    {
                      name:'accountCode',
                      jsonPath:'contractors[0].accountCode.name',
                      label:'works.create.groups.fields.accountCode.name',
                      type:'text',
                      isRequired:false,
                      isDisabled:false,
                      requiredErrMsg:'',
                      patternErrMsg:'',
                      maxLength:128,
                      minLength:5,
                    },
                    {
                      name:'accountCode',
                      jsonPath:'contractors[0].accountCode.accountCodePurpose.description',
                      label:'',
                      type:'autoCompelete',
                      isRequired:false,
                      isDisabled:false,
                      requiredErrMsg:'',
                      patternErrMsg:'',
                      minLength: 1,
                    },
                    {
                      name: 'pmc',
                      jsonPath: 'contractors[0].pmc',
                      label: 'works.create.groups.fields.pmc',
                      type: 'checkbox',
                      isRequired:false,
                      isDisabled: false,
                      requiredErrMsg: '',
                      patternErrMsg: '',
                      maxLength:'',
                      minLength:'',
                      defaultValue:false,
                    },
                  ]
              }
          ]
    },
    'works.update':{
      numCols: 12/2,
      useTimestamp: true,
      title: 'works.update.page.title.createContrator',
      url: '/works-masters/v1/contractors/_update',
      searchUrl:'/works-masters/v1/contractors/_search?ids={id}',
      tenantIdRequired: true,
      objectName: 'contractors',
      groups:[
              {
                name:'updateContractor',
                fields: [
                          {
                            name: 'name',
                            jsonPath:'contractors[0].name',
                            label: 'works.create.groups.fields.name',
                            type: 'text',
                            isRequired:true,
                            isDisabled: false,
                            requiredErrMsg: '',
                            patternErrMsg: '',
                            maxLength:100,
                            minLength: 1,
                          },
                          {
                            name: 'name',
                            jsonPath:'contractors[0].localName',
                            label: 'works.create.groups.fields.localName',
                            type: 'text',
                            isRequired:false,
                            isDisabled: false,
                            requiredErrMsg: '',
                            patternErrMsg: '',
                            maxLength:100,
                            minLength: 1,
                            default:'null'
                          },
                          {
                            name: 'contactPerson',
                            jsonPath:'contractors[0].contactPerson',
                            label: 'works.create.groups.fields.contactPerson',
                            type: 'text',
                            isRequired:false,
                            isDisabled: false,
                            requiredErrMsg: '',
                            patternErrMsg: '',
                            maxLength:100,
                            minLength: 1,
                          },
                          {
                            name: 'contractorCode',
                            jsonPath:'contractors[0].code',
                            label: 'works.create.groups.fields.code',
                            type: 'text',
                            isRequired:true,
                            isDisabled: false,
                            requiredErrMsg: '',
                            patternErrMsg: '',
                            maxLength: 100,
                            minLength:1,
                          },
                          {
                            name: 'correspondenceAddress',
                            jsonPath: 'contractors[0].correspondenceAddress',
                            label: 'works.create.groups.fields.correspondenceAddress',
                            type: 'text',
                            isRequired:true,
                            isDisabled: false,
                            requiredErrMsg: 'Please enter valid correspondence address',
                            patternErrMsg: '',
                            maxLength:512,
                            minLength: 1,
                          },
                          {
                            name: 'paymentAddress',
                            jsonPath: 'contractors[0].paymentAddress',
                            label: 'works.create.groups.fields.paymentAddress',
                            type: 'text',
                            isRequired:false,
                            isDisabled: false,
                            requiredErrMsg: '',
                            patternErrMsg: '',
                            maxLength:512,
                            minLength: 1,
                          },
                          {
                            name: 'narration',
                            jsonPath: 'contractors[0].narration',
                            label: 'Narration',
                            type: 'text',
                            isRequired:false,
                            isDisabled:false,
                            requiredErrMsg: '',
                            patternErrMsg: '',
                            maxLength:1024,
                            minLength: 1,
                          },
                          {
                            name: 'email',
                            jsonPath: 'contractors[0].email',
                            label: 'works.create.groups.fields.email',
                            type: 'text',
                            isRequired:false,
                            isDisabled: false,
                            requiredErrMsg: '',
                            patternErrMsg: '',
                            maxLength:100,
                            minLength: 1,
                          },
                          {
                            name: 'panNumber',
                            jsonPath: 'contractors[0].panNumber',
                            label: 'works.create.groups.fields.panNumber',
                            type: 'text',
                            isRequired:false,
                            isDisabled: false,
                            requiredErrMsg: '',
                            patternErrMsg:'',
                            maxLength: 10,
                            minLength: 1,
                          },
                          {
                            name: 'mobileNumber',
                            jsonPath: 'contractors[0].mobileNumber',
                            label: 'works.create.groups.fields.mobileNumber',
                            type: 'text',
                            isRequired:true,
                            isDisabled: false,
                            requiredErrMsg: 'Please enter valid Mobile number',
                            patternErrMsg: '',
                            minLength:10,
                            minLength:10,
                          },
                          {
                            name: 'tinNumber',
                            jsonPath: 'contractors[0].tinNumber',
                            label: 'works.create.groups.fields.tinNumber',
                            type: 'text',
                            isRequired:false,
                            isDisabled: false,
                            requiredErrMsg: '',
                            patternErrMsg: '',
                            maxLength:12,
                            minLength: 1,
                          },
                          {
                            name: '',
                            jsonPath: '',
                            label: '',
                            type: 'hidden',
                            isRequired:false,
                            isDisabled: false,
                            requiredErrMsg: '',
                            patternErrMsg: '',
                            maxLength:12,
                            minLength: 1,
                          },
                          {
                            name: 'bank',
                            jsonPath: 'contractors[0].bank.name',
                            label: 'works.create.groups.fields.bank',
                            type: 'singleValueList',
                            isRequired:true,
                            isDisabled: false,
                            requiredErrMsg: 'Bank name is invalid',
                            patternErrMsg: '',
                            maxLength: 50,
                            minLength: 1,
                            url:'/egov-mdms-service/v1/_get?&moduleName=egf-master&masterName=Bank|$..Bank.*.code|$..Bank.*.name'
                          },
                          {
                            name: 'ifscCode',
                            jsonPath: 'contractors[0].ifscCode',
                            label: 'works.create.groups.fields.ifscCode',
                            type: 'text',
                            isRequired:false,
                            isDisabled: false,
                            requiredErrMsg: '',
                            patternErrMsg: '',
                            maxLength: 50,
                            minLength: 1,
                          },
                          {
                            name: 'bankAccountNumber',
                            jsonPath: 'contractors[0].bankAccountNumber',
                            label: 'works.create.groups.fields.bankAccountNumber',
                            type: 'text',
                            isRequired:false,
                            isDisabled: false,
                            requiredErrMsg: '',
                            patternErrMsg: '',
                            maxLength:20,
                            minLength: 1,
                          },
                          {
                            name: 'exemptedFrom',
                            jsonPath: 'contractors[0].exemptedFrom',
                            label: 'works.create.groups.fields.exemptedFrom',
                            type: 'singleValueList',
                            isRequired:false,
                            isDisabled: false,
                            requiredErrMsg: '',
                            patternErrMsg: '',
                            maxLength: 50,
                            minLength: 1,
                            url:'',
                            defaultValue: [
                              {
                                key: 'INCOME_TAX',
                                value: 'INCOME TAX',
                              },
                              {
                                key: 'EARNEST_MONEY_DEPOSIT',
                                value: 'EARNEST MONEY DEPOSIT',
                              },
                              {
                                key: 'VAT',
                                value: 'VAT',
                              },
                            ],
                          },
                          {
                            name: 'pwdApprovalCode',
                            jsonPath: 'contractors[0].pwdApprovalCode',
                            label: 'works.create.groups.fields.pwdApprovalCode',
                            type: 'text',
                            isRequired:false,
                            isDisabled: false,
                            requiredErrMsg: '',
                            patternErrMsg: '',
                            maxLength: 20,
                            minLength: 1,
                          },
                          {
                            name: 'pwdApprovalValidTill',
                            jsonPath: 'contractors[0].pwdApprovalValidTill',
                            label: 'works.create.groups.fields.pwdApprovalValidTill',
                            type: 'datePicker',
                            isRequired:false,
                            isDisabled: false,
                            requiredErrMsg: '',
                            requiredErrMsg: 'Please enter valid date',
                            maxLength: 50,
                            minLength: 1,
                          },
                          {
                            name: 'pwdApprovalValidTill',
                            jsonPath: 'contractors[0].pwdApprovalValidTill',
                            label: 'works.create.groups.fields.pwdApprovalValidTill',
                            type: 'datePicker',
                            isRequired:false,
                            isDisabled: false,
                            requiredErrMsg: '',
                            requiredErrMsg: 'Please enter valid date',
                            maxLength: 50,
                            minLength: 1,
                          },
                          {
                            name: 'contractorClass',
                            jsonPath: 'contractors[0].contractorClass.class',
                            label: 'works.create.groups.fields.contractorClass',
                            type: 'singleValueList',
                            isRequired:false,
                            isDisabled: false,
                            requiredErrMsg: '',
                            patternErrMsg: '',
                            maxLength: 50,
                            minLength: 1,
                            url:'/works-masters/v1/contractors/_get?tenantId=default&masterName=ContractorClass&moduleName=Works|$..description|$..class',
                          },
                          {
                            name: 'epfRegistrationNumber',
                            jsonPath: 'contractors[0].epfRegistrationNumber',
                            label: 'works.create.groups.fields.epfRegistrationNumber',
                            type: 'text',
                            isRequired:false,
                            isDisabled: false,
                            requiredErrMsg: '',
                            patternErrMsg: '',
                            maxLength: 50,
                            minLength: 1,
                          },
                          {
                            name:'accountCode',
                            jsonPath:'contractors[0].accountCode.name',
                            label:'works.create.groups.fields.accountCode.name',
                            type:'text',
                            isRequired:false,
                            isDisabled:false,
                            requiredErrMsg:'',
                            patternErrMsg:'',
                            maxLength:128,
                            minLength:5,
                          },
                          {
                            name:'accountCode',
                            jsonPath:'contractors[0].accountCode.accountCodePurpose.description',
                            label:'',
                            type:'autoCompelete',
                            isRequired:false,
                            isDisabled:false,
                            requiredErrMsg:'',
                            patternErrMsg:'',
                            minLength: 1,
                          },
                          {
                            name: 'pmc',
                            jsonPath: 'contractors[0].pmc',
                            label: 'works.create.groups.fields.pmc',
                            type: 'checkbox',
                            isRequired:false,
                            isDisabled: false,
                            requiredErrMsg: '',
                            patternErrMsg: '',
                            maxLength:'',
                            minLength:'',
                            defaultValue:false,
                          },
                      ]
              }
      ]

    }

}

export default dat;
