var ownerDetails = {
  name: 'ownerDetailsCol',
  version: 'v1',
  level: 2,
  jsonPath: 'Connection.connectionOwners',
  groups: [
    {
      name: 'details',
      multiple: true,
      fields: [
        {
          name: 'NameOfApplicant',
          jsonPath: 'Connection.connectionOwners[0].name',
          label: 'wc.create.groups.applicantDetails.nameOfApplicant',
          pattern: '^([a-zA-Z0-9_-\\s]){3,100}$',
          type: 'text',
          isRequired: true,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'MobileNumber',
          jsonPath: 'Connection.connectionOwners[0].mobileNumber',
          label: 'wc.create.groups.applicantDetails.mobileNumber',
          pattern: '',
          type: 'mobileNumber',
          isRequired: true,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'Email',
          jsonPath: 'Connection.connectionOwners[0].emailId',
          label: 'wc.create.groups.applicantDetails.email',
          pattern: '',
          type: 'email',
          isRequired: true,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
          defaultValue: '',
        },
        {
          name: 'AadharNumber',
          jsonPath: 'Connection.connectionOwners[0].aadhaarNumber',
          label: 'wc.create.groups.applicantDetails.adharNumber',
          pattern: '',
          type: 'aadhar',
          isRequired: true,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'gender',
          jsonPath: 'Connection.connectionOwners[0].gender',
          label: 'employee.Employee.fields.User.gender',
          pattern: '',
          type: 'singleValueList',
          url: '/egov-common-masters/genders/_search?|$.Gender.*|$.Gender.*',
          isRequired: true,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'PrimaryOwner',
          jsonPath: 'Connection.connectionOwners[0].primaryOwner',
          label: 'pt.create.groups.ownerDetails.fields.primaryOwner',
          pattern: '',
          type: 'checkbox',
          isRequired: false,
          defaultValue: true,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
      ],
    },
  ],
};

var addressDetails = {
  name: 'addressDetailsCol',
  version: 'v1',
  level: 2,
  groups: [
    {
      name: 'showDetails',
      multiple: false,
      fields: [
        {
          name: 'AddressNo',
          jsonPath: 'Connection.houseNumber',
          label: 'wc.create.groups.applicantDetails.addressNumber',
          pattern: '^[s.]*([^s.][s.]*){0,16}$',
          type: 'text',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'Address',
          jsonPath: 'Connection.address.addressLine1',
          label: 'wc.create.groups.applicantDetails.address',
          pattern: '^.{3,255}$',
          type: 'text',
          isRequired: true,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'City',
          jsonPath: 'Connection.address.city',
          label: 'employee.Employee.fields.city',
          pattern: '^([a-zA-Z0-9_-\\s]){2,50}$',
          type: 'text',
          isRequired: true,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'PinCode',
          jsonPath: 'Connection.address.pinCode',
          label: 'pt.create.groups.propertyAddress.fields.pin',
          pattern: '',
          type: 'pinCode',
          isRequired: true,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'zoneName',
          jsonPath: 'Connection.connectionLocation.revenueBoundary.code',
          label: 'wc.create.groups.fields.zone',
          pattern: '',
          type: 'singleValueList',
          url: '',
          isRequired: true,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'wardName',
          jsonPath: 'Connection.connectionLocation.adminBoundary.code',
          label: 'wc.create.groups.fields.ward',
          pattern: '',
          type: 'singleValueList',
          url:
            '/egov-location/boundarys/boundariesByBndryTypeNameAndHierarchyTypeName?&boundaryTypeName=WARD&hierarchyTypeName=ADMINISTRATION|$.Boundary.*.code|$.Boundary.*.name',
          isRequired: true,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'Locality',
          jsonPath: 'Connection.connectionLocation.locationBoundary.code',
          label: 'wc.create.groups.applicantDetails.locality',
          pattern: '',
          type: 'singleValueList',
          url:
            '/egov-location/boundarys/boundariesByBndryTypeNameAndHierarchyTypeName?&boundaryTypeName=LOCALITY&hierarchyTypeName=LOCATION|$.Boundary.*.code|$.Boundary.*.name',
          isRequired: true,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'executionDate',
          jsonPath: 'Connection.executionDate',
          label: 'wc.create.groups.applicantDetails.connectionDate',
          maxDate: 'today-2',
          pattern: '',
          type: 'datePicker',
          isRequired: true,
          isDisabled: false,
          requiredErrMsg: 'Should allow Current -2 date',
          patternErrMsg: 'Should allow Current -2 date',
        },
        {
          name: 'ConsumerNo',
          jsonPath: 'Connection.legacyConsumerNumber',
          label: 'wc.create.groups.applicantDetails.consumerNo',
          pattern: '^[s.]*([^s.][s.]*){1,16}$',
          type: 'text',
          isRequired: true,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'ManualConsumerNo',
          jsonPath: 'Connection.manualConsumerNumber',
          label: 'wc.create.groups.applicantDetails.manualConsumerNo',
          pattern: '^[s.]*([^s.][s.]*){1,16}$',
          type: 'text',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
      ],
    },
  ],
};

var meterReading = {
  name: 'MeterReading',
  version: 'v1',
  level: 2,
  jsonPath: 'Connection.meter[0].meterReadings',
  groups: [
    {
      label: 'wc.group.meterReading',
      name: 'MeterReading',
      multiple: false,
      hide: true,
      children: [],
      fields: [
        {
          name: 'Reading1',
          jsonPath: 'Connection.meter[0].meterReadings[0].reading',
          label: 'wc.group.reading1',
          pattern: '^\\d{1,8}$',
          type: 'number',
          isRequired: true,
          isDisabled: false,
          requiredErrMsg: '', //Remove required messages
          patternErrMsg: '',
          depedants: [
            {
              jsonPath: 'Connection.meter[0].meterReadings[0].consumption',
              type: 'textField',
              pattern:
                "`${getVal('Connection.meter[0].meterReadings[0].reading')!='' && getVal('Connection.meter[0].meterReadings[1].reading')!='' ? getVal('Connection.meter[0].meterReadings[1].reading')-getVal('Connection.meter[0].meterReadings[0].reading'):getVal('Connection.meter[0].meterReadings[1].reading')}`",
              rg: '',
              isRequired: false,
              requiredErrMsg: '',
              patternErrMsg: '',
            },
          ],
        },
        {
          name: 'Reading2',
          jsonPath: 'Connection.meter[0].meterReadings[1].reading',
          label: 'wc.group.reading2',
          pattern: '^\\d{1,8}$',
          type: 'number',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '', //Remove required messages
          patternErrMsg: '',
          depedants: [
            {
              jsonPath: 'Connection.meter[0].meterReadings[0].consumption',
              type: 'textField',
              pattern:
                "`${getVal('Connection.meter[0].meterReadings[0].reading')!='' && getVal('Connection.meter[0].meterReadings[1].reading')!='' ? getVal('Connection.meter[0].meterReadings[1].reading')-getVal('Connection.meter[0].meterReadings[0].reading'):getVal('Connection.meter[0].meterReadings[1].reading')}`",
              rg: '',
              isRequired: false,
              requiredErrMsg: '',
              patternErrMsg: '',
            },
            {
              jsonPath: 'Connection.meter[0].meterReadings[1].consumption',
              type: 'number',
              pattern:
                "`${getVal('Connection.meter[0].meterReadings[1].reading')!='' && getVal('Connection.meter[0].meterReadings[2].reading')!='' ? getVal('Connection.meter[0].meterReadings[2].reading')-getVal('Connection.meter[0].meterReadings[1].reading'):getVal('Connection.meter[0].meterReadings[2].reading')}`",
              rg: '',
              isRequired: false,
              requiredErrMsg: '',
              patternErrMsg: '',
            },
          ],
        },
        {
          name: 'Reading3',
          jsonPath: 'Connection.meter[0].meterReadings[2].reading',
          label: 'wc.group.reading3',
          pattern: '^\\d{1,8}$',
          type: 'number',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '', //Remove required messages
          patternErrMsg: '',
          depedants: [
            {
              jsonPath: 'Connection.meter[0].meterReadings[1].consumption',
              type: 'textField',
              pattern:
                "`${getVal('Connection.meter[0].meterReadings[1].reading')!='' && getVal('Connection.meter[0].meterReadings[2].reading')!='' ? getVal('Connection.meter[0].meterReadings[2].reading')-getVal('Connection.meter[0].meterReadings[1].reading'):getVal('Connection.meter[0].meterReadings[2].reading')}`",
              rg: '',
              isRequired: false,
              requiredErrMsg: '',
              patternErrMsg: '',
            },
          ],
        },
        {
          name: 'Reading1Date',
          jsonPath: 'Connection.meter[0].meterReadings[0].readingDate',
          label: 'wc.group.reading1Date',
          pattern: '',
          type: 'datePicker',
          isRequired: true,
          maxDate: 'today',
          isDisabled: false,
          requiredErrMsg: '', //Remove required messages
          patternErrMsg: 'future date does not be allowed',
        },
        {
          name: 'Reading2Date',
          jsonPath: 'Connection.meter[0].meterReadings[1].readingDate',
          label: 'wc.group.reading2Date',
          pattern: '',
          type: 'datePicker',
          isRequired: false,
          isDisabled: false,
          maxDate: 'today',
          requiredErrMsg: '', //Remove required messages
          patternErrMsg: 'future date does not be allowed',
        },
        {
          name: 'Reading3Date',
          jsonPath: 'Connection.meter[0].meterReadings[2].readingDate',
          label: 'wc.group.reading3Date',
          pattern: '',
          type: 'datePicker',
          maxDate: 'today',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '', //Remove required messages
          patternErrMsg: 'future date does not be allowed',
        },
        {
          name: 'FirstMonthConsumption',
          jsonPath: 'Connection.meter[0].meterReadings[0].consumption',
          label: 'wc.group.consumption1',
          pattern: '',
          type: 'number',
          isRequired: false,
          isDisabled: true,
          requiredErrMsg: '', //Remove required messages
          patternErrMsg: '',
        },
        {
          name: 'SecondMonthConsumption',
          jsonPath: 'Connection.meter[0].meterReadings[1].consumption',
          label: 'wc.group.consumption2',
          pattern: '',
          type: 'number',
          isRequired: false,
          isDisabled: true,
          requiredErrMsg: '', //Remove required messages
          patternErrMsg: '',
        },
        {
          name: 'ThirdMonthConsumption',
          jsonPath: 'Connection.meter[0].meterReadings[2].consumption',
          label: 'wc.group.consumption3',
          pattern: '',
          type: 'number',
          isRequired: false,
          isDisabled: true,
          requiredErrMsg: '', //Remove required messages
          patternErrMsg: '',
        },
        {
          name: 'GapCode1',
          jsonPath: 'Connection.meter[0].meterReadings[0].gapCode',
          label: 'wc.create.groups.gapCode1',
          pattern: '',
          type: 'singleValueList',
          url: '/wcms/masters/gapcodes/_search?|$..code|$..name',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'GapCode2',
          jsonPath: 'Connection.meter[0].meterReadings[1].gapCode',
          label: 'wc.create.groups.gapCode2',
          pattern: '',
          type: 'singleValueList',
          url: '/wcms/masters/gapcodes/_search?|$..code|$..name',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'GapCode3',
          jsonPath: 'Connection.meter[0].meterReadings[2].gapCode',
          label: 'wc.create.groups.gapCode3',
          pattern: '',
          type: 'singleValueList',
          url: '/wcms/masters/gapcodes/_search?|$..code|$..name',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'ConsumptionAdjustment1',
          jsonPath: 'Connection.meter[0].meterReadings[0].consumptionAdjusted',
          label: 'wc.group.consumptionAdjustment1',
          pattern: '^\\d{1,8}$',
          type: 'number',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'ConsumptionAdjustment2',
          jsonPath: 'Connection.meter[0].meterReadings[1].consumptionAdjusted',
          label: 'wc.group.consumptionAdjustment2',
          pattern: '^\\d{1,8}$',
          type: 'number',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'ConsumptionAdjustment3',
          jsonPath: 'Connection.meter[0].meterReadings[2].consumptionAdjusted',
          label: 'wc.group.consumptionAdjustment3',
          pattern: '^\\d{1,8}$',
          type: 'number',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'FirstMonthReset',
          jsonPath: 'Connection.meter[0].meterReadings[0].resetFlag',
          label: 'wc.create.groups.connectionDetails.fields.resetFlag1',
          pattern: '',
          type: 'checkbox',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
          defaultValue: false,
        },
        {
          name: 'SecondMonthReset',
          jsonPath: 'Connection.meter[0].meterReadings[1].resetFlag',
          label: 'wc.create.groups.connectionDetails.fields.resetFlag2',
          pattern: '',
          type: 'checkbox',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
          defaultValue: false,
        },
        {
          name: 'ThirdMonthReset',
          jsonPath: 'Connection.meter[0].meterReadings[2].resetFlag',
          label: 'wc.create.groups.connectionDetails.fields.resetFlag3',
          pattern: '',
          type: 'checkbox',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
          defaultValue: false,
        },
      ],
    },
  ],
};

var meterReadingView = {
  name: 'MeterReading',
  version: 'v1',
  level: 2,
  jsonPath: 'Connection.meter[0].meterReadings',
  groups: [
    {
      label: 'wc.group.meterReading',
      name: 'MeterReading',
      multiple: false,
      hide: false,
      children: [],
      fields: [
        {
          name: 'Reading1',
          jsonPath: 'Connection[0].meter[0].meterReadings[0].reading',
          label: 'wc.group.reading1',
          pattern: '',
          type: 'number',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '', //Remove required messages
          patternErrMsg: '',
          depedants: [
            {
              jsonPath: 'Connection[0].meter[0].meterReadings[0].consumption',
              type: 'number',
              pattern:
                "`${getVal('Connection.meter[0].meterReadings[0].reading')!='' && getVal('Connection.meter[0].meterReadings[1].reading')!='' ? getVal('Connection.meter[0].meterReadings[1].reading')-getVal('Connection.meter[0].meterReadings[0].reading'):getVal('Connection.meter[0].meterReadings[1].reading')}`",
              rg: '',
              isRequired: false,
              requiredErrMsg: '',
              patternErrMsg: '',
            },
          ],
        },
        {
          name: 'Reading2',
          jsonPath: 'Connection[0].meter[0].meterReadings[1].reading',
          label: 'wc.group.reading2',
          pattern: '',
          type: 'number',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '', //Remove required messages
          patternErrMsg: '',
          depedants: [
            {
              jsonPath: 'Connection[0].meter[0].meterReadings[0].consumption',
              type: 'textField',
              pattern:
                "`${getVal('Connection.meter[0].meterReadings[0].reading')!='' && getVal('Connection.meter[0].meterReadings[1].reading')!='' ? getVal('Connection.meter[0].meterReadings[1].reading') - getVal('Connection.meter[0].meterReadings[0].reading'):getVal('Connection.meter[0].meterReadings[1].reading')}`",
              rg: '',
              isRequired: false,
              requiredErrMsg: '',
              patternErrMsg: '',
            },
            {
              jsonPath: 'Connection[0].meter[0].meterReadings[1].consumption',
              type: 'textField',
              pattern:
                "`${getVal('Connection.meter[0].meterReadings[2].reading')!='' && getVal('Connection.meter[0].meterReadings[1].reading')!='' ? getVal('Connection.meter[0].meterReadings[2].reading') - getVal('Connection.meter[0].meterReadings[1].reading') : getVal('Connection.meter[0].meterReadings[2].reading')}`",
              rg: '',
              isRequired: false,
              requiredErrMsg: '',
              patternErrMsg: '',
            },
          ],
        },
        {
          name: 'Reading3',
          jsonPath: 'Connection[0].meter[0].meterReadings[2].reading',
          label: 'wc.group.reading3',
          pattern: '',
          type: 'number',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '', //Remove required messages
          patternErrMsg: '',
          depedants: [
            {
              jsonPath: 'Connection[0].meter[0].meterReadings[1].consumption',
              type: 'number',
              pattern:
                "`${getVal('Connection.meter[0].meterReadings[2].reading')!='' && getVal('Connection.meter[0].meterReadings[1].reading')!='' ? getVal('Connection.meter[0].meterReadings[2].reading')- getVal('Connection.meter[0].meterReadings[1].reading') : getVal('Connection.meter[0].meterReadings[2].reading')}`",
              rg: '',
              isRequired: false,
              requiredErrMsg: '',
              patternErrMsg: '',
            },
          ],
        },
        {
          name: 'Reading1Date',
          jsonPath: 'Connection[0].meter[0].meterReadings[0].readingDate',
          label: 'wc.group.reading1Date',
          pattern: '',
          type: 'datePicker',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '', //Remove required messages
          patternErrMsg: '',
        },
        {
          name: 'Reading2Date',
          jsonPath: 'Connection[0].meter[0].meterReadings[1].readingDate',
          label: 'wc.group.reading2Date',
          pattern: '',
          type: 'datePicker',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '', //Remove required messages
          patternErrMsg: '',
        },
        {
          name: 'Reading3Date',
          jsonPath: 'Connection[0].meter[0].meterReadings[2].readingDate',
          label: 'wc.group.reading3Date',
          pattern: '',
          type: 'datePicker',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '', //Remove required messages
          patternErrMsg: '',
        },
        {
          name: 'FirstMonthConsumption',
          jsonPath: 'Connection[0].meter[0].meterReadings[0].consumption',
          label: 'wc.group.consumption1',
          pattern: '',
          type: 'number',
          isRequired: false,
          isDisabled: true,
          requiredErrMsg: '', //Remove required messages
          patternErrMsg: '',
        },
        {
          name: 'SecondMonthConsumption',
          jsonPath: 'Connection[0].meter[0].meterReadings[1].consumption',
          label: 'wc.group.consumption2',
          pattern: '',
          type: 'number',
          isRequired: false,
          isDisabled: true,
          requiredErrMsg: '', //Remove required messages
          patternErrMsg: '',
        },
        {
          name: 'ThirdMonthConsumption',
          jsonPath: 'Connection[0].meter[0].meterReadings[2].consumption',
          label: 'wc.group.consumption3',
          pattern: '',
          type: 'number',
          isRequired: false,
          isDisabled: true,
          requiredErrMsg: '', //Remove required messages
          patternErrMsg: '',
        },
        {
          name: 'GapCode1',
          jsonPath: 'Connection[0].meter[0].meterReadings[0].gapCode',
          label: 'wc.create.groups.gapCode1',
          pattern: '',
          type: 'singleValueList',
          url: '/wcms/masters/gapcodes/_search?|$..code|$..name',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'GapCode2',
          jsonPath: 'Connection[0].meter[0].meterReadings[1].gapCode',
          label: 'wc.create.groups.gapCode2',
          pattern: '',
          type: 'singleValueList',
          url: '/wcms/masters/gapcodes/_search?|$..code|$..name',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'GapCode3',
          jsonPath: 'Connection[0].meter[0].meterReadings[2].gapCode',
          label: 'wc.create.groups.gapCode3',
          pattern: '',
          type: 'singleValueList',
          url: '/wcms/masters/gapcodes/_search?|$..code|$..name',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'ConsumptionAdjustment1',
          jsonPath: 'Connection[0].meter[0].meterReadings[0].consumptionAdjusted',
          label: 'wc.group.consumptionAdjustment1',
          pattern: '^\\d{1,8}$',
          type: 'number',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'ConsumptionAdjustment2',
          jsonPath: 'Connection[0].meter[0].meterReadings[1].consumptionAdjusted',
          label: 'wc.group.consumptionAdjustment2',
          pattern: '^\\d{1,8}$',
          type: 'number',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'ConsumptionAdjustment3',
          jsonPath: 'Connection[0].meter[0].meterReadings[2].consumptionAdjusted',
          label: 'wc.group.consumptionAdjustment3',
          pattern: '^\\d{1,8}$',
          type: 'number',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
        },
        {
          name: 'FirstMonthReset',
          jsonPath: 'Connection[0].meter[0].meterReadings[0].resetFlag',
          label: 'wc.create.groups.connectionDetails.fields.resetFlag1',
          pattern: '',
          type: 'checkbox',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
          defaultValue: false,
        },
        {
          name: 'SecondMonthReset',
          jsonPath: 'Connection[0].meter[0].meterReadings[1].resetFlag',
          label: 'wc.create.groups.connectionDetails.fields.resetFlag2',
          pattern: '',
          type: 'checkbox',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
          defaultValue: false,
        },
        {
          name: 'ThirdMonthReset',
          jsonPath: 'Connection[0].meter[0].meterReadings[2].resetFlag',
          label: 'wc.create.groups.connectionDetails.fields.resetFlag3',
          pattern: '',
          type: 'checkbox',
          isRequired: false,
          isDisabled: false,
          requiredErrMsg: '',
          patternErrMsg: '',
          defaultValue: false,
        },
      ],
    },
  ],
};

var dat = {
  'wc.create': {
    numCols: 12 / 3,
    version: 'v1',
    url: '/wcms-connection/connection/_create',
    idJsonPath: 'Connection[0].consumerNumber',
    ackUrl: '/legacy/view',
    useTimestamp: true,
    tenantIdRequired: true, //Instead of boolean value give json path
    objectName: 'Connection',
    level: 0,
    groups: [
      {
        label: 'wc.create.groups.applicationParticular.title', //Cut short labels by taking initial path from parent
        name: 'applicationParticular', //Follow Title case pattern
        children: [],
        multiple: false,
        fields: [
          {
            name: 'applicationType',
            jsonPath: 'Connection.applicationType',
            label: '',
            pattern: '',
            type: 'radio',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            values: [
              { label: 'wc.create.primaryConnection', value: 'NEWCONNECTION' },
              {
                label: 'wc.create.additionalConnection',
                value: 'ADDITIONCONNECTION',
              },
            ],
            defaultValue: 'NEWCONNECTION',
          },
          {
            name: 'With Property',
            jsonPath: 'Connection.withProperty',
            label: '',
            pattern: '',
            type: 'radio',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            values: [{ label: 'wc.group.withProperty', value: true }, { label: 'wc.group.withoutProperty', value: false }],
            defaultValue: false,
            showHideFields: [
              {
                ifValue: false,
                hide: [
                  {
                    name: 'applicantDetailsWithProp',
                    isGroup: true,
                    isField: false,
                  },
                ],
                show: [
                  {
                    name: 'details',
                    isGroup: true,
                    isField: false,
                  },
                  {
                    name: 'showDetails',
                    isGroup: true,
                    isField: false,
                  },
                  {
                    name: 'applicantDetailsWithoutProp',
                    isGroup: true,
                    isField: false,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        label: 'wc.create.groups.applicantDetails.title', //Cut short labels by taking initial path from parent
        name: 'applicantDetailsWithoutProp', //Follow Title case pattern
        children: [ownerDetails, addressDetails],
        multiple: false,
        fields: [{}],
      },
      {
        label: 'wc.create.groups.applicantDetails.title', //Cut short labels by taking initial path from parent
        name: 'applicantDetailsWithProp', //Follow Title case pattern
        children: [],
        multiple: false,
        hide: true,
        fields: [
          {
            name: 'AssessmentNumber',
            jsonPath: 'Connection.property.propertyIdentifier',
            label: 'wc.create.groups.applicantDetails.propertyIdentifier',
            pattern: '',
            type: 'textSearch',
            isRequired: true,
            isDisabled: false,
            autoCompleteDependancy: {
              autoCompleteUrl: '/pt-property/properties/_search?upicNumber={value}&tenantId=default',
              autoFillFields: {
                'Connection.property.mobileNumber': 'properties[0].owners[0].mobileNumber',
                'Connection.property.nameOfApplicant': 'properties[0].owners[0].name',
                'Connection.property.email': 'properties[0].owners[0].emailId',
                'Connection.property.aadhaarNumber': 'properties[0].owners[0].aadhaarNumber',
                'Connection.property.pinCode': 'properties[0].address.pincode',
                'Connection.property.noOfFloors': 'properties[0].propertyDetail.noOfFloors',
                'Connection.property.locality': 'properties[0].boundary.locationBoundary.code',
                'Connection.property.zone': 'properties[0].boundary.revenueBoundary.code',
                'Connection.property.ward': 'properties[0].boundary.adminBoundary.code',
                'Connection.property.address': 'properties[0].address.addressLine1',
                'Connection.property.property': 'properties[0].propertyDetail.propertyType',
              },
            },
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'NameOfApplicant',
            jsonPath: 'Connection.property.nameOfApplicant',
            label: 'wc.create.groups.applicantDetails.nameOfApplicant',
            pattern: '^[s.]*([^s.][s.]*){0,100}$',
            type: 'text',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'MobileNumber',
            jsonPath: 'Connection.property.mobileNumber',
            label: 'wc.create.groups.applicantDetails.mobileNumber',
            pattern: '',
            type: 'mobileNumber',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'Email',
            jsonPath: 'Connection.property.email',
            label: 'wc.create.groups.applicantDetails.email',
            pattern: '',
            type: 'email',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
            isHidden: false,
            defaultValue: '',
          },
          {
            name: 'AadharNumber',
            jsonPath: 'Connection.property.adharNumber',
            label: 'wc.create.groups.applicantDetails.adharNumber',
            pattern: '',
            type: 'aadhar',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'Address',
            jsonPath: 'Connection.property.address',
            label: 'wc.create.groups.applicantDetails.address',
            pattern: '^[s.]*([^s.][s.]*){0,250}$',
            type: 'text',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'PinCode',
            jsonPath: 'Connection.property.pinCode',
            label: 'pt.create.groups.propertyAddress.fields.pin',
            pattern: '',
            type: 'pinCode',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'Zone',
            jsonPath: 'Connection.property.zone',
            label: 'wc.create.groups.applicantDetails.zone',
            pattern: '',
            url: '',
            type: 'singleValueList',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'Locality',
            jsonPath: 'Connection.property.locality',
            label: 'wc.create.groups.applicantDetails.locality',
            pattern: '',
            type: 'singleValueList',
            url:
              '/egov-location/boundarys/boundariesByBndryTypeNameAndHierarchyTypeName?&boundaryTypeName=LOCALITY&hierarchyTypeName=LOCATION|$.Boundary.*.code|$.Boundary.*.name',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'noOfFloors',
            jsonPath: 'Connection.property.noOfFloors',
            label: 'wc.create.groups.applicantDetails.noOfFloors',
            pattern: '',
            type: 'number',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'propertyTaxDue',
            jsonPath: 'Connection.property.propertyTaxDue',
            label: 'wc.create.groups.applicantDetails.propertyTaxDue',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'consumerNo',
            jsonPath: 'Connection.legacyConsumerNumber',
            label: 'wc.create.groups.applicantDetails.consumerNo',
            pattern: '^[s.]*([^s.][s.]*){1,16}$',
            type: 'text',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'ManualConsumerNo',
            jsonPath: 'Connection.manualConsumerNumber',
            label: 'wc.create.groups.applicantDetails.manualConsumerNo',
            pattern: '^[s.]*([^s.][s.]*){1,16}$',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'executionDate',
            jsonPath: 'Connection.executionDate',
            label: 'wc.create.groups.applicantDetails.connectionDate',
            maxDate: 'today-2',
            pattern: '',
            type: 'datePicker',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: 'Should allow Current -2 date',
            patternErrMsg: 'Should allow Current -2 date',
          },
        ],
      },
      {
        label: 'wc.create.groups.connectionDetails.title',
        name: 'connectionDetails',
        multiple: false,
        fields: [
          // {
          //   "name": "CategoryType",
          //   "jsonPath": "Connection.categoryType",
          //   "label": "wc.create.groups.connectionDetails.categoryType",
          //   "pattern": "",
          //   "type": "singleValueList",
          //   "isRequired": true,
          //   "isDisabled": false,
          //   "requiredErrMsg": "",
          //   "patternErrMsg": "",
          // 	"defaultValue": [],
          // 	"url":"/wcms/masters/categorytype/_search?|$..name|$..name"
          // },
          {
            name: 'UsageType',
            jsonPath: 'Connection.usageType',
            label: 'wc.create.groups.connectionDetails.usageType',
            pattern: '',
            type: 'singleValueList',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            defaultValue: [],
            url: '/wcms/masters/usagetypes/_search?active=true|$..code|$..name',
            depedants: [
              {
                jsonPath: 'Connection.subUsageType',
                type: 'dropDown',
                pattern: '/wcms/masters/usagetypes/_search?&parent={Connection.usageType}&isSubUsageType=true|$..code|$..name',
              },
            ],
          },
          {
            name: 'subUsageType',
            jsonPath: 'Connection.subUsageType',
            label: 'wc.create.groups.connectionDetails.subUsageType',
            pattern: '',
            type: 'singleValueList',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            defaultValue: [],
          },
          {
            name: 'hscPipeSizeType',
            jsonPath: 'Connection.hscPipeSizeType',
            label: 'wc.create.groups.connectionDetails.hscPipeSizeType',
            pattern: '',
            type: 'singleValueList',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            defaultValue: [],
            url: '/wcms/masters/pipesizes/_search?|$..sizeInMilimeter|$..sizeInInch',
          },
          {
            name: 'billingType',
            jsonPath: 'Connection.billingType',
            label: 'wc.create.groups.connectionDetails.billingType',
            pattern: '',
            type: 'singleValueList',
            isRequired: true,
            isDisabled: false,
            url: '/wcms-connection/connection/_getbillingtypes?|$..key|$..object',
            requiredErrMsg: '',
            patternErrMsg: '',
            showHideFields: [
              {
                ifValue: 'METERED',
                hide: [
                  {
                    name: 'description',
                    isGroup: false,
                    isField: true,
                  },
                ],
                show: [
                  {
                    name: 'Metered',
                    isGroup: true,
                    isField: false,
                  },
                  {
                    name: 'MeterReading',
                    isGroup: true,
                    isField: false,
                  },
                ],
              },
            ],
          },
          {
            name: 'ConnectionType',
            jsonPath: 'Connection.connectionType',
            label: 'wc.create.groups.connectionDetails.connectionType',
            pattern: '',
            type: 'singleValueList',
            isRequired: true,
            isDisabled: false,
            url: '/wcms-connection/connection/_getconnectiontypes?|$..key|$..object',
            requiredErrMsg: '',
            patternErrMsg: '',
            showHideFields: [
              {
                ifValue: 'TEMPORARY',
                show: [
                  {
                    name: 'fromDate',
                    isGroup: false,
                    isField: true,
                  },
                  {
                    name: 'toDate',
                    isGroup: false,
                    isField: true,
                  },
                ],
                hide: [],
              },
            ],
          },
          {
            name: 'SourceType',
            jsonPath: 'Connection.sourceType',
            label: 'wc.create.groups.connectionDetails.sourceType',
            pattern: '',
            type: 'singleValueList',
            isRequired: true,
            isDisabled: false,
            url: '/wcms/masters/sourcetypes/_search?|$..name|$..name',
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'supplyType',
            jsonPath: 'Connection.supplyType',
            label: 'wc.create.groups.connectionDetails.supplyType',
            isHidden: true,
            pattern: '',
            type: 'text',
            isRequired: true,
            isDisabled: false,
            // "url": "/wcms/masters/supplytype/_search?|$..name|$..name",
            requiredErrMsg: '',
            defaultValue: 'Semi Bulk Type',
            patternErrMsg: '',
          },
          {
            name: 'StorageReservoir',
            jsonPath: 'Connection.storageReservoir',
            label: 'wc.create.groups.fields.storageType',
            pattern: '',
            type: 'singleValueList',
            isRequired: true,
            isDisabled: false,
            url: '/wcms/masters/storagereservoirs/_search?|$..name|$..name',
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'waterTreatment',
            jsonPath: 'Connection.waterTreatment',
            label: 'wc.create.groups.connectionDetails.waterTreatment',
            pattern: '',
            type: 'singleValueList',
            isRequired: false,
            isDisabled: false,
            url: '/wcms/masters/treatmentplants/_search?|$..name|$..name',
            requiredErrMsg: '',
            isKeyValuePair: true,
            patternErrMsg: '',
          },
          {
            name: 'sumpCapacity',
            jsonPath: 'Connection.sumpCapacity',
            label: 'wc.create.groups.connectionDetails.fields.sumpCapacity',
            pattern: '^\\d{1,15}$',
            type: 'number',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'Sequence No',
            jsonPath: 'Connection.billSequenceNumber',
            label: 'wc.create.groups.connectionDetails.fields.billingNumber',
            pattern: '^[1-9]\\d{0,3}(\\.\\d{0,3})*(,\\d+)?$',
            type: 'number',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'PlumberName',
            jsonPath: 'Connection.plumberName',
            label: 'wc.create.groups.connectionDetails.fields.plumberName',
            pattern: '^([a-zA-Z0-9_-\\s]){3,50}$',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'NoOfTaps',
            jsonPath: 'Connection.numberOfTaps',
            label: 'wc.create.groups.connectionDetails.fields.noOfTaps',
            pattern: '^\\d{0,4}$',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'BuildingName',
            jsonPath: 'Connection.connectionLocation.buildingName',
            label: 'wc.create.groups.connectionDetails.fields.buildingName',
            pattern: '^([a-zA-Z0-9_-\\s]){0,24}$',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'BuildingAddress',
            jsonPath: 'Connection.connectionLocation.billingAddress',
            label: 'wc.create.groups.connectionDetails.fields.buildingAddress',
            pattern: '^([a-zA-Z0-9_-\\s]){0,256}$',
            type: 'text',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'RoadName',
            jsonPath: 'Connection.connectionLocation.roadName',
            label: 'wc.create.groups.connectionDetails.fields.roadName',
            pattern: '^([a-zA-Z0-9_-\\s]){0,32}$',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'GISNo',
            jsonPath: 'Connection.connectionLocation.gisNumber',
            label: 'wc.create.groups.connectionDetails.fields.gISNo',
            pattern: '^([a-zA-Z0-9_-\\s]){0,15}$',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'numberOfPersons',
            jsonPath: 'Connection.numberOfPersons',
            label: 'wc.create.groups.connectionDetails.fields.numberOfPersons',
            type: 'number',
            pattern: '^\\d{0,4}$',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            depedants: [
              {
                jsonPath: 'Connection.numberOfFamily',
                type: 'textField',
                pattern: "getVal('Connection.numberOfPersons')!=''? (Math.ceil(getVal('Connection.numberOfPersons')/4)):0",
                rg: '',
                isRequired: false,
                requiredErrMsg: '',
                patternErrMsg: '',
              },
            ],
          },
          {
            name: 'numberOfFamily',
            jsonPath: 'Connection.numberOfFamily',
            label: 'wc.create.numberOfFamily',
            pattern: '^\\d{1,16}$',
            type: 'number',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'Outside ULB',
            jsonPath: 'Connection.outsideULB',
            label: 'wc.create.groups.connectionDetails.fields.outSide',
            pattern: '',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            defaultValue: false,
          },
          {
            name: 'fromDate',
            jsonPath: 'Connection.fromDate',
            label: 'wc.create.fromDate',
            pattern: '',
            type: 'datePicker',
            hide: true,
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            expression: '$Connection.fromDate < $Connection.toDate',
            expressionMsg: 'From Date should be less than To Date',
          },
          {
            name: 'toDate',
            jsonPath: 'Connection.toDate',
            label: 'wc.create.toDate',
            pattern: '',
            hide: true,
            type: 'datePicker',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            expression: '$Connection.fromDate < $Connection.toDate',
            expressionMsg: 'From Date should be less than To Date',
          },
        ],
      },
      {
        label: 'wc.create.meter.title',
        name: 'Metered',
        hide: true,
        children: [meterReading],
        fields: [
          {
            name: 'MeterOwner',
            jsonPath: 'Connection.meter[0].meterOwner',
            label: 'wc.group.meterOwner',
            pattern: '^[s.]*([^s.][s.]*){0,50}$',
            type: 'singleValueList',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            url: '/wcms-connection/connection/_getmeterownertypes?|$..key|$..object',
          },
          {
            name: 'MeterModel',
            jsonPath: 'Connection.meter[0].meterModel',
            label: 'wc.group.meterModal',
            pattern: '',
            type: 'singleValueList',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            url: '/wcms-connection/connection/_getmetermodeltypes?|$..key|$..object',
          },
          {
            name: 'meterMake',
            jsonPath: 'Connection.meter[0].meterMake',
            label: 'wc.group.meterMake',
            pattern: '',
            type: 'singleValueList',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            url: '/wcms/masters/metercosts/_search?|$..meterMake|$..meterMake',
          },
          {
            name: 'meterSlNo',
            jsonPath: 'Connection.meter[0].meterSlNo',
            label: 'wc.group.meterNumber',
            pattern: '^[s.]*([^s.][s.]*){1,20}$',
            type: 'text',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'meterCost',
            jsonPath: 'Connection.meter[0].meterCost',
            label: 'wc.group.meterCost',
            pattern: '^\\d{1,8}$',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'initialMeterReading',
            jsonPath: 'Connection.meter[0].initialMeterReading',
            label: 'wc.group.initialMeterReading',
            pattern: '^\\d{1,8}$',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'maximumMeterReading',
            jsonPath: 'Connection.meter[0].maximumMeterReading',
            label: 'wc.group.maximumReading',
            pattern: '^\\d{1,8}$',
            type: 'number',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
        ],
      },
      {
        label: 'wc.create.donation.subtitle',
        name: 'Donation',
        fields: [
          {
            name: 'SpecialDonationCharges',
            jsonPath: 'Connection.donationCharge',
            label: 'wc.create.SpecialDonationCharges',
            pattern: '^[1-9]\\d{0,5}(\\.\\d{0,2})*(,\\d+)?$',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'receiptNumber',
            jsonPath: 'Connection.manualReceiptNumber',
            label: 'wc.create.receiptNumber',
            pattern: '^[s.]*([^s.][s.]*){1,20}$',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'receiptDate',
            jsonPath: 'Connection.manualReceiptDate',
            maxDate: 'today',
            label: 'wc.create.receiptDate',
            pattern: '',
            type: 'datePicker',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: 'future date does not be allowed', //Remove required messages
            patternErrMsg: 'future date does not be allowed',
          },
        ],
      },
      {
        label: 'wc.create.groups.fileDetails.title',
        name: 'Documents',
        fields: [
          {
            name: 'File',
            jsonPath: 'Connection.documents',
            type: 'documentList',
            pathToArray: 'DocumentTypeApplicationTypes',
            displayNameJsonPath: 'documentType',
            url: '/wcms/masters/documenttypes-applicationtypes/_search?applicationType=NEWCONNECTION',
            autoFillFields: [
              {
                name: 'document',
                jsonPath: 'documentTypeId',
              },
            ],
          },
        ],
      },
    ],
  },
  'wc.view': {
    numCols: 12 / 3,
    version: 'v1',
    url: '/wcms-connection/connection/_search?consumerNumber={consumerNumber}',
    useTimestamp: true,
    tenantIdRequired: true, //Instead of boolean value give json path
    objectName: 'Connection',
    level: 0,
    groups: [
      {
        label: 'wc.create.groups.applicationParticular.title', //Cut short labels by taking initial path from parent
        name: 'applicationParticular', //Follow Title case pattern
        children: [],
        multiple: false,
        fields: [
          {
            name: 'With Property',
            jsonPath: 'Connection[0].withProperty',
            label: 'wc.group.withProperty',
            pattern: '',
            type: 'radio',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            values: [{ label: 'wc.group.withProperty', value: true }, { label: 'wc.group.withoutProperty', value: false }],
            defaultValue: false,
            showHideFields: [
              {
                ifValue: false,
                hide: [
                  {
                    name: 'applicantDetailsWithProp',
                    isGroup: true,
                    isField: false,
                  },
                ],
                show: [
                  {
                    name: 'applicantDetailsWithoutProp',
                    isGroup: true,
                    isField: false,
                  },
                  {
                    name: 'addressDetails',
                    isGroup: true,
                    isField: false,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        label: 'wc.create.groups.applicantDetails.title', //Cut short labels by taking initial path from parent
        name: 'applicantDetailsWithoutProp', //Follow Title case pattern
        jsonPath: 'Connection[0].connectionOwners',
        multiple: true,
        hide: true,
        fields: [
          {
            name: 'NameOfApplicant',
            jsonPath: 'Connection[0].connectionOwners[0].name',
            label: 'wc.create.groups.applicantDetails.nameOfApplicant',
            pattern: '^([a-zA-Z0-9_-\\s]){3,100}$',
            type: 'text',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'MobileNumber',
            jsonPath: 'Connection[0].connectionOwners[0].mobileNumber',
            label: 'wc.create.groups.applicantDetails.mobileNumber',
            pattern: '',
            type: 'mobileNumber',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'Email',
            jsonPath: 'Connection[0].connectionOwners[0].emailId',
            label: 'wc.create.groups.applicantDetails.email',
            pattern: '',
            type: 'email',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            defaultValue: '',
          },
          {
            name: 'AadharNumber',
            jsonPath: 'Connection[0].connectionOwners[0].aadhaarNumber',
            label: 'wc.create.groups.applicantDetails.adharNumber',
            pattern: '',
            type: 'aadhar',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'gender',
            jsonPath: 'Connection[0].connectionOwners[0].gender',
            label: 'employee.Employee.fields.User.gender',
            pattern: '',
            type: 'singleValueList',
            url: '/egov-common-masters/genders/_search?|$.Gender.*|$.Gender.*',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'Primary Owner',
            jsonPath: 'Connection[0].connectionOwners[0].primaryOwner',
            label: 'pt.create.groups.ownerDetails.fields.primaryOwner',
            pattern: '',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            defaultValue: true,
          },
        ],
      },
      {
        name: 'addressDetails',
        multiple: false,
        hide: true,
        fields: [
          {
            name: 'ConsumerNumber',
            jsonPath: 'Connection[0].consumerNumber',
            label: 'wc.create.groups.applicantDetails.consumerNumber',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'AddressNo',
            jsonPath: 'Connection[0].houseNumber',
            label: 'wc.create.groups.applicantDetails.addressNumber',
            pattern: '^[s.]*([^s.][s.]*){0,16}$',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'Address',
            jsonPath: 'Connection[0].address.addressLine1',
            label: 'wc.create.groups.applicantDetails.address',
            pattern: '^.{0,255}$',
            type: 'text',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'City',
            jsonPath: 'Connection[0].address.city',
            label: 'employee.Employee.fields.city',
            pattern: '^([a-zA-Z0-9_-\\s]){2,50}$',
            type: 'text',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'PinCode',
            jsonPath: 'Connection[0].address.pinCode',
            label: 'pt.create.groups.propertyAddress.fields.pin',
            pattern: '',
            type: 'pinCode',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'zoneName',
            jsonPath: 'Connection[0].connectionLocation.revenueBoundary.code',
            label: 'wc.create.groups.fields.zone',
            pattern: '',
            type: 'singleValueList',
            url: '',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            configUrl: '/wcms/masters/waterchargesconfig/_search?name=HIERACHYTYPEFORWC',
            url:
              '/egov-location/boundarys/boundariesByBndryTypeNameAndHierarchyTypeName?&boundaryTypeName=ZONE&hierarchyTypeName={WaterConfigurationValue[0].value}|$.Boundary.*.code|$.Boundary.*.name',
          },
          {
            name: 'wardName',
            jsonPath: 'Connection[0].connectionLocation.adminBoundary.code',
            label: 'wc.create.groups.fields.ward',
            pattern: '',
            type: 'singleValueList',
            url:
              '/egov-location/boundarys/boundariesByBndryTypeNameAndHierarchyTypeName?&boundaryTypeName=WARD&hierarchyTypeName=ADMINISTRATION|$.Boundary.*.code|$.Boundary.*.name',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'Locality',
            jsonPath: 'Connection[0].connectionLocation.locationBoundary.code',
            label: 'wc.create.groups.applicantDetails.locality',
            pattern: '',
            type: 'singleValueList',
            url:
              '/egov-location/boundarys/boundariesByBndryTypeNameAndHierarchyTypeName?&boundaryTypeName=LOCALITY&hierarchyTypeName=LOCATION|$.Boundary.*.code|$.Boundary.*.name',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'executionDate',
            jsonPath: 'Connection[0].executionDate',
            label: 'wc.create.groups.applicantDetails.connectionDate',
            maxDate: 'today-2',
            pattern: '',
            type: 'datePicker',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'ConsumerNo',
            jsonPath: 'Connection[0].legacyConsumerNumber',
            label: 'wc.create.groups.applicantDetails.consumerNo',
            pattern: '^\\d{1,16}$',
            type: 'text',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'ManualConsumerNo',
            jsonPath: 'Connection[0].manualConsumerNumber',
            label: 'wc.create.groups.applicantDetails.manualConsumerNo',
            pattern: '^\\d{1,16}$',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
        ],
      },
      {
        label: 'wc.create.groups.applicantDetails.title', //Cut short labels by taking initial path from parent
        name: 'applicantDetailsWithProp', //Follow Title case pattern
        children: [],
        multiple: false,
        hide: false,
        fields: [
          {
            name: 'ConsumerNumber',
            jsonPath: 'Connection[0].consumerNumber',
            label: 'wc.create.groups.applicantDetails.consumerNumber',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'AssessmentNumber',
            jsonPath: 'Connection[0].property.propertyIdentifier',
            label: 'wc.create.groups.applicantDetails.propertyIdentifier',
            pattern: '',
            type: 'textSearch',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'NameOfApplicant',
            jsonPath: 'Connection[0].property.propertyOwner[0].name',
            label: 'wc.create.groups.applicantDetails.nameOfApplicant',
            pattern: '^[s.]*([^s.][s.]*){0,100}$',
            type: 'text',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'MobileNumber',
            jsonPath: 'Connection[0].property.propertyOwner[0].mobileNumber',
            label: 'wc.create.groups.applicantDetails.mobileNumber',
            pattern: '',
            type: 'mobileNumber',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'Email',
            jsonPath: 'Connection[0].property.propertyOwner[0].emailId',
            label: 'wc.create.groups.applicantDetails.email',
            pattern: '',
            type: 'email',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
            isHidden: false,
            defaultValue: '',
          },
          {
            name: 'AadharNumber',
            jsonPath: 'Connection[0].property.propertyOwner[0].aadhaarNumber',
            label: 'wc.create.groups.applicantDetails.adharNumber',
            pattern: '',
            type: 'aadhar',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'Address',
            jsonPath: 'Connection[0].property.address',
            label: 'wc.create.groups.applicantDetails.address',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'PinCode',
            jsonPath: 'Connection[0].property.pinCode',
            label: 'pt.create.groups.propertyAddress.fields.pin',
            pattern: '',
            type: 'pinCode',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'Zone',
            jsonPath: 'Connection[0].property.zone',
            label: 'wc.create.groups.applicantDetails.zone',
            pattern: '',
            type: 'singleValueList',
            isRequired: false,
            isDisabled: true,
            url: '',
            requiredErrMsg: '',
            patternErrMsg: '',
            configUrl: '/wcms/masters/waterchargesconfig/_search?name=HIERACHYTYPEFORWC',
            url:
              '/egov-location/boundarys/boundariesByBndryTypeNameAndHierarchyTypeName?&boundaryTypeName=ZONE&hierarchyTypeName={WaterConfigurationValue[0].value}|$.Boundary.*.code|$.Boundary.*.name',
          },
          {
            name: 'Locality',
            jsonPath: 'Connection[0].property.locality',
            label: 'wc.create.groups.applicantDetails.locality',
            pattern: '',
            type: 'singleValueList',
            url:
              '/egov-location/boundarys/boundariesByBndryTypeNameAndHierarchyTypeName?&boundaryTypeName=LOCALITY&hierarchyTypeName=LOCATION|$.Boundary.*.code|$.Boundary.*.name',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'propertyTaxDue',
            jsonPath: 'Connection[0].property.propertyTaxDue',
            label: 'wc.create.groups.applicantDetails.propertyTaxDue',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'consumerNo',
            jsonPath: 'Connection[0].legacyConsumerNumber',
            label: 'wc.create.groups.applicantDetails.consumerNo',
            pattern: '',
            type: 'text',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'ManualConsumerNo',
            jsonPath: 'Connection[0].manualConsumerNumber',
            label: 'wc.create.groups.applicantDetails.manualConsumerNo',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'executionDate',
            jsonPath: 'Connection[0].executionDate',
            label: 'wc.create.groups.applicantDetails.connectionDate',
            maxDate: 'today-2',
            pattern: '',
            type: 'datePicker',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
        ],
      },
      {
        label: 'wc.create.groups.connectionDetails.title',
        name: 'connectionDetails',
        multiple: false,
        fields: [
          // {
          //   "name": "PropertyType",
          //   "jsonPath": "Connection[0].property.propertyType",
          //   "label": "wc.create.groups.connectionDetails.propertyType",
          //   "pattern": "",
          //   "type": "singleValueList",
          //   "isRequired": false,
          //   "isDisabled": false,
          //   "url": "/pt-property/property/propertytypes/_search?|$..name|$..name",
          //   "requiredErrMsg": "",
          //   "patternErrMsg": ""
          // },
          // {
          //   "name": "CategoryType",
          //   "jsonPath": "Connection[0].categoryType",
          //   "label": "wc.create.groups.connectionDetails.categoryType",
          //   "pattern": "",
          //   "type": "singleValueList",
          //   "isRequired": false,
          //   "isDisabled": false,
          //   "requiredErrMsg": "",
          //   "patternErrMsg": ""
          // },
          {
            name: 'UsageType',
            jsonPath: 'Connection[0].usageTypeName',
            label: 'wc.create.groups.connectionDetails.usageType',
            pattern: '',
            type: 'singleValueList',
            isRequired: false,
            isDisabled: false,
            url: '/wcms/masters/usagetypes/_search?|$..code|$..name',
            requiredErrMsg: '',
            patternErrMsg: '',
            depedants: [
              {
                jsonPath: 'Connection[0].subUsageTypeName',
                type: 'dropDown',
                pattern: '/wcms/masters/usagetypes/_search?&parent={Connection.usageTypeName}&isSubUsageType=true|$..code|$..name',
              },
            ],
          },
          {
            name: 'subUsageType',
            jsonPath: 'Connection[0].subUsageTypeName',
            label: 'wc.create.groups.connectionDetails.subUsageType',
            pattern: '',
            type: 'singleValueList',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            defaultValue: '',
          },
          {
            name: 'hscPipeSizeType',
            jsonPath: 'Connection[0].hscPipeSizeType',
            label: 'wc.create.groups.connectionDetails.hscPipeSizeType',
            pattern: '',
            type: 'singleValueList',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            url: '/wcms/masters/pipesizes/_search?|$..sizeInMilimeter|$..sizeInInch',
          },
          {
            name: 'applicationType',
            jsonPath: 'Connection[0].applicationType',
            label: 'wc.create.groups.connectionDetails.applicationType',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            isHidden: true,
            defaultValue: 'NEWCONNECTION',
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'connectionStatus',
            jsonPath: 'Connection[0].connectionStatus',
            label: 'wc.create.groups.connectionDetails.applicationType',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            isHidden: true,
            defaultValue: 'INPROGRESS',
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'billingType',
            jsonPath: 'Connection[0].billingType',
            label: 'wc.create.groups.connectionDetails.billingType',
            pattern: '',
            type: 'singleValueList',
            isRequired: false,
            isDisabled: false,
            url: '/wcms-connection/connection/_getbillingtypes?|$..key|$..object',
            requiredErrMsg: '',
            patternErrMsg: '',
            showHideFields: [
              {
                ifValue: 'METERED',
                hide: [
                  {
                    name: 'description',
                    isGroup: false,
                    isField: true,
                  },
                ],
                show: [
                  {
                    name: 'Metered',
                    isGroup: true,
                    isField: false,
                  },
                ],
              },
            ],
          },
          {
            name: 'ConnectionType',
            jsonPath: 'Connection[0].connectionType',
            label: 'wc.create.groups.connectionDetails.connectionType',
            pattern: '',
            type: 'singleValueList',
            isRequired: false,
            isDisabled: false,
            url: '/wcms-connection/connection/_getconnectiontypes?|$..key|$..object',
            requiredErrMsg: '',
            patternErrMsg: '',
            showHideFields: [
              {
                ifValue: 'TEMPORARY',
                show: [
                  {
                    name: 'fromDate',
                    isGroup: false,
                    isField: true,
                  },
                  {
                    name: 'toDate',
                    isGroup: false,
                    isField: true,
                  },
                ],
                hide: [],
              },
            ],
          },
          {
            name: 'SourceType',
            jsonPath: 'Connection[0].sourceType',
            label: 'wc.create.groups.connectionDetails.sourceType',
            pattern: '',
            type: 'singleValueList',
            isRequired: false,
            isDisabled: false,
            url: '/wcms/masters/sourcetypes/_search?|$..name|$..name',
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          // {
          //   "name": "supplyType",
          //   "jsonPath": "Connection[0].supplyType",
          //   "label": "wc.create.groups.connectionDetails.supplyType",
          //   "pattern": "",
          //   "type": "singleValueList",
          //   "isRequired": false,
          //   "isDisabled": false,
          //   "url": "/wcms/masters/supplytype/_search?|$..name|$..name",
          //   "requiredErrMsg": "",
          //   "patternErrMsg": ""
          // },
          {
            name: 'StorageReservoir',
            jsonPath: 'Connection[0].storageReservoir',
            label: 'wc.create.groups.fields.storageType',
            pattern: '',
            type: 'singleValueList',
            isRequired: true,
            isDisabled: false,
            url: '/wcms/masters/storagereservoirs/_search?|$..name|$..name',
            requiredErrMsg: '',
            patternErrMsg: '',
          },

          {
            name: 'waterTreatment',
            jsonPath: 'Connection[0].waterTreatment',
            label: 'wc.create.groups.connectionDetails.waterTreatment',
            pattern: '',
            type: 'singleValueList',
            isRequired: false,
            isDisabled: false,
            url: '/wcms/masters/treatmentplants/_search?|$..name|$..name',
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'sumpCapacity',
            jsonPath: 'Connection[0].sumpCapacity',
            label: 'wc.create.groups.connectionDetails.fields.sumpCapacity',
            pattern: '^(0|[1-9][0-9]*)$',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'numberOfPersons',
            jsonPath: 'Connection[0].numberOfPersons',
            label: 'wc.create.groups.connectionDetails.fields.numberOfPersons',
            type: 'number',
            pattern: '^(0|[1-9][0-9]*)$',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
            depedants: [
              {
                jsonPath: 'Connection[0].numberOfFamily',
                type: 'number',
                pattern: "getVal('Connection.numberOfPersons')!=''? (Math.ceil(getVal('Connection.numberOfPersons')/4)):0",
                rg: '',
                isRequired: false,
                requiredErrMsg: '',
                patternErrMsg: '',
              },
            ],
          },
          {
            name: 'numberOfFamily',
            jsonPath: 'Connection[0].numberOfFamily',
            label: 'wc.create.numberOfFamily',
            pattern: '',
            type: 'number',
            isRequired: false,
            isDisabled: true,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'Sequence No',
            jsonPath: 'Connection[0].billSequenceNumber',
            label: 'wc.create.groups.connectionDetails.fields.billingNumber',
            pattern: '^([0-9]+(\\.[0-9][0-9]*)$',
            type: 'number',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'PlumberName',
            jsonPath: 'Connection[0].plumberName',
            label: 'wc.create.groups.connectionDetails.fields.plumberName',
            pattern: '',
            type: 'textarea',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'NoOfTaps',
            jsonPath: 'Connection[0].numberOfTaps',
            label: 'wc.create.groups.connectionDetails.fields.noOfTaps',
            pattern: '^(0|[1-9][0-9]*)$',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'BuildingName',
            jsonPath: 'Connection[0].connectionLocation.buildingName',
            label: 'wc.create.groups.connectionDetails.fields.buildingName',
            pattern: '^([a-zA-Z0-9_-\\s]){0,24}$',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'BuildingAddress',
            jsonPath: 'Connection[0].connectionLocation.billingAddress',
            label: 'wc.create.groups.connectionDetails.fields.buildingAddress',
            pattern: '^([a-zA-Z0-9_-\\s]){0,256}$',
            type: 'text',
            isRequired: true,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'RoadName',
            jsonPath: 'Connection[0].connectionLocation.roadName',
            label: 'wc.create.groups.connectionDetails.fields.roadName',
            pattern: '^([a-zA-Z0-9_-\\s]){0,32}$',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'GISNo',
            jsonPath: 'Connection[0].connectionLocation.gisNumber',
            label: 'wc.create.groups.connectionDetails.fields.gISNo',
            pattern: '^([a-zA-Z0-9_-\\s]){0,15}$',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'Outside ULB',
            jsonPath: 'Connection[0].outsideULB',
            label: 'wc.create.groups.connectionDetails.fields.outSide',
            pattern: '',
            type: 'checkbox',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'fromDate',
            jsonPath: 'Connection[0].fromDate',
            label: 'wc.create.fromDate',
            pattern: '',
            type: 'datePicker',
            isHidden: true,
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'toDate',
            jsonPath: 'Connection[0].toDate',
            label: 'wc.create.toDate',
            pattern: '',
            isHidden: true,
            type: 'datePicker',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
        ],
      },
      {
        label: 'wc.create.meter.title',
        name: 'Metered',
        hide: true,
        children: [meterReadingView],
        fields: [
          {
            name: 'meterOwner',
            jsonPath: 'Connection[0].meter[0].meterOwner',
            label: 'wc.group.meterOwner',
            pattern: '^[s.]*([^s.][s.]*){0,50}$',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'meterModel',
            jsonPath: 'Connection[0].meter[0].meterModel',
            label: 'wc.group.meterModal',
            pattern: '^[s.]*([^s.][s.]*){0,50}$',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'meterMake',
            jsonPath: 'Connection[0].meter[0].meterMake',
            label: 'wc.group.meterMake',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'meterSlNo',
            jsonPath: 'Connection[0].meter[0].meterSlNo',
            label: 'wc.group.meterNumber',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'meterCost',
            jsonPath: 'Connection[0].meter[0].meterCost',
            label: 'wc.group.meterCost',
            pattern: '^\\d{1,8}$',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'initialMeterReading',
            jsonPath: 'Connection[0].meter[0].initialMeterReading',
            label: 'wc.group.initialMeterReading',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'maximumMeterReading',
            jsonPath: 'Connection[0].meter[0].maximumMeterReading',
            label: 'wc.group.maximumReading',
            pattern: '^\\d{1,8}$',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
        ],
      },
      {
        label: 'wc.create.donation.subtitle',
        name: 'Donation',
        fields: [
          {
            name: 'SpecialDonationCharges',
            jsonPath: 'Connection[0].donationCharge',
            label: 'wc.create.SpecialDonationCharges',
            pattern: '^[1-9]\\d{0,5}(\\.\\d{0,2})*(,\\d+)?$',
            type: 'number',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'receiptNumber',
            jsonPath: 'Connection[0].manualReceiptNumber',
            label: 'wc.create.receiptNumber',
            pattern: '',
            type: 'text',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '',
            patternErrMsg: '',
          },
          {
            name: 'receiptDate',
            jsonPath: 'Connection[0].manualReceiptDate',
            maxDate: 'today',
            label: 'wc.create.receiptDate',
            pattern: '',
            type: 'datePicker',
            isRequired: false,
            isDisabled: false,
            requiredErrMsg: '', //Remove required messages
            patternErrMsg: '',
          },
        ],
      },
    ],
  },
};

export default dat;
