export const PROPERTY_FETCH_PENDING = "PROPERTY_FETCH_PENDING";
export const PROPERTY_FETCH_COMPLETE = "PROPERTY_FETCH_COMPLETE";
export const PROPERTY_FETCH_ERROR = "PROPERTY_FETCH_ERROR";

export const DRAFT_FETCH_PENDING = "DRAFT_FETCH_PENDING";
export const DRAFT_FETCH_COMPLETE = "DRAFT_FETCH_COMPLETE";
export const DRAFT_FETCH_ERROR = "DRAFT_FETCH_ERROR";

export const FAILED_TRANSACTION_FETCH_PENDING = "FAILED_TRANSACTION_FETCH_PENDING";
export const FAILED_TRANSACTION_FETCH_COMPLETE = "FAILED_TRANSACTION_FETCH_COMPLETE";
export const FAILED_TRANSACTION_FETCH_ERROR = "FAILED_TRANSACTION_FETCH_ERROR";

export const SUCCESS_TRANSACTION_FETCH_PENDING = "SUCCESS_TRANSACTION_FETCH_PENDING";
export const SUCCESS_TRANSACTION_FETCH_COMPLETE = "SUCCESS_TRANSACTION_FETCH_COMPLETE";
export const SUCCESS_TRANSACTION_FETCH_ERROR = "SUCCESS_TRANSACTION_FETCH_ERROR";

export const RECEIPT_FETCH_ERROR = "RECEIPT_FETCH_ERROR";
export const RECEIPT_FETCH_COMPLETE = "RECEIPT_FETCH_COMPLETE";
export const RECEIPT_FETCH_PENDING = "RECEIPT_FETCH_PENDING";

export const ASSESSMENT_STATUS_ERROR = "ASSESSMENT_STATUS_ERROR";
export const ASSESSMENT_STATUS_COMPLETE = "ASSESSMENT_STATUS_COMPLETE";
export const ASSESSMENT_STATUS_PENDING = "ASSESSMENT_STATUS_PENDING";

export const SINGLE_ASSESSMENT_STATUS_ERROR = "SINGLE_ASSESSMENT_STATUS_ERROR";
export const SINGLE_ASSESSMENT_STATUS_COMPLETE = "SINGLE_ASSESSMENT_STATUS_COMPLETE";
export const SINGLE_ASSESSMENT_STATUS_PENDING = "SINGLE_ASSESSMENT_STATUS_PENDING";

export const PROPERTY_FETCH_BILL_PENDING = "PROPERTY_FETCH_BILL_PENDING";
export const PROPERTY_FETCH_BILL_COMPLETE = "PROPERTY_FETCH_BILL_COMPLETE";
export const PROPERTY_FETCH_BILL_ERROR = "PROPERTY_FETCH_BILL_ERROR";

export const PROPERTY_FETCH_RECEIPT_PENDING = "PROPERTY_FETCH_RECEIPT_PENDING";
export const PROPERTY_FETCH_RECEIPT_COMPLETE = "PROPERTY_FETCH_RECEIPT_COMPLETE";
export const PROPERTY_FETCH_RECEIPT_ERROR = "PROPERTY_FETCH_RECEIPT_ERROR";

export const PROPERTY_FETCH_ASSESSMENTS_PENDING = "PROPERTY_FETCH_ASSESSMENTS_PENDING";
export const PROPERTY_FETCH_ASSESSMENTS_COMPLETE = "PROPERTY_FETCH_ASSESSMENTS_COMPLETE";
export const PROPERTY_FETCH_ASSESSMENTS_ERROR = "PROPERTY_FETCH_ASSESSMENTS_ERROR";

export const PROPERTY_DOWNLOAD_RECEIPT_PENDING = "PROPERTY_DOWNLOAD_RECEIPT_PENDING";
export const PROPERTY_DOWNLOAD_RECEIPT_COMPLETE = "PROPERTY_DOWNLOAD_RECEIPT_COMPLETE";
export const PROPERTY_DOWNLOAD_RECEIPT_ERROR = "PROPERTY_DOWNLOAD_RECEIPT_ERROR";


export const MOHALLA_FETCH_COMPLETE = "MOHALLA_FETCH_COMPLETE";

export const RESET_PROPERTY_STATE="RESET_PROPERTY_STATE";
