CREATE SEQUENCE SEQ_SUMMON_CODE;
CREATE SEQUENCE SEQ_SUMMON_REFERENCE;
CREATE SEQUENCE SEQ_CASE_REFERENCE;
CREATE SEQUENCE SEQ_ADVOCATE_CODE;
CREATE SEQUENCE SEQ_ADVOCATEPAYMENT_CODE;
CREATE SEQUENCE SEQ_OPINION_CODE;

